MegaIsland_Castle_2F_MapScripts::
	.byte 0

MegaIsland_Castle_2F_EventScript_Leon::
	msgbox MegaIsland_Castle_2F_Text_Leon, MSGBOX_NPC
	end

MegaIsland_Castle_2F_Text_Leon:
	.string "LEON: Huh? Is this the way to my\n"
	.string "room?\p"
	.string "…They all look the same.\n"
	.string "I always get lost.\p"
	.string "I'm LEON, the CHAMPION of GALAR!\p"
	.string "My CHARIZARD's never been this fired\n"
	.string "up. Let's have a champion time!$"
