# Generated by tools/kanto_port/port_kanto.py from pokefirered.

$(TILESETGFXDIR)/primary/kanto_building/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 640 -Wnum_tiles

$(TILESETGFXDIR)/primary/kanto_general/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 640 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_pallet_town/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 76 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_lavender_town/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 256 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_cinnabar_island/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 128 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_pokemon_center/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 376 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_cable_club/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 632 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_fuchsia_gym/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 92 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_pewter_gym/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 207 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_saffron_gym/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 82 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_viridian_forest/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 101 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_seafoam_islands/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 318 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_generic_building_2/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 152 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_underground_path/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 50 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_restaurant_hotel/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 76 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_burgled_house/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 172 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_berry_forest/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 101 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_sevii_islands_45/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 374 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_pokemon_league/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 340 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_viridian_city/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 112 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_vermilion_city/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 140 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_indigo_plateau/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 247 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_cave/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 256 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_bike_shop/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 60 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_viridian_gym/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 90 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_cerulean_gym/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 119 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_cinnabar_gym/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 146 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_unused_gatehouse_1/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 144 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_unused_gatehouse_2/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 144 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_power_plant/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 80 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_pokemon_tower/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 128 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_school/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 50 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_dummy_3/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 2 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_navel_rock/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 282 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_sevii_islands_67/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 374 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_hall_of_fame/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 208 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_pewter_city/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 280 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_celadon_city/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 244 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_saffron_city/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 262 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_dummy_1/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 2 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_generic_building_1/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 63 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_hoenn_building/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 383 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_vermilion_gym/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 247 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_ss_anne/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 245 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_rock_tunnel/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 256 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_cerulean_cave/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 246 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_sea_cottage/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 68 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_safari_zone_building/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 90 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_fan_club_daycare/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 85 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_dummy_4/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 2 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_tanoby_ruins/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 74 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_trainer_tower/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 343 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_cerulean_city/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 158 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_fuchsia_city/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 191 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_mart/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 36 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_museum/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 137 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_lab/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 102 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_game_corner/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 171 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_celadon_gym/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 103 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_dummy_2/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 2 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_digletts_cave/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 248 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_department_store/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 201 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_pokemon_mansion/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 350 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_condominiums/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 384 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_mt_ember/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 288 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_sevii_islands_123/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 374 -Wnum_tiles

$(TILESETGFXDIR)/secondary/kanto_island_harbor/tiles.4bpp: %.4bpp: %.png
	$(GFX) $< $@ -num_tiles 165 -Wnum_tiles
