// Generated by tools/kanto_port/port_trainers.py from pokefirered. Do not edit by hand.
// Included by data.c before the trainer front pic tables

static const u32 gTrainerFrontPic_KantoAromaLady[] = INCGFX_U32("graphics/trainers/kanto/front_pics/aroma_lady_front_pic.png", ".4bpp.lz");
static const u32 gTrainerPalette_KantoAromaLady[] = INCGFX_U32("graphics/trainers/kanto/palettes/aroma_lady.pal", ".gbapal.lz");
static const u32 gTrainerFrontPic_KantoBeauty[] = INCGFX_U32("graphics/trainers/kanto/front_pics/beauty_front_pic.png", ".4bpp.lz");
static const u32 gTrainerPalette_KantoBeauty[] = INCGFX_U32("graphics/trainers/kanto/palettes/beauty.pal", ".gbapal.lz");
static const u32 gTrainerFrontPic_KantoBiker[] = INCGFX_U32("graphics/trainers/kanto/front_pics/biker_front_pic.png", ".4bpp.lz");
static const u32 gTrainerPalette_KantoBiker[] = INCGFX_U32("graphics/trainers/kanto/palettes/biker.pal", ".gbapal.lz");
static const u32 gTrainerFrontPic_KantoBirdKeeper[] = INCGFX_U32("graphics/trainers/kanto/front_pics/bird_keeper_front_pic.png", ".4bpp.lz");
static const u32 gTrainerPalette_KantoBirdKeeper[] = INCGFX_U32("graphics/trainers/kanto/palettes/bird_keeper.pal", ".gbapal.lz");
static const u32 gTrainerFrontPic_KantoBlackBelt[] = INCGFX_U32("graphics/trainers/kanto/front_pics/black_belt_front_pic.png", ".4bpp.lz");
static const u32 gTrainerPalette_KantoBlackBelt[] = INCGFX_U32("graphics/trainers/kanto/palettes/black_belt.pal", ".gbapal.lz");
static const u32 gTrainerFrontPic_KantoLeaderGiovanni[] = INCGFX_U32("graphics/trainers/kanto/front_pics/leader_giovanni_front_pic.png", ".4bpp.lz");
static const u32 gTrainerPalette_KantoLeaderGiovanni[] = INCGFX_U32("graphics/trainers/kanto/palettes/leader_giovanni.pal", ".gbapal.lz");
static const u32 gTrainerFrontPic_KantoBugCatcher[] = INCGFX_U32("graphics/trainers/kanto/front_pics/bug_catcher_front_pic.png", ".4bpp.lz");
static const u32 gTrainerPalette_KantoBugCatcher[] = INCGFX_U32("graphics/trainers/kanto/palettes/bug_catcher.pal", ".gbapal.lz");
static const u32 gTrainerFrontPic_KantoBurglar[] = INCGFX_U32("graphics/trainers/kanto/front_pics/burglar_front_pic.png", ".4bpp.lz");
static const u32 gTrainerPalette_KantoBurglar[] = INCGFX_U32("graphics/trainers/kanto/palettes/burglar.pal", ".gbapal.lz");
static const u32 gTrainerFrontPic_KantoCamper[] = INCGFX_U32("graphics/trainers/kanto/front_pics/camper_front_pic.png", ".4bpp.lz");
static const u32 gTrainerPalette_KantoCamper[] = INCGFX_U32("graphics/trainers/kanto/palettes/camper.pal", ".gbapal.lz");
static const u32 gTrainerFrontPic_KantoChanneler[] = INCGFX_U32("graphics/trainers/kanto/front_pics/channeler_front_pic.png", ".4bpp.lz");
static const u32 gTrainerPalette_KantoChanneler[] = INCGFX_U32("graphics/trainers/kanto/palettes/channeler.pal", ".gbapal.lz");
static const u32 gTrainerFrontPic_KantoCooltrainerF[] = INCGFX_U32("graphics/trainers/kanto/front_pics/cool_trainer_f_front_pic.png", ".4bpp.lz");
static const u32 gTrainerPalette_KantoCooltrainerF[] = INCGFX_U32("graphics/trainers/kanto/palettes/cool_trainer_f.pal", ".gbapal.lz");
static const u32 gTrainerFrontPic_KantoCooltrainerM[] = INCGFX_U32("graphics/trainers/kanto/front_pics/cool_trainer_m_front_pic.png", ".4bpp.lz");
static const u32 gTrainerPalette_KantoCooltrainerM[] = INCGFX_U32("graphics/trainers/kanto/palettes/cool_trainer_m.pal", ".gbapal.lz");
static const u32 gTrainerFrontPic_KantoCoolCouple[] = INCGFX_U32("graphics/trainers/kanto/front_pics/cool_couple_front_pic.png", ".4bpp.lz");
static const u32 gTrainerPalette_KantoCoolCouple[] = INCGFX_U32("graphics/trainers/kanto/palettes/cool_couple.pal", ".gbapal.lz");
static const u32 gTrainerFrontPic_KantoCrushGirl[] = INCGFX_U32("graphics/trainers/kanto/front_pics/crush_girl_front_pic.png", ".4bpp.lz");
static const u32 gTrainerPalette_KantoCrushGirl[] = INCGFX_U32("graphics/trainers/kanto/palettes/crush_girl.pal", ".gbapal.lz");
static const u32 gTrainerFrontPic_KantoCrushKin[] = INCGFX_U32("graphics/trainers/kanto/front_pics/crush_kin_front_pic.png", ".4bpp.lz");
static const u32 gTrainerPalette_KantoCrushKin[] = INCGFX_U32("graphics/trainers/kanto/palettes/crush_kin.pal", ".gbapal.lz");
static const u32 gTrainerFrontPic_KantoCueBall[] = INCGFX_U32("graphics/trainers/kanto/front_pics/cue_ball_front_pic.png", ".4bpp.lz");
static const u32 gTrainerPalette_KantoCueBall[] = INCGFX_U32("graphics/trainers/kanto/palettes/cue_ball.pal", ".gbapal.lz");
static const u32 gTrainerFrontPic_KantoEngineer[] = INCGFX_U32("graphics/trainers/kanto/front_pics/engineer_front_pic.png", ".4bpp.lz");
static const u32 gTrainerPalette_KantoEngineer[] = INCGFX_U32("graphics/trainers/kanto/palettes/engineer.pal", ".gbapal.lz");
static const u32 gTrainerFrontPic_KantoFisherman[] = INCGFX_U32("graphics/trainers/kanto/front_pics/fisherman_front_pic.png", ".4bpp.lz");
static const u32 gTrainerPalette_KantoFisherman[] = INCGFX_U32("graphics/trainers/kanto/palettes/fisherman.pal", ".gbapal.lz");
static const u32 gTrainerFrontPic_KantoGamer[] = INCGFX_U32("graphics/trainers/kanto/front_pics/gamer_front_pic.png", ".4bpp.lz");
static const u32 gTrainerPalette_KantoGamer[] = INCGFX_U32("graphics/trainers/kanto/palettes/gamer.pal", ".gbapal.lz");
static const u32 gTrainerFrontPic_KantoGentleman[] = INCGFX_U32("graphics/trainers/kanto/front_pics/gentleman_front_pic.png", ".4bpp.lz");
static const u32 gTrainerPalette_KantoGentleman[] = INCGFX_U32("graphics/trainers/kanto/palettes/gentleman.pal", ".gbapal.lz");
static const u32 gTrainerFrontPic_KantoHiker[] = INCGFX_U32("graphics/trainers/kanto/front_pics/hiker_front_pic.png", ".4bpp.lz");
static const u32 gTrainerPalette_KantoHiker[] = INCGFX_U32("graphics/trainers/kanto/palettes/hiker.pal", ".gbapal.lz");
static const u32 gTrainerFrontPic_KantoJuggler[] = INCGFX_U32("graphics/trainers/kanto/front_pics/juggler_front_pic.png", ".4bpp.lz");
static const u32 gTrainerPalette_KantoJuggler[] = INCGFX_U32("graphics/trainers/kanto/palettes/juggler.pal", ".gbapal.lz");
static const u32 gTrainerFrontPic_KantoLady[] = INCGFX_U32("graphics/trainers/kanto/front_pics/lady_front_pic.png", ".4bpp.lz");
static const u32 gTrainerPalette_KantoLady[] = INCGFX_U32("graphics/trainers/kanto/palettes/lady.pal", ".gbapal.lz");
static const u32 gTrainerFrontPic_KantoLass[] = INCGFX_U32("graphics/trainers/kanto/front_pics/lass_front_pic.png", ".4bpp.lz");
static const u32 gTrainerPalette_KantoLass[] = INCGFX_U32("graphics/trainers/kanto/palettes/lass.pal", ".gbapal.lz");
static const u32 gTrainerFrontPic_KantoLeaderBlaine[] = INCGFX_U32("graphics/trainers/kanto/front_pics/leader_blaine_front_pic.png", ".4bpp.lz");
static const u32 gTrainerPalette_KantoLeaderBlaine[] = INCGFX_U32("graphics/trainers/kanto/palettes/leader_blaine.pal", ".gbapal.lz");
static const u32 gTrainerFrontPic_KantoLeaderBrock[] = INCGFX_U32("graphics/trainers/kanto/front_pics/leader_brock_front_pic.png", ".4bpp.lz");
static const u32 gTrainerPalette_KantoLeaderBrock[] = INCGFX_U32("graphics/trainers/kanto/palettes/leader_brock.pal", ".gbapal.lz");
static const u32 gTrainerFrontPic_KantoLeaderErika[] = INCGFX_U32("graphics/trainers/kanto/front_pics/leader_erika_front_pic.png", ".4bpp.lz");
static const u32 gTrainerPalette_KantoLeaderErika[] = INCGFX_U32("graphics/trainers/kanto/palettes/leader_erika.pal", ".gbapal.lz");
static const u32 gTrainerFrontPic_KantoLeaderKoga[] = INCGFX_U32("graphics/trainers/kanto/front_pics/leader_koga_front_pic.png", ".4bpp.lz");
static const u32 gTrainerPalette_KantoLeaderKoga[] = INCGFX_U32("graphics/trainers/kanto/palettes/leader_koga.pal", ".gbapal.lz");
static const u32 gTrainerFrontPic_KantoLeaderLtSurge[] = INCGFX_U32("graphics/trainers/kanto/front_pics/leader_lt_surge_front_pic.png", ".4bpp.lz");
static const u32 gTrainerPalette_KantoLeaderLtSurge[] = INCGFX_U32("graphics/trainers/kanto/palettes/leader_lt_surge.pal", ".gbapal.lz");
static const u32 gTrainerFrontPic_KantoLeaderMisty[] = INCGFX_U32("graphics/trainers/kanto/front_pics/leader_misty_front_pic.png", ".4bpp.lz");
static const u32 gTrainerPalette_KantoLeaderMisty[] = INCGFX_U32("graphics/trainers/kanto/palettes/leader_misty.pal", ".gbapal.lz");
static const u32 gTrainerFrontPic_KantoLeaderSabrina[] = INCGFX_U32("graphics/trainers/kanto/front_pics/leader_sabrina_front_pic.png", ".4bpp.lz");
static const u32 gTrainerPalette_KantoLeaderSabrina[] = INCGFX_U32("graphics/trainers/kanto/palettes/leader_sabrina.pal", ".gbapal.lz");
static const u32 gTrainerFrontPic_KantoPainter[] = INCGFX_U32("graphics/trainers/kanto/front_pics/painter_front_pic.png", ".4bpp.lz");
static const u32 gTrainerPalette_KantoPainter[] = INCGFX_U32("graphics/trainers/kanto/palettes/painter.pal", ".gbapal.lz");
static const u32 gTrainerFrontPic_KantoPicnicker[] = INCGFX_U32("graphics/trainers/kanto/front_pics/picnicker_front_pic.png", ".4bpp.lz");
static const u32 gTrainerPalette_KantoPicnicker[] = INCGFX_U32("graphics/trainers/kanto/palettes/picnicker.pal", ".gbapal.lz");
static const u32 gTrainerFrontPic_KantoPokemonBreeder[] = INCGFX_U32("graphics/trainers/kanto/front_pics/pokemon_breeder_front_pic.png", ".4bpp.lz");
static const u32 gTrainerPalette_KantoPokemonBreeder[] = INCGFX_U32("graphics/trainers/kanto/palettes/pokemon_breeder.pal", ".gbapal.lz");
static const u32 gTrainerFrontPic_KantoPokemonRangerF[] = INCGFX_U32("graphics/trainers/kanto/front_pics/pokemon_ranger_f_front_pic.png", ".4bpp.lz");
static const u32 gTrainerPalette_KantoPokemonRangerF[] = INCGFX_U32("graphics/trainers/kanto/palettes/pokemon_ranger_f.pal", ".gbapal.lz");
static const u32 gTrainerFrontPic_KantoPokemonRangerM[] = INCGFX_U32("graphics/trainers/kanto/front_pics/pokemon_ranger_m_front_pic.png", ".4bpp.lz");
static const u32 gTrainerPalette_KantoPokemonRangerM[] = INCGFX_U32("graphics/trainers/kanto/palettes/pokemon_ranger_m.pal", ".gbapal.lz");
static const u32 gTrainerFrontPic_KantoPokeManiac[] = INCGFX_U32("graphics/trainers/kanto/front_pics/pokemaniac_front_pic.png", ".4bpp.lz");
static const u32 gTrainerPalette_KantoPokeManiac[] = INCGFX_U32("graphics/trainers/kanto/palettes/pokemaniac.pal", ".gbapal.lz");
static const u32 gTrainerFrontPic_KantoPsychicM[] = INCGFX_U32("graphics/trainers/kanto/front_pics/psychic_m_front_pic.png", ".4bpp.lz");
static const u32 gTrainerPalette_KantoPsychicM[] = INCGFX_U32("graphics/trainers/kanto/palettes/psychic_m.pal", ".gbapal.lz");
static const u32 gTrainerFrontPic_KantoPsychicF[] = INCGFX_U32("graphics/trainers/kanto/front_pics/psychic_f_front_pic.png", ".4bpp.lz");
static const u32 gTrainerPalette_KantoPsychicF[] = INCGFX_U32("graphics/trainers/kanto/palettes/psychic_f.pal", ".gbapal.lz");
static const u32 gTrainerFrontPic_KantoRocker[] = INCGFX_U32("graphics/trainers/kanto/front_pics/rocker_front_pic.png", ".4bpp.lz");
static const u32 gTrainerPalette_KantoRocker[] = INCGFX_U32("graphics/trainers/kanto/palettes/rocker.pal", ".gbapal.lz");
static const u32 gTrainerFrontPic_KantoRuinManiac[] = INCGFX_U32("graphics/trainers/kanto/front_pics/ruin_maniac_front_pic.png", ".4bpp.lz");
static const u32 gTrainerPalette_KantoRuinManiac[] = INCGFX_U32("graphics/trainers/kanto/palettes/ruin_maniac.pal", ".gbapal.lz");
static const u32 gTrainerFrontPic_KantoSailor[] = INCGFX_U32("graphics/trainers/kanto/front_pics/sailor_front_pic.png", ".4bpp.lz");
static const u32 gTrainerPalette_KantoSailor[] = INCGFX_U32("graphics/trainers/kanto/palettes/sailor.pal", ".gbapal.lz");
static const u32 gTrainerFrontPic_KantoScientist[] = INCGFX_U32("graphics/trainers/kanto/front_pics/scientist_front_pic.png", ".4bpp.lz");
static const u32 gTrainerPalette_KantoScientist[] = INCGFX_U32("graphics/trainers/kanto/palettes/scientist.pal", ".gbapal.lz");
static const u32 gTrainerFrontPic_KantoSisAndBro[] = INCGFX_U32("graphics/trainers/kanto/front_pics/sis_and_bro_front_pic.png", ".4bpp.lz");
static const u32 gTrainerPalette_KantoSisAndBro[] = INCGFX_U32("graphics/trainers/kanto/palettes/sis_and_bro.pal", ".gbapal.lz");
static const u32 gTrainerFrontPic_KantoSuperNerd[] = INCGFX_U32("graphics/trainers/kanto/front_pics/super_nerd_front_pic.png", ".4bpp.lz");
static const u32 gTrainerPalette_KantoSuperNerd[] = INCGFX_U32("graphics/trainers/kanto/palettes/super_nerd.pal", ".gbapal.lz");
static const u32 gTrainerFrontPic_KantoSwimmerF[] = INCGFX_U32("graphics/trainers/kanto/front_pics/swimmer_f_front_pic.png", ".4bpp.lz");
static const u32 gTrainerPalette_KantoSwimmerF[] = INCGFX_U32("graphics/trainers/kanto/palettes/swimmer_f.pal", ".gbapal.lz");
static const u32 gTrainerFrontPic_KantoSwimmerM[] = INCGFX_U32("graphics/trainers/kanto/front_pics/swimmer_m_front_pic.png", ".4bpp.lz");
static const u32 gTrainerPalette_KantoSwimmerM[] = INCGFX_U32("graphics/trainers/kanto/palettes/swimmer_m.pal", ".gbapal.lz");
static const u32 gTrainerFrontPic_KantoTamer[] = INCGFX_U32("graphics/trainers/kanto/front_pics/tamer_front_pic.png", ".4bpp.lz");
static const u32 gTrainerPalette_KantoTamer[] = INCGFX_U32("graphics/trainers/kanto/palettes/tamer.pal", ".gbapal.lz");
static const u32 gTrainerFrontPic_KantoRocketGruntF[] = INCGFX_U32("graphics/trainers/kanto/front_pics/rocket_grunt_f_front_pic.png", ".4bpp.lz");
static const u32 gTrainerPalette_KantoRocketGruntF[] = INCGFX_U32("graphics/trainers/kanto/palettes/rocket_grunt_f.pal", ".gbapal.lz");
static const u32 gTrainerFrontPic_KantoRocketGruntM[] = INCGFX_U32("graphics/trainers/kanto/front_pics/rocket_grunt_m_front_pic.png", ".4bpp.lz");
static const u32 gTrainerPalette_KantoRocketGruntM[] = INCGFX_U32("graphics/trainers/kanto/palettes/rocket_grunt_m.pal", ".gbapal.lz");
static const u32 gTrainerFrontPic_KantoTuberF[] = INCGFX_U32("graphics/trainers/kanto/front_pics/tuber_f_front_pic.png", ".4bpp.lz");
static const u32 gTrainerPalette_KantoTuberF[] = INCGFX_U32("graphics/trainers/kanto/palettes/tuber_f.pal", ".gbapal.lz");
static const u32 gTrainerFrontPic_KantoTwins[] = INCGFX_U32("graphics/trainers/kanto/front_pics/twins_front_pic.png", ".4bpp.lz");
static const u32 gTrainerPalette_KantoTwins[] = INCGFX_U32("graphics/trainers/kanto/palettes/twins.pal", ".gbapal.lz");
static const u32 gTrainerFrontPic_KantoYoungster[] = INCGFX_U32("graphics/trainers/kanto/front_pics/youngster_front_pic.png", ".4bpp.lz");
static const u32 gTrainerPalette_KantoYoungster[] = INCGFX_U32("graphics/trainers/kanto/palettes/youngster.pal", ".gbapal.lz");
static const u32 gTrainerFrontPic_KantoYoungCouple[] = INCGFX_U32("graphics/trainers/kanto/front_pics/young_couple_front_pic.png", ".4bpp.lz");
static const u32 gTrainerPalette_KantoYoungCouple[] = INCGFX_U32("graphics/trainers/kanto/palettes/young_couple.pal", ".gbapal.lz");

#define KANTO_TRAINER_FRONT_PIC_COORDS \
    [TRAINER_PIC_KANTO_AROMA_LADY] = {.size = 8, .y_offset = 1}, \
    [TRAINER_PIC_KANTO_BEAUTY] = {.size = 8, .y_offset = 1}, \
    [TRAINER_PIC_KANTO_BIKER] = {.size = 8, .y_offset = 1}, \
    [TRAINER_PIC_KANTO_BIRD_KEEPER] = {.size = 8, .y_offset = 1}, \
    [TRAINER_PIC_KANTO_BLACK_BELT] = {.size = 8, .y_offset = 1}, \
    [TRAINER_PIC_KANTO_LEADER_GIOVANNI] = {.size = 8, .y_offset = 1}, \
    [TRAINER_PIC_KANTO_BUG_CATCHER] = {.size = 8, .y_offset = 1}, \
    [TRAINER_PIC_KANTO_BURGLAR] = {.size = 8, .y_offset = 1}, \
    [TRAINER_PIC_KANTO_CAMPER] = {.size = 8, .y_offset = 1}, \
    [TRAINER_PIC_KANTO_CHANNELER] = {.size = 8, .y_offset = 1}, \
    [TRAINER_PIC_KANTO_COOLTRAINER_F] = {.size = 8, .y_offset = 1}, \
    [TRAINER_PIC_KANTO_COOLTRAINER_M] = {.size = 8, .y_offset = 1}, \
    [TRAINER_PIC_KANTO_COOL_COUPLE] = {.size = 8, .y_offset = 1}, \
    [TRAINER_PIC_KANTO_CRUSH_GIRL] = {.size = 8, .y_offset = 1}, \
    [TRAINER_PIC_KANTO_CRUSH_KIN] = {.size = 8, .y_offset = 1}, \
    [TRAINER_PIC_KANTO_CUE_BALL] = {.size = 8, .y_offset = 1}, \
    [TRAINER_PIC_KANTO_ENGINEER] = {.size = 8, .y_offset = 1}, \
    [TRAINER_PIC_KANTO_FISHERMAN] = {.size = 8, .y_offset = 1}, \
    [TRAINER_PIC_KANTO_GAMER] = {.size = 8, .y_offset = 1}, \
    [TRAINER_PIC_KANTO_GENTLEMAN] = {.size = 8, .y_offset = 1}, \
    [TRAINER_PIC_KANTO_HIKER] = {.size = 8, .y_offset = 1}, \
    [TRAINER_PIC_KANTO_JUGGLER] = {.size = 8, .y_offset = 1}, \
    [TRAINER_PIC_KANTO_LADY] = {.size = 8, .y_offset = 1}, \
    [TRAINER_PIC_KANTO_LASS] = {.size = 8, .y_offset = 1}, \
    [TRAINER_PIC_KANTO_LEADER_BLAINE] = {.size = 8, .y_offset = 1}, \
    [TRAINER_PIC_KANTO_LEADER_BROCK] = {.size = 8, .y_offset = 1}, \
    [TRAINER_PIC_KANTO_LEADER_ERIKA] = {.size = 8, .y_offset = 1}, \
    [TRAINER_PIC_KANTO_LEADER_KOGA] = {.size = 8, .y_offset = 1}, \
    [TRAINER_PIC_KANTO_LEADER_LT_SURGE] = {.size = 8, .y_offset = 1}, \
    [TRAINER_PIC_KANTO_LEADER_MISTY] = {.size = 8, .y_offset = 1}, \
    [TRAINER_PIC_KANTO_LEADER_SABRINA] = {.size = 8, .y_offset = 1}, \
    [TRAINER_PIC_KANTO_PAINTER] = {.size = 8, .y_offset = 1}, \
    [TRAINER_PIC_KANTO_PICNICKER] = {.size = 8, .y_offset = 1}, \
    [TRAINER_PIC_KANTO_POKEMON_BREEDER] = {.size = 8, .y_offset = 1}, \
    [TRAINER_PIC_KANTO_POKEMON_RANGER_F] = {.size = 8, .y_offset = 1}, \
    [TRAINER_PIC_KANTO_POKEMON_RANGER_M] = {.size = 8, .y_offset = 1}, \
    [TRAINER_PIC_KANTO_POKEMANIAC] = {.size = 8, .y_offset = 1}, \
    [TRAINER_PIC_KANTO_PSYCHIC_M] = {.size = 8, .y_offset = 1}, \
    [TRAINER_PIC_KANTO_PSYCHIC_F] = {.size = 8, .y_offset = 1}, \
    [TRAINER_PIC_KANTO_ROCKER] = {.size = 8, .y_offset = 1}, \
    [TRAINER_PIC_KANTO_RUIN_MANIAC] = {.size = 8, .y_offset = 1}, \
    [TRAINER_PIC_KANTO_SAILOR] = {.size = 8, .y_offset = 1}, \
    [TRAINER_PIC_KANTO_SCIENTIST] = {.size = 8, .y_offset = 1}, \
    [TRAINER_PIC_KANTO_SIS_AND_BRO] = {.size = 8, .y_offset = 1}, \
    [TRAINER_PIC_KANTO_SUPER_NERD] = {.size = 8, .y_offset = 1}, \
    [TRAINER_PIC_KANTO_SWIMMER_F] = {.size = 8, .y_offset = 1}, \
    [TRAINER_PIC_KANTO_SWIMMER_M] = {.size = 8, .y_offset = 1}, \
    [TRAINER_PIC_KANTO_TAMER] = {.size = 8, .y_offset = 1}, \
    [TRAINER_PIC_KANTO_ROCKET_GRUNT_F] = {.size = 8, .y_offset = 1}, \
    [TRAINER_PIC_KANTO_ROCKET_GRUNT_M] = {.size = 8, .y_offset = 1}, \
    [TRAINER_PIC_KANTO_TUBER_F] = {.size = 8, .y_offset = 1}, \
    [TRAINER_PIC_KANTO_TWINS] = {.size = 8, .y_offset = 1}, \
    [TRAINER_PIC_KANTO_YOUNGSTER] = {.size = 8, .y_offset = 1}, \
    [TRAINER_PIC_KANTO_YOUNG_COUPLE] = {.size = 8, .y_offset = 1},

#define KANTO_TRAINER_FRONT_PICS \
    [TRAINER_PIC_KANTO_AROMA_LADY] = {gTrainerFrontPic_KantoAromaLady, TRAINER_PIC_SIZE, TRAINER_PIC_KANTO_AROMA_LADY}, \
    [TRAINER_PIC_KANTO_BEAUTY] = {gTrainerFrontPic_KantoBeauty, TRAINER_PIC_SIZE, TRAINER_PIC_KANTO_BEAUTY}, \
    [TRAINER_PIC_KANTO_BIKER] = {gTrainerFrontPic_KantoBiker, TRAINER_PIC_SIZE, TRAINER_PIC_KANTO_BIKER}, \
    [TRAINER_PIC_KANTO_BIRD_KEEPER] = {gTrainerFrontPic_KantoBirdKeeper, TRAINER_PIC_SIZE, TRAINER_PIC_KANTO_BIRD_KEEPER}, \
    [TRAINER_PIC_KANTO_BLACK_BELT] = {gTrainerFrontPic_KantoBlackBelt, TRAINER_PIC_SIZE, TRAINER_PIC_KANTO_BLACK_BELT}, \
    [TRAINER_PIC_KANTO_LEADER_GIOVANNI] = {gTrainerFrontPic_KantoLeaderGiovanni, TRAINER_PIC_SIZE, TRAINER_PIC_KANTO_LEADER_GIOVANNI}, \
    [TRAINER_PIC_KANTO_BUG_CATCHER] = {gTrainerFrontPic_KantoBugCatcher, TRAINER_PIC_SIZE, TRAINER_PIC_KANTO_BUG_CATCHER}, \
    [TRAINER_PIC_KANTO_BURGLAR] = {gTrainerFrontPic_KantoBurglar, TRAINER_PIC_SIZE, TRAINER_PIC_KANTO_BURGLAR}, \
    [TRAINER_PIC_KANTO_CAMPER] = {gTrainerFrontPic_KantoCamper, TRAINER_PIC_SIZE, TRAINER_PIC_KANTO_CAMPER}, \
    [TRAINER_PIC_KANTO_CHANNELER] = {gTrainerFrontPic_KantoChanneler, TRAINER_PIC_SIZE, TRAINER_PIC_KANTO_CHANNELER}, \
    [TRAINER_PIC_KANTO_COOLTRAINER_F] = {gTrainerFrontPic_KantoCooltrainerF, TRAINER_PIC_SIZE, TRAINER_PIC_KANTO_COOLTRAINER_F}, \
    [TRAINER_PIC_KANTO_COOLTRAINER_M] = {gTrainerFrontPic_KantoCooltrainerM, TRAINER_PIC_SIZE, TRAINER_PIC_KANTO_COOLTRAINER_M}, \
    [TRAINER_PIC_KANTO_COOL_COUPLE] = {gTrainerFrontPic_KantoCoolCouple, TRAINER_PIC_SIZE, TRAINER_PIC_KANTO_COOL_COUPLE}, \
    [TRAINER_PIC_KANTO_CRUSH_GIRL] = {gTrainerFrontPic_KantoCrushGirl, TRAINER_PIC_SIZE, TRAINER_PIC_KANTO_CRUSH_GIRL}, \
    [TRAINER_PIC_KANTO_CRUSH_KIN] = {gTrainerFrontPic_KantoCrushKin, TRAINER_PIC_SIZE, TRAINER_PIC_KANTO_CRUSH_KIN}, \
    [TRAINER_PIC_KANTO_CUE_BALL] = {gTrainerFrontPic_KantoCueBall, TRAINER_PIC_SIZE, TRAINER_PIC_KANTO_CUE_BALL}, \
    [TRAINER_PIC_KANTO_ENGINEER] = {gTrainerFrontPic_KantoEngineer, TRAINER_PIC_SIZE, TRAINER_PIC_KANTO_ENGINEER}, \
    [TRAINER_PIC_KANTO_FISHERMAN] = {gTrainerFrontPic_KantoFisherman, TRAINER_PIC_SIZE, TRAINER_PIC_KANTO_FISHERMAN}, \
    [TRAINER_PIC_KANTO_GAMER] = {gTrainerFrontPic_KantoGamer, TRAINER_PIC_SIZE, TRAINER_PIC_KANTO_GAMER}, \
    [TRAINER_PIC_KANTO_GENTLEMAN] = {gTrainerFrontPic_KantoGentleman, TRAINER_PIC_SIZE, TRAINER_PIC_KANTO_GENTLEMAN}, \
    [TRAINER_PIC_KANTO_HIKER] = {gTrainerFrontPic_KantoHiker, TRAINER_PIC_SIZE, TRAINER_PIC_KANTO_HIKER}, \
    [TRAINER_PIC_KANTO_JUGGLER] = {gTrainerFrontPic_KantoJuggler, TRAINER_PIC_SIZE, TRAINER_PIC_KANTO_JUGGLER}, \
    [TRAINER_PIC_KANTO_LADY] = {gTrainerFrontPic_KantoLady, TRAINER_PIC_SIZE, TRAINER_PIC_KANTO_LADY}, \
    [TRAINER_PIC_KANTO_LASS] = {gTrainerFrontPic_KantoLass, TRAINER_PIC_SIZE, TRAINER_PIC_KANTO_LASS}, \
    [TRAINER_PIC_KANTO_LEADER_BLAINE] = {gTrainerFrontPic_KantoLeaderBlaine, TRAINER_PIC_SIZE, TRAINER_PIC_KANTO_LEADER_BLAINE}, \
    [TRAINER_PIC_KANTO_LEADER_BROCK] = {gTrainerFrontPic_KantoLeaderBrock, TRAINER_PIC_SIZE, TRAINER_PIC_KANTO_LEADER_BROCK}, \
    [TRAINER_PIC_KANTO_LEADER_ERIKA] = {gTrainerFrontPic_KantoLeaderErika, TRAINER_PIC_SIZE, TRAINER_PIC_KANTO_LEADER_ERIKA}, \
    [TRAINER_PIC_KANTO_LEADER_KOGA] = {gTrainerFrontPic_KantoLeaderKoga, TRAINER_PIC_SIZE, TRAINER_PIC_KANTO_LEADER_KOGA}, \
    [TRAINER_PIC_KANTO_LEADER_LT_SURGE] = {gTrainerFrontPic_KantoLeaderLtSurge, TRAINER_PIC_SIZE, TRAINER_PIC_KANTO_LEADER_LT_SURGE}, \
    [TRAINER_PIC_KANTO_LEADER_MISTY] = {gTrainerFrontPic_KantoLeaderMisty, TRAINER_PIC_SIZE, TRAINER_PIC_KANTO_LEADER_MISTY}, \
    [TRAINER_PIC_KANTO_LEADER_SABRINA] = {gTrainerFrontPic_KantoLeaderSabrina, TRAINER_PIC_SIZE, TRAINER_PIC_KANTO_LEADER_SABRINA}, \
    [TRAINER_PIC_KANTO_PAINTER] = {gTrainerFrontPic_KantoPainter, TRAINER_PIC_SIZE, TRAINER_PIC_KANTO_PAINTER}, \
    [TRAINER_PIC_KANTO_PICNICKER] = {gTrainerFrontPic_KantoPicnicker, TRAINER_PIC_SIZE, TRAINER_PIC_KANTO_PICNICKER}, \
    [TRAINER_PIC_KANTO_POKEMON_BREEDER] = {gTrainerFrontPic_KantoPokemonBreeder, TRAINER_PIC_SIZE, TRAINER_PIC_KANTO_POKEMON_BREEDER}, \
    [TRAINER_PIC_KANTO_POKEMON_RANGER_F] = {gTrainerFrontPic_KantoPokemonRangerF, TRAINER_PIC_SIZE, TRAINER_PIC_KANTO_POKEMON_RANGER_F}, \
    [TRAINER_PIC_KANTO_POKEMON_RANGER_M] = {gTrainerFrontPic_KantoPokemonRangerM, TRAINER_PIC_SIZE, TRAINER_PIC_KANTO_POKEMON_RANGER_M}, \
    [TRAINER_PIC_KANTO_POKEMANIAC] = {gTrainerFrontPic_KantoPokeManiac, TRAINER_PIC_SIZE, TRAINER_PIC_KANTO_POKEMANIAC}, \
    [TRAINER_PIC_KANTO_PSYCHIC_M] = {gTrainerFrontPic_KantoPsychicM, TRAINER_PIC_SIZE, TRAINER_PIC_KANTO_PSYCHIC_M}, \
    [TRAINER_PIC_KANTO_PSYCHIC_F] = {gTrainerFrontPic_KantoPsychicF, TRAINER_PIC_SIZE, TRAINER_PIC_KANTO_PSYCHIC_F}, \
    [TRAINER_PIC_KANTO_ROCKER] = {gTrainerFrontPic_KantoRocker, TRAINER_PIC_SIZE, TRAINER_PIC_KANTO_ROCKER}, \
    [TRAINER_PIC_KANTO_RUIN_MANIAC] = {gTrainerFrontPic_KantoRuinManiac, TRAINER_PIC_SIZE, TRAINER_PIC_KANTO_RUIN_MANIAC}, \
    [TRAINER_PIC_KANTO_SAILOR] = {gTrainerFrontPic_KantoSailor, TRAINER_PIC_SIZE, TRAINER_PIC_KANTO_SAILOR}, \
    [TRAINER_PIC_KANTO_SCIENTIST] = {gTrainerFrontPic_KantoScientist, TRAINER_PIC_SIZE, TRAINER_PIC_KANTO_SCIENTIST}, \
    [TRAINER_PIC_KANTO_SIS_AND_BRO] = {gTrainerFrontPic_KantoSisAndBro, TRAINER_PIC_SIZE, TRAINER_PIC_KANTO_SIS_AND_BRO}, \
    [TRAINER_PIC_KANTO_SUPER_NERD] = {gTrainerFrontPic_KantoSuperNerd, TRAINER_PIC_SIZE, TRAINER_PIC_KANTO_SUPER_NERD}, \
    [TRAINER_PIC_KANTO_SWIMMER_F] = {gTrainerFrontPic_KantoSwimmerF, TRAINER_PIC_SIZE, TRAINER_PIC_KANTO_SWIMMER_F}, \
    [TRAINER_PIC_KANTO_SWIMMER_M] = {gTrainerFrontPic_KantoSwimmerM, TRAINER_PIC_SIZE, TRAINER_PIC_KANTO_SWIMMER_M}, \
    [TRAINER_PIC_KANTO_TAMER] = {gTrainerFrontPic_KantoTamer, TRAINER_PIC_SIZE, TRAINER_PIC_KANTO_TAMER}, \
    [TRAINER_PIC_KANTO_ROCKET_GRUNT_F] = {gTrainerFrontPic_KantoRocketGruntF, TRAINER_PIC_SIZE, TRAINER_PIC_KANTO_ROCKET_GRUNT_F}, \
    [TRAINER_PIC_KANTO_ROCKET_GRUNT_M] = {gTrainerFrontPic_KantoRocketGruntM, TRAINER_PIC_SIZE, TRAINER_PIC_KANTO_ROCKET_GRUNT_M}, \
    [TRAINER_PIC_KANTO_TUBER_F] = {gTrainerFrontPic_KantoTuberF, TRAINER_PIC_SIZE, TRAINER_PIC_KANTO_TUBER_F}, \
    [TRAINER_PIC_KANTO_TWINS] = {gTrainerFrontPic_KantoTwins, TRAINER_PIC_SIZE, TRAINER_PIC_KANTO_TWINS}, \
    [TRAINER_PIC_KANTO_YOUNGSTER] = {gTrainerFrontPic_KantoYoungster, TRAINER_PIC_SIZE, TRAINER_PIC_KANTO_YOUNGSTER}, \
    [TRAINER_PIC_KANTO_YOUNG_COUPLE] = {gTrainerFrontPic_KantoYoungCouple, TRAINER_PIC_SIZE, TRAINER_PIC_KANTO_YOUNG_COUPLE},

#define KANTO_TRAINER_FRONT_PALETTES \
    [TRAINER_PIC_KANTO_AROMA_LADY] = {gTrainerPalette_KantoAromaLady, TRAINER_PIC_KANTO_AROMA_LADY}, \
    [TRAINER_PIC_KANTO_BEAUTY] = {gTrainerPalette_KantoBeauty, TRAINER_PIC_KANTO_BEAUTY}, \
    [TRAINER_PIC_KANTO_BIKER] = {gTrainerPalette_KantoBiker, TRAINER_PIC_KANTO_BIKER}, \
    [TRAINER_PIC_KANTO_BIRD_KEEPER] = {gTrainerPalette_KantoBirdKeeper, TRAINER_PIC_KANTO_BIRD_KEEPER}, \
    [TRAINER_PIC_KANTO_BLACK_BELT] = {gTrainerPalette_KantoBlackBelt, TRAINER_PIC_KANTO_BLACK_BELT}, \
    [TRAINER_PIC_KANTO_LEADER_GIOVANNI] = {gTrainerPalette_KantoLeaderGiovanni, TRAINER_PIC_KANTO_LEADER_GIOVANNI}, \
    [TRAINER_PIC_KANTO_BUG_CATCHER] = {gTrainerPalette_KantoBugCatcher, TRAINER_PIC_KANTO_BUG_CATCHER}, \
    [TRAINER_PIC_KANTO_BURGLAR] = {gTrainerPalette_KantoBurglar, TRAINER_PIC_KANTO_BURGLAR}, \
    [TRAINER_PIC_KANTO_CAMPER] = {gTrainerPalette_KantoCamper, TRAINER_PIC_KANTO_CAMPER}, \
    [TRAINER_PIC_KANTO_CHANNELER] = {gTrainerPalette_KantoChanneler, TRAINER_PIC_KANTO_CHANNELER}, \
    [TRAINER_PIC_KANTO_COOLTRAINER_F] = {gTrainerPalette_KantoCooltrainerF, TRAINER_PIC_KANTO_COOLTRAINER_F}, \
    [TRAINER_PIC_KANTO_COOLTRAINER_M] = {gTrainerPalette_KantoCooltrainerM, TRAINER_PIC_KANTO_COOLTRAINER_M}, \
    [TRAINER_PIC_KANTO_COOL_COUPLE] = {gTrainerPalette_KantoCoolCouple, TRAINER_PIC_KANTO_COOL_COUPLE}, \
    [TRAINER_PIC_KANTO_CRUSH_GIRL] = {gTrainerPalette_KantoCrushGirl, TRAINER_PIC_KANTO_CRUSH_GIRL}, \
    [TRAINER_PIC_KANTO_CRUSH_KIN] = {gTrainerPalette_KantoCrushKin, TRAINER_PIC_KANTO_CRUSH_KIN}, \
    [TRAINER_PIC_KANTO_CUE_BALL] = {gTrainerPalette_KantoCueBall, TRAINER_PIC_KANTO_CUE_BALL}, \
    [TRAINER_PIC_KANTO_ENGINEER] = {gTrainerPalette_KantoEngineer, TRAINER_PIC_KANTO_ENGINEER}, \
    [TRAINER_PIC_KANTO_FISHERMAN] = {gTrainerPalette_KantoFisherman, TRAINER_PIC_KANTO_FISHERMAN}, \
    [TRAINER_PIC_KANTO_GAMER] = {gTrainerPalette_KantoGamer, TRAINER_PIC_KANTO_GAMER}, \
    [TRAINER_PIC_KANTO_GENTLEMAN] = {gTrainerPalette_KantoGentleman, TRAINER_PIC_KANTO_GENTLEMAN}, \
    [TRAINER_PIC_KANTO_HIKER] = {gTrainerPalette_KantoHiker, TRAINER_PIC_KANTO_HIKER}, \
    [TRAINER_PIC_KANTO_JUGGLER] = {gTrainerPalette_KantoJuggler, TRAINER_PIC_KANTO_JUGGLER}, \
    [TRAINER_PIC_KANTO_LADY] = {gTrainerPalette_KantoLady, TRAINER_PIC_KANTO_LADY}, \
    [TRAINER_PIC_KANTO_LASS] = {gTrainerPalette_KantoLass, TRAINER_PIC_KANTO_LASS}, \
    [TRAINER_PIC_KANTO_LEADER_BLAINE] = {gTrainerPalette_KantoLeaderBlaine, TRAINER_PIC_KANTO_LEADER_BLAINE}, \
    [TRAINER_PIC_KANTO_LEADER_BROCK] = {gTrainerPalette_KantoLeaderBrock, TRAINER_PIC_KANTO_LEADER_BROCK}, \
    [TRAINER_PIC_KANTO_LEADER_ERIKA] = {gTrainerPalette_KantoLeaderErika, TRAINER_PIC_KANTO_LEADER_ERIKA}, \
    [TRAINER_PIC_KANTO_LEADER_KOGA] = {gTrainerPalette_KantoLeaderKoga, TRAINER_PIC_KANTO_LEADER_KOGA}, \
    [TRAINER_PIC_KANTO_LEADER_LT_SURGE] = {gTrainerPalette_KantoLeaderLtSurge, TRAINER_PIC_KANTO_LEADER_LT_SURGE}, \
    [TRAINER_PIC_KANTO_LEADER_MISTY] = {gTrainerPalette_KantoLeaderMisty, TRAINER_PIC_KANTO_LEADER_MISTY}, \
    [TRAINER_PIC_KANTO_LEADER_SABRINA] = {gTrainerPalette_KantoLeaderSabrina, TRAINER_PIC_KANTO_LEADER_SABRINA}, \
    [TRAINER_PIC_KANTO_PAINTER] = {gTrainerPalette_KantoPainter, TRAINER_PIC_KANTO_PAINTER}, \
    [TRAINER_PIC_KANTO_PICNICKER] = {gTrainerPalette_KantoPicnicker, TRAINER_PIC_KANTO_PICNICKER}, \
    [TRAINER_PIC_KANTO_POKEMON_BREEDER] = {gTrainerPalette_KantoPokemonBreeder, TRAINER_PIC_KANTO_POKEMON_BREEDER}, \
    [TRAINER_PIC_KANTO_POKEMON_RANGER_F] = {gTrainerPalette_KantoPokemonRangerF, TRAINER_PIC_KANTO_POKEMON_RANGER_F}, \
    [TRAINER_PIC_KANTO_POKEMON_RANGER_M] = {gTrainerPalette_KantoPokemonRangerM, TRAINER_PIC_KANTO_POKEMON_RANGER_M}, \
    [TRAINER_PIC_KANTO_POKEMANIAC] = {gTrainerPalette_KantoPokeManiac, TRAINER_PIC_KANTO_POKEMANIAC}, \
    [TRAINER_PIC_KANTO_PSYCHIC_M] = {gTrainerPalette_KantoPsychicM, TRAINER_PIC_KANTO_PSYCHIC_M}, \
    [TRAINER_PIC_KANTO_PSYCHIC_F] = {gTrainerPalette_KantoPsychicF, TRAINER_PIC_KANTO_PSYCHIC_F}, \
    [TRAINER_PIC_KANTO_ROCKER] = {gTrainerPalette_KantoRocker, TRAINER_PIC_KANTO_ROCKER}, \
    [TRAINER_PIC_KANTO_RUIN_MANIAC] = {gTrainerPalette_KantoRuinManiac, TRAINER_PIC_KANTO_RUIN_MANIAC}, \
    [TRAINER_PIC_KANTO_SAILOR] = {gTrainerPalette_KantoSailor, TRAINER_PIC_KANTO_SAILOR}, \
    [TRAINER_PIC_KANTO_SCIENTIST] = {gTrainerPalette_KantoScientist, TRAINER_PIC_KANTO_SCIENTIST}, \
    [TRAINER_PIC_KANTO_SIS_AND_BRO] = {gTrainerPalette_KantoSisAndBro, TRAINER_PIC_KANTO_SIS_AND_BRO}, \
    [TRAINER_PIC_KANTO_SUPER_NERD] = {gTrainerPalette_KantoSuperNerd, TRAINER_PIC_KANTO_SUPER_NERD}, \
    [TRAINER_PIC_KANTO_SWIMMER_F] = {gTrainerPalette_KantoSwimmerF, TRAINER_PIC_KANTO_SWIMMER_F}, \
    [TRAINER_PIC_KANTO_SWIMMER_M] = {gTrainerPalette_KantoSwimmerM, TRAINER_PIC_KANTO_SWIMMER_M}, \
    [TRAINER_PIC_KANTO_TAMER] = {gTrainerPalette_KantoTamer, TRAINER_PIC_KANTO_TAMER}, \
    [TRAINER_PIC_KANTO_ROCKET_GRUNT_F] = {gTrainerPalette_KantoRocketGruntF, TRAINER_PIC_KANTO_ROCKET_GRUNT_F}, \
    [TRAINER_PIC_KANTO_ROCKET_GRUNT_M] = {gTrainerPalette_KantoRocketGruntM, TRAINER_PIC_KANTO_ROCKET_GRUNT_M}, \
    [TRAINER_PIC_KANTO_TUBER_F] = {gTrainerPalette_KantoTuberF, TRAINER_PIC_KANTO_TUBER_F}, \
    [TRAINER_PIC_KANTO_TWINS] = {gTrainerPalette_KantoTwins, TRAINER_PIC_KANTO_TWINS}, \
    [TRAINER_PIC_KANTO_YOUNGSTER] = {gTrainerPalette_KantoYoungster, TRAINER_PIC_KANTO_YOUNGSTER}, \
    [TRAINER_PIC_KANTO_YOUNG_COUPLE] = {gTrainerPalette_KantoYoungCouple, TRAINER_PIC_KANTO_YOUNG_COUPLE},

#define KANTO_TRAINER_FRONT_ANIMS \
    [TRAINER_PIC_KANTO_AROMA_LADY] = sAnims_Hiker, \
    [TRAINER_PIC_KANTO_BEAUTY] = sAnims_Hiker, \
    [TRAINER_PIC_KANTO_BIKER] = sAnims_Hiker, \
    [TRAINER_PIC_KANTO_BIRD_KEEPER] = sAnims_Hiker, \
    [TRAINER_PIC_KANTO_BLACK_BELT] = sAnims_Hiker, \
    [TRAINER_PIC_KANTO_LEADER_GIOVANNI] = sAnims_Hiker, \
    [TRAINER_PIC_KANTO_BUG_CATCHER] = sAnims_Hiker, \
    [TRAINER_PIC_KANTO_BURGLAR] = sAnims_Hiker, \
    [TRAINER_PIC_KANTO_CAMPER] = sAnims_Hiker, \
    [TRAINER_PIC_KANTO_CHANNELER] = sAnims_Hiker, \
    [TRAINER_PIC_KANTO_COOLTRAINER_F] = sAnims_Hiker, \
    [TRAINER_PIC_KANTO_COOLTRAINER_M] = sAnims_Hiker, \
    [TRAINER_PIC_KANTO_COOL_COUPLE] = sAnims_Hiker, \
    [TRAINER_PIC_KANTO_CRUSH_GIRL] = sAnims_Hiker, \
    [TRAINER_PIC_KANTO_CRUSH_KIN] = sAnims_Hiker, \
    [TRAINER_PIC_KANTO_CUE_BALL] = sAnims_Hiker, \
    [TRAINER_PIC_KANTO_ENGINEER] = sAnims_Hiker, \
    [TRAINER_PIC_KANTO_FISHERMAN] = sAnims_Hiker, \
    [TRAINER_PIC_KANTO_GAMER] = sAnims_Hiker, \
    [TRAINER_PIC_KANTO_GENTLEMAN] = sAnims_Hiker, \
    [TRAINER_PIC_KANTO_HIKER] = sAnims_Hiker, \
    [TRAINER_PIC_KANTO_JUGGLER] = sAnims_Hiker, \
    [TRAINER_PIC_KANTO_LADY] = sAnims_Hiker, \
    [TRAINER_PIC_KANTO_LASS] = sAnims_Hiker, \
    [TRAINER_PIC_KANTO_LEADER_BLAINE] = sAnims_Hiker, \
    [TRAINER_PIC_KANTO_LEADER_BROCK] = sAnims_Hiker, \
    [TRAINER_PIC_KANTO_LEADER_ERIKA] = sAnims_Hiker, \
    [TRAINER_PIC_KANTO_LEADER_KOGA] = sAnims_Hiker, \
    [TRAINER_PIC_KANTO_LEADER_LT_SURGE] = sAnims_Hiker, \
    [TRAINER_PIC_KANTO_LEADER_MISTY] = sAnims_Hiker, \
    [TRAINER_PIC_KANTO_LEADER_SABRINA] = sAnims_Hiker, \
    [TRAINER_PIC_KANTO_PAINTER] = sAnims_Hiker, \
    [TRAINER_PIC_KANTO_PICNICKER] = sAnims_Hiker, \
    [TRAINER_PIC_KANTO_POKEMON_BREEDER] = sAnims_Hiker, \
    [TRAINER_PIC_KANTO_POKEMON_RANGER_F] = sAnims_Hiker, \
    [TRAINER_PIC_KANTO_POKEMON_RANGER_M] = sAnims_Hiker, \
    [TRAINER_PIC_KANTO_POKEMANIAC] = sAnims_Hiker, \
    [TRAINER_PIC_KANTO_PSYCHIC_M] = sAnims_Hiker, \
    [TRAINER_PIC_KANTO_PSYCHIC_F] = sAnims_Hiker, \
    [TRAINER_PIC_KANTO_ROCKER] = sAnims_Hiker, \
    [TRAINER_PIC_KANTO_RUIN_MANIAC] = sAnims_Hiker, \
    [TRAINER_PIC_KANTO_SAILOR] = sAnims_Hiker, \
    [TRAINER_PIC_KANTO_SCIENTIST] = sAnims_Hiker, \
    [TRAINER_PIC_KANTO_SIS_AND_BRO] = sAnims_Hiker, \
    [TRAINER_PIC_KANTO_SUPER_NERD] = sAnims_Hiker, \
    [TRAINER_PIC_KANTO_SWIMMER_F] = sAnims_Hiker, \
    [TRAINER_PIC_KANTO_SWIMMER_M] = sAnims_Hiker, \
    [TRAINER_PIC_KANTO_TAMER] = sAnims_Hiker, \
    [TRAINER_PIC_KANTO_ROCKET_GRUNT_F] = sAnims_Hiker, \
    [TRAINER_PIC_KANTO_ROCKET_GRUNT_M] = sAnims_Hiker, \
    [TRAINER_PIC_KANTO_TUBER_F] = sAnims_Hiker, \
    [TRAINER_PIC_KANTO_TWINS] = sAnims_Hiker, \
    [TRAINER_PIC_KANTO_YOUNGSTER] = sAnims_Hiker, \
    [TRAINER_PIC_KANTO_YOUNG_COUPLE] = sAnims_Hiker,
