// Generated by tools/kanto_port/port_npcs.py from pokefirered. Do not edit by hand.
#ifndef GUARD_CONSTANTS_EVENT_OBJECTS_KANTO_H
#define GUARD_CONSTANTS_EVENT_OBJECTS_KANTO_H

// FRLG object event graphics, used by the Kanto maps. They come after OBJ_EVENT_GFX_VAR_F.
#define OBJ_EVENT_GFX_KANTO_START 256

#define OBJ_EVENT_GFX_KANTO_AGATHA                       256
#define OBJ_EVENT_GFX_KANTO_ARTICUNO                     257
#define OBJ_EVENT_GFX_KANTO_BALDING_MAN                  258
#define OBJ_EVENT_GFX_KANTO_BEAUTY                       259
#define OBJ_EVENT_GFX_KANTO_BIKER                        260
#define OBJ_EVENT_GFX_KANTO_BILL                         261
#define OBJ_EVENT_GFX_KANTO_BLACK_BELT                   262
#define OBJ_EVENT_GFX_KANTO_BLAINE                       263
#define OBJ_EVENT_GFX_KANTO_BLUE                         264
#define OBJ_EVENT_GFX_KANTO_BOY                          265
#define OBJ_EVENT_GFX_KANTO_BROCK                        266
#define OBJ_EVENT_GFX_KANTO_BRUNO                        267
#define OBJ_EVENT_GFX_KANTO_BUG_CATCHER                  268
#define OBJ_EVENT_GFX_KANTO_CABLE_CLUB_RECEPTIONIST      269
#define OBJ_EVENT_GFX_KANTO_CAMPER                       270
#define OBJ_EVENT_GFX_KANTO_CAPTAIN                      271
#define OBJ_EVENT_GFX_KANTO_CELIO                        272
#define OBJ_EVENT_GFX_KANTO_CHANNELER                    273
#define OBJ_EVENT_GFX_KANTO_CHANSEY                      274
#define OBJ_EVENT_GFX_KANTO_CHEF                         275
#define OBJ_EVENT_GFX_KANTO_CLEFAIRY                     276
#define OBJ_EVENT_GFX_KANTO_CLERK                        277
#define OBJ_EVENT_GFX_KANTO_CLIPBOARD                    278
#define OBJ_EVENT_GFX_KANTO_COOLTRAINER_F                279
#define OBJ_EVENT_GFX_KANTO_COOLTRAINER_M                280
#define OBJ_EVENT_GFX_KANTO_CRUSH_GIRL                   281
#define OBJ_EVENT_GFX_KANTO_CUBONE                       282
#define OBJ_EVENT_GFX_KANTO_CUT_TREE                     283
#define OBJ_EVENT_GFX_KANTO_DAISY                        284
#define OBJ_EVENT_GFX_KANTO_DEOXYS_N                     285
#define OBJ_EVENT_GFX_KANTO_DODUO                        286
#define OBJ_EVENT_GFX_KANTO_ERIKA                        287
#define OBJ_EVENT_GFX_KANTO_FAT_MAN                      288
#define OBJ_EVENT_GFX_KANTO_FEAROW                       289
#define OBJ_EVENT_GFX_KANTO_FISHER                       290
#define OBJ_EVENT_GFX_KANTO_FOSSIL                       291
#define OBJ_EVENT_GFX_KANTO_GBA_KID                      292
#define OBJ_EVENT_GFX_KANTO_GENTLEMAN                    293
#define OBJ_EVENT_GFX_KANTO_GIOVANNI                     294
#define OBJ_EVENT_GFX_KANTO_GYM_GUY                      295
#define OBJ_EVENT_GFX_KANTO_HIKER                        296
#define OBJ_EVENT_GFX_KANTO_HO_OH                        297
#define OBJ_EVENT_GFX_KANTO_ITEM_BALL                    298
#define OBJ_EVENT_GFX_KANTO_JIGGLYPUFF                   299
#define OBJ_EVENT_GFX_KANTO_KABUTO                       300
#define OBJ_EVENT_GFX_KANTO_KANGASKHAN                   301
#define OBJ_EVENT_GFX_KANTO_KOGA                         302
#define OBJ_EVENT_GFX_KANTO_LANCE                        303
#define OBJ_EVENT_GFX_KANTO_LAPRAS                       304
#define OBJ_EVENT_GFX_KANTO_LAPRAS_DOLL                  305
#define OBJ_EVENT_GFX_KANTO_LASS                         306
#define OBJ_EVENT_GFX_KANTO_LITTLE_BOY                   307
#define OBJ_EVENT_GFX_KANTO_LITTLE_GIRL                  308
#define OBJ_EVENT_GFX_KANTO_LORELEI                      309
#define OBJ_EVENT_GFX_KANTO_LT_SURGE                     310
#define OBJ_EVENT_GFX_KANTO_LUGIA                        311
#define OBJ_EVENT_GFX_KANTO_MACHOKE                      312
#define OBJ_EVENT_GFX_KANTO_MACHOP                       313
#define OBJ_EVENT_GFX_KANTO_MAN                          314
#define OBJ_EVENT_GFX_KANTO_MEOWTH                       315
#define OBJ_EVENT_GFX_KANTO_METEORITE                    316
#define OBJ_EVENT_GFX_KANTO_MEWTWO                       317
#define OBJ_EVENT_GFX_KANTO_MG_DELIVERYMAN               318
#define OBJ_EVENT_GFX_KANTO_MISTY                        319
#define OBJ_EVENT_GFX_KANTO_MOLTRES                      320
#define OBJ_EVENT_GFX_KANTO_MOM                          321
#define OBJ_EVENT_GFX_KANTO_MR_FUJI                      322
#define OBJ_EVENT_GFX_KANTO_NIDORAN_F                    323
#define OBJ_EVENT_GFX_KANTO_NIDORAN_M                    324
#define OBJ_EVENT_GFX_KANTO_NIDORINO                     325
#define OBJ_EVENT_GFX_KANTO_NURSE                        326
#define OBJ_EVENT_GFX_KANTO_OLD_AMBER                    327
#define OBJ_EVENT_GFX_KANTO_OLD_MAN_1                    328
#define OBJ_EVENT_GFX_KANTO_OLD_MAN_2                    329
#define OBJ_EVENT_GFX_KANTO_OLD_MAN_LYING_DOWN           330
#define OBJ_EVENT_GFX_KANTO_OLD_WOMAN                    331
#define OBJ_EVENT_GFX_KANTO_OMANYTE                      332
#define OBJ_EVENT_GFX_KANTO_PICNICKER                    333
#define OBJ_EVENT_GFX_KANTO_PIDGEOT                      334
#define OBJ_EVENT_GFX_KANTO_PIDGEY                       335
#define OBJ_EVENT_GFX_KANTO_PIKACHU                      336
#define OBJ_EVENT_GFX_KANTO_POKEDEX                      337
#define OBJ_EVENT_GFX_KANTO_POKE_MANIAC                  338
#define OBJ_EVENT_GFX_KANTO_POLICEMAN                    339
#define OBJ_EVENT_GFX_KANTO_POLIWRATH                    340
#define OBJ_EVENT_GFX_KANTO_PROF_OAK                     341
#define OBJ_EVENT_GFX_KANTO_PSYDUCK                      342
#define OBJ_EVENT_GFX_KANTO_PUSHABLE_BOULDER             343
#define OBJ_EVENT_GFX_KANTO_ROCKER                       344
#define OBJ_EVENT_GFX_KANTO_ROCKET_F                     345
#define OBJ_EVENT_GFX_KANTO_ROCKET_M                     346
#define OBJ_EVENT_GFX_KANTO_ROCK_SMASH_ROCK              347
#define OBJ_EVENT_GFX_KANTO_RUBY                         348
#define OBJ_EVENT_GFX_KANTO_SABRINA                      349
#define OBJ_EVENT_GFX_KANTO_SAILOR                       350
#define OBJ_EVENT_GFX_KANTO_SAPPHIRE                     351
#define OBJ_EVENT_GFX_KANTO_SCIENTIST                    352
#define OBJ_EVENT_GFX_KANTO_SEAGALLOP                    353
#define OBJ_EVENT_GFX_KANTO_SEEL                         354
#define OBJ_EVENT_GFX_KANTO_SLOWBRO                      355
#define OBJ_EVENT_GFX_KANTO_SLOWPOKE                     356
#define OBJ_EVENT_GFX_KANTO_SNORLAX                      357
#define OBJ_EVENT_GFX_KANTO_SPEAROW                      358
#define OBJ_EVENT_GFX_KANTO_SS_ANNE                      359
#define OBJ_EVENT_GFX_KANTO_SWIMMER_F_LAND               360
#define OBJ_EVENT_GFX_KANTO_SWIMMER_F_WATER              361
#define OBJ_EVENT_GFX_KANTO_SWIMMER_M_LAND               362
#define OBJ_EVENT_GFX_KANTO_SWIMMER_M_WATER              363
#define OBJ_EVENT_GFX_KANTO_TOWN_MAP                     364
#define OBJ_EVENT_GFX_KANTO_TRAINER_TOWER_DUDE           365
#define OBJ_EVENT_GFX_KANTO_TUBER_F                      366
#define OBJ_EVENT_GFX_KANTO_TUBER_M_WATER                367
#define OBJ_EVENT_GFX_KANTO_UNION_ROOM_RECEPTIONIST      368
#define OBJ_EVENT_GFX_KANTO_VOLTORB                      369
#define OBJ_EVENT_GFX_KANTO_WIGGLYTUFF                   370
#define OBJ_EVENT_GFX_KANTO_WOMAN_1                      371
#define OBJ_EVENT_GFX_KANTO_WOMAN_2                      372
#define OBJ_EVENT_GFX_KANTO_WOMAN_3                      373
#define OBJ_EVENT_GFX_KANTO_WORKER_F                     374
#define OBJ_EVENT_GFX_KANTO_WORKER_M                     375
#define OBJ_EVENT_GFX_KANTO_YOUNGSTER                    376
#define OBJ_EVENT_GFX_KANTO_ZAPDOS                       377

#define NUM_KANTO_OBJ_EVENT_GFX 122

// Added for the Mega Evolution tournament (not generated): the champions of other regions.
// See tools/mega_island/champions/overworld.py.
#define OBJ_EVENT_GFX_CHAMPION_START (OBJ_EVENT_GFX_KANTO_START + NUM_KANTO_OBJ_EVENT_GFX)
#define OBJ_EVENT_GFX_CHAMPION_CYNTHIA    (OBJ_EVENT_GFX_CHAMPION_START + 0)
#define OBJ_EVENT_GFX_CHAMPION_ALDER      (OBJ_EVENT_GFX_CHAMPION_START + 1)
#define OBJ_EVENT_GFX_CHAMPION_DIANTHA    (OBJ_EVENT_GFX_CHAMPION_START + 2)
#define OBJ_EVENT_GFX_CHAMPION_LEON       (OBJ_EVENT_GFX_CHAMPION_START + 3)
#define OBJ_EVENT_GFX_ALAIN            (OBJ_EVENT_GFX_CHAMPION_START + 4)
#define NUM_CHAMPION_OBJ_EVENT_GFX 5

#endif // GUARD_CONSTANTS_EVENT_OBJECTS_KANTO_H
