// Generated by tools/kanto_port/port_trainers.py from pokefirered. Do not edit by hand.
#ifndef GUARD_CONSTANTS_TRAINERS_KANTO_H
#define GUARD_CONSTANTS_TRAINERS_KANTO_H

// FRLG trainer classes Emerald doesn't have
#define TRAINER_CLASS_BIKER                0x42
#define TRAINER_CLASS_BOSS                 0x43
#define TRAINER_CLASS_BURGLAR              0x44
#define TRAINER_CLASS_CHANNELER            0x45
#define TRAINER_CLASS_COOL_COUPLE          0x46
#define TRAINER_CLASS_CRUSH_GIRL           0x47
#define TRAINER_CLASS_CRUSH_KIN            0x48
#define TRAINER_CLASS_CUE_BALL             0x49
#define TRAINER_CLASS_ENGINEER             0x4a
#define TRAINER_CLASS_GAMER                0x4b
#define TRAINER_CLASS_JUGGLER              0x4c
#define TRAINER_CLASS_PAINTER              0x4d
#define TRAINER_CLASS_RIVAL_EARLY          0x4e
#define TRAINER_CLASS_RIVAL_LATE           0x4f
#define TRAINER_CLASS_ROCKER               0x50
#define TRAINER_CLASS_SCIENTIST            0x51
#define TRAINER_CLASS_SUPER_NERD           0x52
#define TRAINER_CLASS_TAMER                0x53
#define TRAINER_CLASS_TEAM_ROCKET          0x54
#define TRAINER_CLASS_TUBER                0x55

// FRLG trainer front pics
#define TRAINER_PIC_KANTO_AROMA_LADY                 93
#define TRAINER_PIC_KANTO_BEAUTY                     94
#define TRAINER_PIC_KANTO_BIKER                      95
#define TRAINER_PIC_KANTO_BIRD_KEEPER                96
#define TRAINER_PIC_KANTO_BLACK_BELT                 97
#define TRAINER_PIC_KANTO_LEADER_GIOVANNI            98
#define TRAINER_PIC_KANTO_BUG_CATCHER                99
#define TRAINER_PIC_KANTO_BURGLAR                    100
#define TRAINER_PIC_KANTO_CAMPER                     101
#define TRAINER_PIC_KANTO_CHAMPION_RIVAL             102
#define TRAINER_PIC_KANTO_CHANNELER                  103
#define TRAINER_PIC_KANTO_COOLTRAINER_F              104
#define TRAINER_PIC_KANTO_COOLTRAINER_M              105
#define TRAINER_PIC_KANTO_COOL_COUPLE                106
#define TRAINER_PIC_KANTO_CRUSH_GIRL                 107
#define TRAINER_PIC_KANTO_CRUSH_KIN                  108
#define TRAINER_PIC_KANTO_CUE_BALL                   109
#define TRAINER_PIC_KANTO_ELITE_FOUR_AGATHA          110
#define TRAINER_PIC_KANTO_ELITE_FOUR_BRUNO           111
#define TRAINER_PIC_KANTO_ELITE_FOUR_LANCE           112
#define TRAINER_PIC_KANTO_ELITE_FOUR_LORELEI         113
#define TRAINER_PIC_KANTO_ENGINEER                   114
#define TRAINER_PIC_KANTO_FISHERMAN                  115
#define TRAINER_PIC_KANTO_GAMER                      116
#define TRAINER_PIC_KANTO_GENTLEMAN                  117
#define TRAINER_PIC_KANTO_HIKER                      118
#define TRAINER_PIC_KANTO_JUGGLER                    119
#define TRAINER_PIC_KANTO_LADY                       120
#define TRAINER_PIC_KANTO_LASS                       121
#define TRAINER_PIC_KANTO_LEADER_BLAINE              122
#define TRAINER_PIC_KANTO_LEADER_BROCK               123
#define TRAINER_PIC_KANTO_LEADER_ERIKA               124
#define TRAINER_PIC_KANTO_LEADER_KOGA                125
#define TRAINER_PIC_KANTO_LEADER_LT_SURGE            126
#define TRAINER_PIC_KANTO_LEADER_MISTY               127
#define TRAINER_PIC_KANTO_LEADER_SABRINA             128
#define TRAINER_PIC_KANTO_PAINTER                    129
#define TRAINER_PIC_KANTO_PICNICKER                  130
#define TRAINER_PIC_KANTO_POKEMON_BREEDER            131
#define TRAINER_PIC_KANTO_POKEMON_RANGER_F           132
#define TRAINER_PIC_KANTO_POKEMON_RANGER_M           133
#define TRAINER_PIC_KANTO_POKEMANIAC                 134
#define TRAINER_PIC_KANTO_PSYCHIC_M                  135
#define TRAINER_PIC_KANTO_PSYCHIC_F                  136
#define TRAINER_PIC_KANTO_RIVAL_EARLY                137
#define TRAINER_PIC_KANTO_RIVAL_LATE                 138
#define TRAINER_PIC_KANTO_ROCKER                     139
#define TRAINER_PIC_KANTO_RUIN_MANIAC                140
#define TRAINER_PIC_KANTO_SAILOR                     141
#define TRAINER_PIC_KANTO_SCIENTIST                  142
#define TRAINER_PIC_KANTO_SIS_AND_BRO                143
#define TRAINER_PIC_KANTO_SUPER_NERD                 144
#define TRAINER_PIC_KANTO_SWIMMER_F                  145
#define TRAINER_PIC_KANTO_SWIMMER_M                  146
#define TRAINER_PIC_KANTO_TAMER                      147
#define TRAINER_PIC_KANTO_ROCKET_GRUNT_F             148
#define TRAINER_PIC_KANTO_ROCKET_GRUNT_M             149
#define TRAINER_PIC_KANTO_TUBER_F                    150
#define TRAINER_PIC_KANTO_TWINS                      151
#define TRAINER_PIC_KANTO_YOUNGSTER                  152
#define TRAINER_PIC_KANTO_YOUNG_COUPLE               153
// Added for the Mega Evolution tournament (not generated): the champions of other regions
#define TRAINER_PIC_CHAMPION_CYNTHIA                 154
#define TRAINER_PIC_CHAMPION_ALDER                   155
#define TRAINER_PIC_CHAMPION_DIANTHA                 156
#define TRAINER_PIC_CHAMPION_LEON                    157
#define TRAINER_PIC_KANTO_END 158

// Entries for gTrainerClassNames and gTrainerMoneyTable
#define KANTO_TRAINER_CLASS_NAMES \
    [TRAINER_CLASS_BIKER] = _("BIKER"), \
    [TRAINER_CLASS_BOSS] = _("BOSS"), \
    [TRAINER_CLASS_BURGLAR] = _("BURGLAR"), \
    [TRAINER_CLASS_CHANNELER] = _("CHANNELER"), \
    [TRAINER_CLASS_COOL_COUPLE] = _("COOL COUPLE"), \
    [TRAINER_CLASS_CRUSH_GIRL] = _("CRUSH GIRL"), \
    [TRAINER_CLASS_CRUSH_KIN] = _("CRUSH KIN"), \
    [TRAINER_CLASS_CUE_BALL] = _("CUE BALL"), \
    [TRAINER_CLASS_ENGINEER] = _("ENGINEER"), \
    [TRAINER_CLASS_GAMER] = _("GAMER"), \
    [TRAINER_CLASS_JUGGLER] = _("JUGGLER"), \
    [TRAINER_CLASS_PAINTER] = _("PAINTER"), \
    [TRAINER_CLASS_RIVAL_EARLY] = _("RIVAL"), \
    [TRAINER_CLASS_RIVAL_LATE] = _("RIVAL"), \
    [TRAINER_CLASS_ROCKER] = _("ROCKER"), \
    [TRAINER_CLASS_SCIENTIST] = _("SCIENTIST"), \
    [TRAINER_CLASS_SUPER_NERD] = _("SUPER NERD"), \
    [TRAINER_CLASS_TAMER] = _("TAMER"), \
    [TRAINER_CLASS_TEAM_ROCKET] = _("TEAM ROCKET"), \
    [TRAINER_CLASS_TUBER] = _("TUBER"),

#define KANTO_TRAINER_MONEY \
    {TRAINER_CLASS_BIKER, 5}, \
    {TRAINER_CLASS_BOSS, 25}, \
    {TRAINER_CLASS_BURGLAR, 22}, \
    {TRAINER_CLASS_CHANNELER, 8}, \
    {TRAINER_CLASS_COOL_COUPLE, 6}, \
    {TRAINER_CLASS_CRUSH_GIRL, 6}, \
    {TRAINER_CLASS_CRUSH_KIN, 6}, \
    {TRAINER_CLASS_CUE_BALL, 6}, \
    {TRAINER_CLASS_ENGINEER, 12}, \
    {TRAINER_CLASS_GAMER, 18}, \
    {TRAINER_CLASS_JUGGLER, 10}, \
    {TRAINER_CLASS_PAINTER, 4}, \
    {TRAINER_CLASS_RIVAL_EARLY, 4}, \
    {TRAINER_CLASS_RIVAL_LATE, 9}, \
    {TRAINER_CLASS_ROCKER, 6}, \
    {TRAINER_CLASS_SCIENTIST, 12}, \
    {TRAINER_CLASS_SUPER_NERD, 6}, \
    {TRAINER_CLASS_TAMER, 10}, \
    {TRAINER_CLASS_TEAM_ROCKET, 8}, \
    {TRAINER_CLASS_TUBER, 1},

#endif // GUARD_CONSTANTS_TRAINERS_KANTO_H
