MegaIsland_Castle_Room2_MapScripts::
	.byte 0

MegaIsland_Castle_Room2_EventScript_Lance::
	msgbox MegaIsland_Castle_Room2_Text_Lance, MSGBOX_NPC
	end

MegaIsland_Castle_Room2_Text_Lance:
	.string "LANCE: {PLAYER}. So the new\n"
	.string "CHAMPION is here as well.\p"
	.string "MR. M.'s letter came with a stone\n"
	.string "for my GYARADOS.\p"
	.string "I have trained dragons all my life,\n"
	.string "yet I never knew they could change\l"
	.string "like this.\p"
	.string "I intend to find out what this power\n"
	.string "really is. Don't hold back.$"
