// Generated by tools/kanto_port/port_kanto.py from pokefirered. Do not edit by hand.

const u16 gMetatiles_KantoGeneral[] = INCBIN_U16("data/tilesets/primary/kanto_general/metatiles.bin");
const u16 gMetatileAttributes_KantoGeneral[] = INCBIN_U16("data/tilesets/primary/kanto_general/metatile_attributes.bin");

const u16 gMetatiles_KantoPalletTown[] = INCBIN_U16("data/tilesets/secondary/kanto_pallet_town/metatiles.bin");
const u16 gMetatileAttributes_KantoPalletTown[] = INCBIN_U16("data/tilesets/secondary/kanto_pallet_town/metatile_attributes.bin");

const u16 gMetatiles_KantoViridianCity[] = INCBIN_U16("data/tilesets/secondary/kanto_viridian_city/metatiles.bin");
const u16 gMetatileAttributes_KantoViridianCity[] = INCBIN_U16("data/tilesets/secondary/kanto_viridian_city/metatile_attributes.bin");

const u16 gMetatiles_KantoPewterCity[] = INCBIN_U16("data/tilesets/secondary/kanto_pewter_city/metatiles.bin");
const u16 gMetatileAttributes_KantoPewterCity[] = INCBIN_U16("data/tilesets/secondary/kanto_pewter_city/metatile_attributes.bin");

const u16 gMetatiles_KantoCeruleanCity[] = INCBIN_U16("data/tilesets/secondary/kanto_cerulean_city/metatiles.bin");
const u16 gMetatileAttributes_KantoCeruleanCity[] = INCBIN_U16("data/tilesets/secondary/kanto_cerulean_city/metatile_attributes.bin");

const u16 gMetatiles_KantoLavenderTown[] = INCBIN_U16("data/tilesets/secondary/kanto_lavender_town/metatiles.bin");
const u16 gMetatileAttributes_KantoLavenderTown[] = INCBIN_U16("data/tilesets/secondary/kanto_lavender_town/metatile_attributes.bin");

const u16 gMetatiles_KantoVermilionCity[] = INCBIN_U16("data/tilesets/secondary/kanto_vermilion_city/metatiles.bin");
const u16 gMetatileAttributes_KantoVermilionCity[] = INCBIN_U16("data/tilesets/secondary/kanto_vermilion_city/metatile_attributes.bin");

const u16 gMetatiles_KantoCeladonCity[] = INCBIN_U16("data/tilesets/secondary/kanto_celadon_city/metatiles.bin");
const u16 gMetatileAttributes_KantoCeladonCity[] = INCBIN_U16("data/tilesets/secondary/kanto_celadon_city/metatile_attributes.bin");

const u16 gMetatiles_KantoFuchsiaCity[] = INCBIN_U16("data/tilesets/secondary/kanto_fuchsia_city/metatiles.bin");
const u16 gMetatileAttributes_KantoFuchsiaCity[] = INCBIN_U16("data/tilesets/secondary/kanto_fuchsia_city/metatile_attributes.bin");

const u16 gMetatiles_KantoCinnabarIsland[] = INCBIN_U16("data/tilesets/secondary/kanto_cinnabar_island/metatiles.bin");
const u16 gMetatileAttributes_KantoCinnabarIsland[] = INCBIN_U16("data/tilesets/secondary/kanto_cinnabar_island/metatile_attributes.bin");

const u16 gMetatiles_KantoIndigoPlateau[] = INCBIN_U16("data/tilesets/secondary/kanto_indigo_plateau/metatiles.bin");
const u16 gMetatileAttributes_KantoIndigoPlateau[] = INCBIN_U16("data/tilesets/secondary/kanto_indigo_plateau/metatile_attributes.bin");

const u16 gMetatiles_KantoSaffronCity[] = INCBIN_U16("data/tilesets/secondary/kanto_saffron_city/metatiles.bin");
const u16 gMetatileAttributes_KantoSaffronCity[] = INCBIN_U16("data/tilesets/secondary/kanto_saffron_city/metatile_attributes.bin");

const u16 gMetatiles_KantoPewterGym[] = INCBIN_U16("data/tilesets/secondary/kanto_pewter_gym/metatiles.bin");
const u16 gMetatileAttributes_KantoPewterGym[] = INCBIN_U16("data/tilesets/secondary/kanto_pewter_gym/metatile_attributes.bin");

const u16 gMetatiles_KantoCeruleanGym[] = INCBIN_U16("data/tilesets/secondary/kanto_cerulean_gym/metatiles.bin");
const u16 gMetatileAttributes_KantoCeruleanGym[] = INCBIN_U16("data/tilesets/secondary/kanto_cerulean_gym/metatile_attributes.bin");

const u16 gMetatiles_KantoVermilionGym[] = INCBIN_U16("data/tilesets/secondary/kanto_vermilion_gym/metatiles.bin");
const u16 gMetatileAttributes_KantoVermilionGym[] = INCBIN_U16("data/tilesets/secondary/kanto_vermilion_gym/metatile_attributes.bin");

const u16 gMetatiles_KantoCeladonGym[] = INCBIN_U16("data/tilesets/secondary/kanto_celadon_gym/metatiles.bin");
const u16 gMetatileAttributes_KantoCeladonGym[] = INCBIN_U16("data/tilesets/secondary/kanto_celadon_gym/metatile_attributes.bin");

const u16 gMetatiles_KantoFuchsiaGym[] = INCBIN_U16("data/tilesets/secondary/kanto_fuchsia_gym/metatiles.bin");
const u16 gMetatileAttributes_KantoFuchsiaGym[] = INCBIN_U16("data/tilesets/secondary/kanto_fuchsia_gym/metatile_attributes.bin");

const u16 gMetatiles_KantoSaffronGym[] = INCBIN_U16("data/tilesets/secondary/kanto_saffron_gym/metatiles.bin");
const u16 gMetatileAttributes_KantoSaffronGym[] = INCBIN_U16("data/tilesets/secondary/kanto_saffron_gym/metatile_attributes.bin");

const u16 gMetatiles_KantoCinnabarGym[] = INCBIN_U16("data/tilesets/secondary/kanto_cinnabar_gym/metatiles.bin");
const u16 gMetatileAttributes_KantoCinnabarGym[] = INCBIN_U16("data/tilesets/secondary/kanto_cinnabar_gym/metatile_attributes.bin");

const u16 gMetatiles_KantoViridianGym[] = INCBIN_U16("data/tilesets/secondary/kanto_viridian_gym/metatiles.bin");
const u16 gMetatileAttributes_KantoViridianGym[] = INCBIN_U16("data/tilesets/secondary/kanto_viridian_gym/metatile_attributes.bin");

const u16 gMetatiles_KantoBuilding[] = INCBIN_U16("data/tilesets/primary/kanto_building/metatiles.bin");
const u16 gMetatileAttributes_KantoBuilding[] = INCBIN_U16("data/tilesets/primary/kanto_building/metatile_attributes.bin");

const u16 gMetatiles_KantoDummy1[] = INCBIN_U16("data/tilesets/secondary/kanto_dummy_1/metatiles.bin");
const u16 gMetatileAttributes_KantoDummy1[] = INCBIN_U16("data/tilesets/secondary/kanto_dummy_1/metatile_attributes.bin");

const u16 gMetatiles_KantoHoennBuilding[] = INCBIN_U16("data/tilesets/secondary/kanto_hoenn_building/metatiles.bin");
const u16 gMetatileAttributes_KantoHoennBuilding[] = INCBIN_U16("data/tilesets/secondary/kanto_hoenn_building/metatile_attributes.bin");

const u16 gMetatiles_KantoBikeShop[] = INCBIN_U16("data/tilesets/secondary/kanto_bike_shop/metatiles.bin");
const u16 gMetatileAttributes_KantoBikeShop[] = INCBIN_U16("data/tilesets/secondary/kanto_bike_shop/metatile_attributes.bin");

const u16 gMetatiles_KantoMart[] = INCBIN_U16("data/tilesets/secondary/kanto_mart/metatiles.bin");
const u16 gMetatileAttributes_KantoMart[] = INCBIN_U16("data/tilesets/secondary/kanto_mart/metatile_attributes.bin");

const u16 gMetatiles_KantoPokemonCenter[] = INCBIN_U16("data/tilesets/secondary/kanto_pokemon_center/metatiles.bin");
const u16 gMetatileAttributes_KantoPokemonCenter[] = INCBIN_U16("data/tilesets/secondary/kanto_pokemon_center/metatile_attributes.bin");

const u16 gMetatiles_KantoGenericBuilding1[] = INCBIN_U16("data/tilesets/secondary/kanto_generic_building_1/metatiles.bin");
const u16 gMetatileAttributes_KantoGenericBuilding1[] = INCBIN_U16("data/tilesets/secondary/kanto_generic_building_1/metatile_attributes.bin");

const u16 gMetatiles_KantoCave[] = INCBIN_U16("data/tilesets/secondary/kanto_cave/metatiles.bin");
const u16 gMetatileAttributes_KantoCave[] = INCBIN_U16("data/tilesets/secondary/kanto_cave/metatile_attributes.bin");

const u16 gMetatiles_KantoGameCorner[] = INCBIN_U16("data/tilesets/secondary/kanto_game_corner/metatiles.bin");
const u16 gMetatileAttributes_KantoGameCorner[] = INCBIN_U16("data/tilesets/secondary/kanto_game_corner/metatile_attributes.bin");

const u16 gMetatiles_KantoLab[] = INCBIN_U16("data/tilesets/secondary/kanto_lab/metatiles.bin");
const u16 gMetatileAttributes_KantoLab[] = INCBIN_U16("data/tilesets/secondary/kanto_lab/metatile_attributes.bin");

const u16 gMetatiles_KantoSSAnne[] = INCBIN_U16("data/tilesets/secondary/kanto_ss_anne/metatiles.bin");
const u16 gMetatileAttributes_KantoSSAnne[] = INCBIN_U16("data/tilesets/secondary/kanto_ss_anne/metatile_attributes.bin");

const u16 gMetatiles_KantoDummy2[] = INCBIN_U16("data/tilesets/secondary/kanto_dummy_2/metatiles.bin");
const u16 gMetatileAttributes_KantoDummy2[] = INCBIN_U16("data/tilesets/secondary/kanto_dummy_2/metatile_attributes.bin");

const u16 gMetatiles_KantoViridianForest[] = INCBIN_U16("data/tilesets/secondary/kanto_viridian_forest/metatiles.bin");
const u16 gMetatileAttributes_KantoViridianForest[] = INCBIN_U16("data/tilesets/secondary/kanto_viridian_forest/metatile_attributes.bin");

const u16 gMetatiles_KantoUnusedGatehouse1[] = INCBIN_U16("data/tilesets/secondary/kanto_unused_gatehouse_1/metatiles.bin");
const u16 gMetatileAttributes_KantoUnusedGatehouse1[] = INCBIN_U16("data/tilesets/secondary/kanto_unused_gatehouse_1/metatile_attributes.bin");

const u16 gMetatiles_KantoRockTunnel[] = INCBIN_U16("data/tilesets/secondary/kanto_rock_tunnel/metatiles.bin");
const u16 gMetatileAttributes_KantoRockTunnel[] = INCBIN_U16("data/tilesets/secondary/kanto_rock_tunnel/metatile_attributes.bin");

const u16 gMetatiles_KantoDiglettsCave[] = INCBIN_U16("data/tilesets/secondary/kanto_digletts_cave/metatiles.bin");
const u16 gMetatileAttributes_KantoDiglettsCave[] = INCBIN_U16("data/tilesets/secondary/kanto_digletts_cave/metatile_attributes.bin");

const u16 gMetatiles_KantoSeafoamIslands[] = INCBIN_U16("data/tilesets/secondary/kanto_seafoam_islands/metatiles.bin");
const u16 gMetatileAttributes_KantoSeafoamIslands[] = INCBIN_U16("data/tilesets/secondary/kanto_seafoam_islands/metatile_attributes.bin");

const u16 gMetatiles_KantoUnusedGatehouse2[] = INCBIN_U16("data/tilesets/secondary/kanto_unused_gatehouse_2/metatiles.bin");
const u16 gMetatileAttributes_KantoUnusedGatehouse2[] = INCBIN_U16("data/tilesets/secondary/kanto_unused_gatehouse_2/metatile_attributes.bin");

const u16 gMetatiles_KantoCeruleanCave[] = INCBIN_U16("data/tilesets/secondary/kanto_cerulean_cave/metatiles.bin");
const u16 gMetatileAttributes_KantoCeruleanCave[] = INCBIN_U16("data/tilesets/secondary/kanto_cerulean_cave/metatile_attributes.bin");

const u16 gMetatiles_KantoDepartmentStore[] = INCBIN_U16("data/tilesets/secondary/kanto_department_store/metatiles.bin");
const u16 gMetatileAttributes_KantoDepartmentStore[] = INCBIN_U16("data/tilesets/secondary/kanto_department_store/metatile_attributes.bin");

const u16 gMetatiles_KantoGenericBuilding2[] = INCBIN_U16("data/tilesets/secondary/kanto_generic_building_2/metatiles.bin");
const u16 gMetatileAttributes_KantoGenericBuilding2[] = INCBIN_U16("data/tilesets/secondary/kanto_generic_building_2/metatile_attributes.bin");

const u16 gMetatiles_KantoPowerPlant[] = INCBIN_U16("data/tilesets/secondary/kanto_power_plant/metatiles.bin");
const u16 gMetatileAttributes_KantoPowerPlant[] = INCBIN_U16("data/tilesets/secondary/kanto_power_plant/metatile_attributes.bin");

const u16 gMetatiles_KantoSeaCottage[] = INCBIN_U16("data/tilesets/secondary/kanto_sea_cottage/metatiles.bin");
const u16 gMetatileAttributes_KantoSeaCottage[] = INCBIN_U16("data/tilesets/secondary/kanto_sea_cottage/metatile_attributes.bin");

const u16 gMetatiles_KantoSilphCo[] = INCBIN_U16("data/tilesets/secondary/kanto_silph_co/metatiles.bin");
const u16 gMetatileAttributes_KantoSilphCo[] = INCBIN_U16("data/tilesets/secondary/kanto_silph_co/metatile_attributes.bin");

const u16 gMetatiles_KantoUndergroundPath[] = INCBIN_U16("data/tilesets/secondary/kanto_underground_path/metatiles.bin");
const u16 gMetatileAttributes_KantoUndergroundPath[] = INCBIN_U16("data/tilesets/secondary/kanto_underground_path/metatile_attributes.bin");

const u16 gMetatiles_KantoPokemonTower[] = INCBIN_U16("data/tilesets/secondary/kanto_pokemon_tower/metatiles.bin");
const u16 gMetatileAttributes_KantoPokemonTower[] = INCBIN_U16("data/tilesets/secondary/kanto_pokemon_tower/metatile_attributes.bin");

const u16 gMetatiles_KantoSafariZoneBuilding[] = INCBIN_U16("data/tilesets/secondary/kanto_safari_zone_building/metatiles.bin");
const u16 gMetatileAttributes_KantoSafariZoneBuilding[] = INCBIN_U16("data/tilesets/secondary/kanto_safari_zone_building/metatile_attributes.bin");

const u16 gMetatiles_KantoPokemonMansion[] = INCBIN_U16("data/tilesets/secondary/kanto_pokemon_mansion/metatiles.bin");
const u16 gMetatileAttributes_KantoPokemonMansion[] = INCBIN_U16("data/tilesets/secondary/kanto_pokemon_mansion/metatile_attributes.bin");

const u16 gMetatiles_KantoMuseum[] = INCBIN_U16("data/tilesets/secondary/kanto_museum/metatiles.bin");
const u16 gMetatileAttributes_KantoMuseum[] = INCBIN_U16("data/tilesets/secondary/kanto_museum/metatile_attributes.bin");

const u16 gMetatiles_KantoCableClub[] = INCBIN_U16("data/tilesets/secondary/kanto_cable_club/metatiles.bin");
const u16 gMetatileAttributes_KantoCableClub[] = INCBIN_U16("data/tilesets/secondary/kanto_cable_club/metatile_attributes.bin");

const u16 gMetatiles_KantoRestaurantHotel[] = INCBIN_U16("data/tilesets/secondary/kanto_restaurant_hotel/metatiles.bin");
const u16 gMetatileAttributes_KantoRestaurantHotel[] = INCBIN_U16("data/tilesets/secondary/kanto_restaurant_hotel/metatile_attributes.bin");

const u16 gMetatiles_KantoSchool[] = INCBIN_U16("data/tilesets/secondary/kanto_school/metatiles.bin");
const u16 gMetatileAttributes_KantoSchool[] = INCBIN_U16("data/tilesets/secondary/kanto_school/metatile_attributes.bin");

const u16 gMetatiles_KantoFanClubDaycare[] = INCBIN_U16("data/tilesets/secondary/kanto_fan_club_daycare/metatiles.bin");
const u16 gMetatileAttributes_KantoFanClubDaycare[] = INCBIN_U16("data/tilesets/secondary/kanto_fan_club_daycare/metatile_attributes.bin");

const u16 gMetatiles_KantoCondominiums[] = INCBIN_U16("data/tilesets/secondary/kanto_condominiums/metatiles.bin");
const u16 gMetatileAttributes_KantoCondominiums[] = INCBIN_U16("data/tilesets/secondary/kanto_condominiums/metatile_attributes.bin");

const u16 gMetatiles_KantoBurgledHouse[] = INCBIN_U16("data/tilesets/secondary/kanto_burgled_house/metatiles.bin");
const u16 gMetatileAttributes_KantoBurgledHouse[] = INCBIN_U16("data/tilesets/secondary/kanto_burgled_house/metatile_attributes.bin");

const u16 gMetatiles_KantoDummy3[] = INCBIN_U16("data/tilesets/secondary/kanto_dummy_3/metatiles.bin");
const u16 gMetatileAttributes_KantoDummy3[] = INCBIN_U16("data/tilesets/secondary/kanto_dummy_3/metatile_attributes.bin");

const u16 gMetatiles_KantoDummy4[] = INCBIN_U16("data/tilesets/secondary/kanto_dummy_4/metatiles.bin");
const u16 gMetatileAttributes_KantoDummy4[] = INCBIN_U16("data/tilesets/secondary/kanto_dummy_4/metatile_attributes.bin");

const u16 gMetatiles_KantoMtEmber[] = INCBIN_U16("data/tilesets/secondary/kanto_mt_ember/metatiles.bin");
const u16 gMetatileAttributes_KantoMtEmber[] = INCBIN_U16("data/tilesets/secondary/kanto_mt_ember/metatile_attributes.bin");

const u16 gMetatiles_KantoBerryForest[] = INCBIN_U16("data/tilesets/secondary/kanto_berry_forest/metatiles.bin");
const u16 gMetatileAttributes_KantoBerryForest[] = INCBIN_U16("data/tilesets/secondary/kanto_berry_forest/metatile_attributes.bin");

const u16 gMetatiles_KantoNavelRock[] = INCBIN_U16("data/tilesets/secondary/kanto_navel_rock/metatiles.bin");
const u16 gMetatileAttributes_KantoNavelRock[] = INCBIN_U16("data/tilesets/secondary/kanto_navel_rock/metatile_attributes.bin");

const u16 gMetatiles_KantoTanobyRuins[] = INCBIN_U16("data/tilesets/secondary/kanto_tanoby_ruins/metatiles.bin");
const u16 gMetatileAttributes_KantoTanobyRuins[] = INCBIN_U16("data/tilesets/secondary/kanto_tanoby_ruins/metatile_attributes.bin");

const u16 gMetatiles_KantoSeviiIslands123[] = INCBIN_U16("data/tilesets/secondary/kanto_sevii_islands_123/metatiles.bin");
const u16 gMetatileAttributes_KantoSeviiIslands123[] = INCBIN_U16("data/tilesets/secondary/kanto_sevii_islands_123/metatile_attributes.bin");

const u16 gMetatiles_KantoSeviiIslands45[] = INCBIN_U16("data/tilesets/secondary/kanto_sevii_islands_45/metatiles.bin");
const u16 gMetatileAttributes_KantoSeviiIslands45[] = INCBIN_U16("data/tilesets/secondary/kanto_sevii_islands_45/metatile_attributes.bin");

const u16 gMetatiles_KantoSeviiIslands67[] = INCBIN_U16("data/tilesets/secondary/kanto_sevii_islands_67/metatiles.bin");
const u16 gMetatileAttributes_KantoSeviiIslands67[] = INCBIN_U16("data/tilesets/secondary/kanto_sevii_islands_67/metatile_attributes.bin");

const u16 gMetatiles_KantoTrainerTower[] = INCBIN_U16("data/tilesets/secondary/kanto_trainer_tower/metatiles.bin");
const u16 gMetatileAttributes_KantoTrainerTower[] = INCBIN_U16("data/tilesets/secondary/kanto_trainer_tower/metatile_attributes.bin");

const u16 gMetatiles_KantoIslandHarbor[] = INCBIN_U16("data/tilesets/secondary/kanto_island_harbor/metatiles.bin");
const u16 gMetatileAttributes_KantoIslandHarbor[] = INCBIN_U16("data/tilesets/secondary/kanto_island_harbor/metatile_attributes.bin");

const u16 gMetatiles_KantoPokemonLeague[] = INCBIN_U16("data/tilesets/secondary/kanto_pokemon_league/metatiles.bin");
const u16 gMetatileAttributes_KantoPokemonLeague[] = INCBIN_U16("data/tilesets/secondary/kanto_pokemon_league/metatile_attributes.bin");

const u16 gMetatiles_KantoHallOfFame[] = INCBIN_U16("data/tilesets/secondary/kanto_hall_of_fame/metatiles.bin");
const u16 gMetatileAttributes_KantoHallOfFame[] = INCBIN_U16("data/tilesets/secondary/kanto_hall_of_fame/metatile_attributes.bin");
