// Generated by tools/kanto_port/port_kanto.py from pokefirered. Do not edit by hand.

const struct Tileset gTileset_KantoGeneral =
{
    .isCompressed = TRUE,
    .isSecondary = FALSE,
    .tiles = gTilesetTiles_KantoGeneral,
    .palettes = gTilesetPalettes_KantoGeneral,
    .metatiles = gMetatiles_KantoGeneral,
    .metatileAttributes = gMetatileAttributes_KantoGeneral,
    .callback = NULL, // TODO: port InitTilesetAnim_General from pokefirered
};

const struct Tileset gTileset_KantoPalletTown =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoPalletTown,
    .palettes = gTilesetPalettes_KantoPalletTown,
    .metatiles = gMetatiles_KantoPalletTown,
    .metatileAttributes = gMetatileAttributes_KantoPalletTown,
    .callback = NULL,
};

const struct Tileset gTileset_KantoViridianCity =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoViridianCity,
    .palettes = gTilesetPalettes_KantoViridianCity,
    .metatiles = gMetatiles_KantoViridianCity,
    .metatileAttributes = gMetatileAttributes_KantoViridianCity,
    .callback = NULL,
};

const struct Tileset gTileset_KantoPewterCity =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoPewterCity,
    .palettes = gTilesetPalettes_KantoPewterCity,
    .metatiles = gMetatiles_KantoPewterCity,
    .metatileAttributes = gMetatileAttributes_KantoPewterCity,
    .callback = NULL,
};

const struct Tileset gTileset_KantoCeruleanCity =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoCeruleanCity,
    .palettes = gTilesetPalettes_KantoCeruleanCity,
    .metatiles = gMetatiles_KantoCeruleanCity,
    .metatileAttributes = gMetatileAttributes_KantoCeruleanCity,
    .callback = NULL,
};

const struct Tileset gTileset_KantoLavenderTown =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoLavenderTown,
    .palettes = gTilesetPalettes_KantoLavenderTown,
    .metatiles = gMetatiles_KantoLavenderTown,
    .metatileAttributes = gMetatileAttributes_KantoLavenderTown,
    .callback = NULL,
};

const struct Tileset gTileset_KantoVermilionCity =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoVermilionCity,
    .palettes = gTilesetPalettes_KantoVermilionCity,
    .metatiles = gMetatiles_KantoVermilionCity,
    .metatileAttributes = gMetatileAttributes_KantoVermilionCity,
    .callback = NULL,
};

const struct Tileset gTileset_KantoCeladonCity =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoCeladonCity,
    .palettes = gTilesetPalettes_KantoCeladonCity,
    .metatiles = gMetatiles_KantoCeladonCity,
    .metatileAttributes = gMetatileAttributes_KantoCeladonCity,
    .callback = NULL, // TODO: port InitTilesetAnim_CeladonCity from pokefirered
};

const struct Tileset gTileset_KantoFuchsiaCity =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoFuchsiaCity,
    .palettes = gTilesetPalettes_KantoFuchsiaCity,
    .metatiles = gMetatiles_KantoFuchsiaCity,
    .metatileAttributes = gMetatileAttributes_KantoFuchsiaCity,
    .callback = NULL,
};

const struct Tileset gTileset_KantoCinnabarIsland =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoCinnabarIsland,
    .palettes = gTilesetPalettes_KantoCinnabarIsland,
    .metatiles = gMetatiles_KantoCinnabarIsland,
    .metatileAttributes = gMetatileAttributes_KantoCinnabarIsland,
    .callback = NULL,
};

const struct Tileset gTileset_KantoIndigoPlateau =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoIndigoPlateau,
    .palettes = gTilesetPalettes_KantoIndigoPlateau,
    .metatiles = gMetatiles_KantoIndigoPlateau,
    .metatileAttributes = gMetatileAttributes_KantoIndigoPlateau,
    .callback = NULL,
};

const struct Tileset gTileset_KantoSaffronCity =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoSaffronCity,
    .palettes = gTilesetPalettes_KantoSaffronCity,
    .metatiles = gMetatiles_KantoSaffronCity,
    .metatileAttributes = gMetatileAttributes_KantoSaffronCity,
    .callback = NULL,
};

const struct Tileset gTileset_KantoBuilding =
{
    .isCompressed = TRUE,
    .isSecondary = FALSE,
    .tiles = gTilesetTiles_KantoBuilding,
    .palettes = gTilesetPalettes_KantoBuilding,
    .metatiles = gMetatiles_KantoBuilding,
    .metatileAttributes = gMetatileAttributes_KantoBuilding,
    .callback = NULL,
};

const struct Tileset gTileset_KantoMart =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoMart,
    .palettes = gTilesetPalettes_KantoMart,
    .metatiles = gMetatiles_KantoMart,
    .metatileAttributes = gMetatileAttributes_KantoMart,
    .callback = NULL,
};

const struct Tileset gTileset_KantoPokemonCenter =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoPokemonCenter,
    .palettes = gTilesetPalettes_KantoPokemonCenter,
    .metatiles = gMetatiles_KantoPokemonCenter,
    .metatileAttributes = gMetatileAttributes_KantoPokemonCenter,
    .callback = NULL,
};

const struct Tileset gTileset_KantoCave =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoCave,
    .palettes = gTilesetPalettes_KantoCave,
    .metatiles = gMetatiles_KantoCave,
    .metatileAttributes = gMetatileAttributes_KantoCave,
    .callback = NULL,
};

const struct Tileset gTileset_KantoDummy1 =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoDummy1,
    .palettes = gTilesetPalettes_KantoDummy1,
    .metatiles = gMetatiles_KantoDummy1,
    .metatileAttributes = gMetatileAttributes_KantoDummy1,
    .callback = NULL,
};

const struct Tileset gTileset_KantoMuseum =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoMuseum,
    .palettes = gTilesetPalettes_KantoMuseum,
    .metatiles = gMetatiles_KantoMuseum,
    .metatileAttributes = gMetatileAttributes_KantoMuseum,
    .callback = NULL,
};

const struct Tileset gTileset_KantoCableClub =
{
    .isCompressed = FALSE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoCableClub,
    .palettes = gTilesetPalettes_KantoCableClub,
    .metatiles = gMetatiles_KantoCableClub,
    .metatileAttributes = gMetatileAttributes_KantoCableClub,
    .callback = NULL,
};

const struct Tileset gTileset_KantoBikeShop =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoBikeShop,
    .palettes = gTilesetPalettes_KantoBikeShop,
    .metatiles = gMetatiles_KantoBikeShop,
    .metatileAttributes = gMetatileAttributes_KantoBikeShop,
    .callback = NULL,
};

const struct Tileset gTileset_KantoGenericBuilding1 =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoGenericBuilding1,
    .palettes = gTilesetPalettes_KantoGenericBuilding1,
    .metatiles = gMetatiles_KantoGenericBuilding1,
    .metatileAttributes = gMetatileAttributes_KantoGenericBuilding1,
    .callback = NULL,
};

const struct Tileset gTileset_KantoLab =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoLab,
    .palettes = gTilesetPalettes_KantoLab,
    .metatiles = gMetatiles_KantoLab,
    .metatileAttributes = gMetatileAttributes_KantoLab,
    .callback = NULL,
};

const struct Tileset gTileset_KantoFuchsiaGym =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoFuchsiaGym,
    .palettes = gTilesetPalettes_KantoFuchsiaGym,
    .metatiles = gMetatiles_KantoFuchsiaGym,
    .metatileAttributes = gMetatileAttributes_KantoFuchsiaGym,
    .callback = NULL,
};

const struct Tileset gTileset_KantoViridianGym =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoViridianGym,
    .palettes = gTilesetPalettes_KantoViridianGym,
    .metatiles = gMetatiles_KantoViridianGym,
    .metatileAttributes = gMetatileAttributes_KantoViridianGym,
    .callback = NULL,
};

const struct Tileset gTileset_KantoHoennBuilding =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoHoennBuilding,
    .palettes = gTilesetPalettes_KantoHoennBuilding,
    .metatiles = gMetatiles_KantoHoennBuilding,
    .metatileAttributes = gMetatileAttributes_KantoHoennBuilding,
    .callback = NULL,
};

const struct Tileset gTileset_KantoGameCorner =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoGameCorner,
    .palettes = gTilesetPalettes_KantoGameCorner,
    .metatiles = gMetatiles_KantoGameCorner,
    .metatileAttributes = gMetatileAttributes_KantoGameCorner,
    .callback = NULL,
};

const struct Tileset gTileset_KantoPewterGym =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoPewterGym,
    .palettes = gTilesetPalettes_KantoPewterGym,
    .metatiles = gMetatiles_KantoPewterGym,
    .metatileAttributes = gMetatileAttributes_KantoPewterGym,
    .callback = NULL,
};

const struct Tileset gTileset_KantoCeruleanGym =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoCeruleanGym,
    .palettes = gTilesetPalettes_KantoCeruleanGym,
    .metatiles = gMetatiles_KantoCeruleanGym,
    .metatileAttributes = gMetatileAttributes_KantoCeruleanGym,
    .callback = NULL,
};

const struct Tileset gTileset_KantoVermilionGym =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoVermilionGym,
    .palettes = gTilesetPalettes_KantoVermilionGym,
    .metatiles = gMetatiles_KantoVermilionGym,
    .metatileAttributes = gMetatileAttributes_KantoVermilionGym,
    .callback = NULL, // TODO: port InitTilesetAnim_VermilionGym from pokefirered
};

const struct Tileset gTileset_KantoCeladonGym =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoCeladonGym,
    .palettes = gTilesetPalettes_KantoCeladonGym,
    .metatiles = gMetatiles_KantoCeladonGym,
    .metatileAttributes = gMetatileAttributes_KantoCeladonGym,
    .callback = NULL, // TODO: port InitTilesetAnim_CeladonGym from pokefirered
};

const struct Tileset gTileset_KantoSaffronGym =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoSaffronGym,
    .palettes = gTilesetPalettes_KantoSaffronGym,
    .metatiles = gMetatiles_KantoSaffronGym,
    .metatileAttributes = gMetatileAttributes_KantoSaffronGym,
    .callback = NULL,
};

const struct Tileset gTileset_KantoCinnabarGym =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoCinnabarGym,
    .palettes = gTilesetPalettes_KantoCinnabarGym,
    .metatiles = gMetatiles_KantoCinnabarGym,
    .metatileAttributes = gMetatileAttributes_KantoCinnabarGym,
    .callback = NULL,
};

const struct Tileset gTileset_KantoSSAnne =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoSSAnne,
    .palettes = gTilesetPalettes_KantoSSAnne,
    .metatiles = gMetatiles_KantoSSAnne,
    .metatileAttributes = gMetatileAttributes_KantoSSAnne,
    .callback = NULL,
};

const struct Tileset gTileset_KantoDummy2 =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoDummy2,
    .palettes = gTilesetPalettes_KantoDummy2,
    .metatiles = gMetatiles_KantoDummy2,
    .metatileAttributes = gMetatileAttributes_KantoDummy2,
    .callback = NULL,
};

const struct Tileset gTileset_KantoViridianForest =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoViridianForest,
    .palettes = gTilesetPalettes_KantoViridianForest,
    .metatiles = gMetatiles_KantoViridianForest,
    .metatileAttributes = gMetatileAttributes_KantoViridianForest,
    .callback = NULL,
};

const struct Tileset gTileset_KantoUnusedGatehouse1 =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoUnusedGatehouse1,
    .palettes = gTilesetPalettes_KantoUnusedGatehouse1,
    .metatiles = gMetatiles_KantoUnusedGatehouse1,
    .metatileAttributes = gMetatileAttributes_KantoUnusedGatehouse1,
    .callback = NULL,
};

const struct Tileset gTileset_KantoRockTunnel =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoRockTunnel,
    .palettes = gTilesetPalettes_KantoRockTunnel,
    .metatiles = gMetatiles_KantoRockTunnel,
    .metatileAttributes = gMetatileAttributes_KantoRockTunnel,
    .callback = NULL,
};

const struct Tileset gTileset_KantoDiglettsCave =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoDiglettsCave,
    .palettes = gTilesetPalettes_KantoDiglettsCave,
    .metatiles = gMetatiles_KantoDiglettsCave,
    .metatileAttributes = gMetatileAttributes_KantoDiglettsCave,
    .callback = NULL,
};

const struct Tileset gTileset_KantoSeafoamIslands =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoSeafoamIslands,
    .palettes = gTilesetPalettes_KantoSeafoamIslands,
    .metatiles = gMetatiles_KantoSeafoamIslands,
    .metatileAttributes = gMetatileAttributes_KantoSeafoamIslands,
    .callback = NULL,
};

const struct Tileset gTileset_KantoUnusedGatehouse2 =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoUnusedGatehouse2,
    .palettes = gTilesetPalettes_KantoUnusedGatehouse2,
    .metatiles = gMetatiles_KantoUnusedGatehouse2,
    .metatileAttributes = gMetatileAttributes_KantoUnusedGatehouse2,
    .callback = NULL,
};

const struct Tileset gTileset_KantoCeruleanCave =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoCeruleanCave,
    .palettes = gTilesetPalettes_KantoCeruleanCave,
    .metatiles = gMetatiles_KantoCeruleanCave,
    .metatileAttributes = gMetatileAttributes_KantoCeruleanCave,
    .callback = NULL,
};

const struct Tileset gTileset_KantoDepartmentStore =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoDepartmentStore,
    .palettes = gTilesetPalettes_KantoDepartmentStore,
    .metatiles = gMetatiles_KantoDepartmentStore,
    .metatileAttributes = gMetatileAttributes_KantoDepartmentStore,
    .callback = NULL,
};

const struct Tileset gTileset_KantoGenericBuilding2 =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoGenericBuilding2,
    .palettes = gTilesetPalettes_KantoGenericBuilding2,
    .metatiles = gMetatiles_KantoGenericBuilding2,
    .metatileAttributes = gMetatileAttributes_KantoGenericBuilding2,
    .callback = NULL,
};

const struct Tileset gTileset_KantoPowerPlant =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoPowerPlant,
    .palettes = gTilesetPalettes_KantoPowerPlant,
    .metatiles = gMetatiles_KantoPowerPlant,
    .metatileAttributes = gMetatileAttributes_KantoPowerPlant,
    .callback = NULL,
};

const struct Tileset gTileset_KantoSeaCottage =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoSeaCottage,
    .palettes = gTilesetPalettes_KantoSeaCottage,
    .metatiles = gMetatiles_KantoSeaCottage,
    .metatileAttributes = gMetatileAttributes_KantoSeaCottage,
    .callback = NULL,
};

const struct Tileset gTileset_KantoSilphCo =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoCondominiums,
    .palettes = gTilesetPalettes_KantoCondominiums,
    .metatiles = gMetatiles_KantoSilphCo,
    .metatileAttributes = gMetatileAttributes_KantoSilphCo,
    .callback = NULL, // TODO: port InitTilesetAnim_SilphCo from pokefirered
};

const struct Tileset gTileset_KantoUndergroundPath =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoUndergroundPath,
    .palettes = gTilesetPalettes_KantoUndergroundPath,
    .metatiles = gMetatiles_KantoUndergroundPath,
    .metatileAttributes = gMetatileAttributes_KantoUndergroundPath,
    .callback = NULL,
};

const struct Tileset gTileset_KantoPokemonTower =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoPokemonTower,
    .palettes = gTilesetPalettes_KantoPokemonTower,
    .metatiles = gMetatiles_KantoPokemonTower,
    .metatileAttributes = gMetatileAttributes_KantoPokemonTower,
    .callback = NULL,
};

const struct Tileset gTileset_KantoSafariZoneBuilding =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoSafariZoneBuilding,
    .palettes = gTilesetPalettes_KantoSafariZoneBuilding,
    .metatiles = gMetatiles_KantoSafariZoneBuilding,
    .metatileAttributes = gMetatileAttributes_KantoSafariZoneBuilding,
    .callback = NULL,
};

const struct Tileset gTileset_KantoPokemonMansion =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoPokemonMansion,
    .palettes = gTilesetPalettes_KantoPokemonMansion,
    .metatiles = gMetatiles_KantoPokemonMansion,
    .metatileAttributes = gMetatileAttributes_KantoPokemonMansion,
    .callback = NULL,
};

const struct Tileset gTileset_KantoRestaurantHotel =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoRestaurantHotel,
    .palettes = gTilesetPalettes_KantoRestaurantHotel,
    .metatiles = gMetatiles_KantoRestaurantHotel,
    .metatileAttributes = gMetatileAttributes_KantoRestaurantHotel,
    .callback = NULL,
};

const struct Tileset gTileset_KantoSchool =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoSchool,
    .palettes = gTilesetPalettes_KantoSchool,
    .metatiles = gMetatiles_KantoSchool,
    .metatileAttributes = gMetatileAttributes_KantoSchool,
    .callback = NULL,
};

const struct Tileset gTileset_KantoFanClubDaycare =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoFanClubDaycare,
    .palettes = gTilesetPalettes_KantoFanClubDaycare,
    .metatiles = gMetatiles_KantoFanClubDaycare,
    .metatileAttributes = gMetatileAttributes_KantoFanClubDaycare,
    .callback = NULL,
};

const struct Tileset gTileset_KantoCondominiums =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoCondominiums,
    .palettes = gTilesetPalettes_KantoCondominiums,
    .metatiles = gMetatiles_KantoCondominiums,
    .metatileAttributes = gMetatileAttributes_KantoCondominiums,
    .callback = NULL,
};

const struct Tileset gTileset_KantoBurgledHouse =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoBurgledHouse,
    .palettes = gTilesetPalettes_KantoBurgledHouse,
    .metatiles = gMetatiles_KantoBurgledHouse,
    .metatileAttributes = gMetatileAttributes_KantoBurgledHouse,
    .callback = NULL,
};

const struct Tileset gTileset_KantoDummy3 =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoDummy3,
    .palettes = gTilesetPalettes_KantoDummy3,
    .metatiles = gMetatiles_KantoDummy3,
    .metatileAttributes = gMetatileAttributes_KantoDummy3,
    .callback = NULL,
};

const struct Tileset gTileset_KantoDummy4 =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoDummy4,
    .palettes = gTilesetPalettes_KantoDummy4,
    .metatiles = gMetatiles_KantoDummy4,
    .metatileAttributes = gMetatileAttributes_KantoDummy4,
    .callback = NULL,
};

const struct Tileset gTileset_KantoMtEmber =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoMtEmber,
    .palettes = gTilesetPalettes_KantoMtEmber,
    .metatiles = gMetatiles_KantoMtEmber,
    .metatileAttributes = gMetatileAttributes_KantoMtEmber,
    .callback = NULL, // TODO: port InitTilesetAnim_MtEmber from pokefirered
};

const struct Tileset gTileset_KantoBerryForest =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoBerryForest,
    .palettes = gTilesetPalettes_KantoBerryForest,
    .metatiles = gMetatiles_KantoBerryForest,
    .metatileAttributes = gMetatileAttributes_KantoBerryForest,
    .callback = NULL,
};

const struct Tileset gTileset_KantoNavelRock =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoNavelRock,
    .palettes = gTilesetPalettes_KantoNavelRock,
    .metatiles = gMetatiles_KantoNavelRock,
    .metatileAttributes = gMetatileAttributes_KantoNavelRock,
    .callback = NULL,
};

const struct Tileset gTileset_KantoTanobyRuins =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoTanobyRuins,
    .palettes = gTilesetPalettes_KantoTanobyRuins,
    .metatiles = gMetatiles_KantoTanobyRuins,
    .metatileAttributes = gMetatileAttributes_KantoTanobyRuins,
    .callback = NULL,
};

const struct Tileset gTileset_KantoSeviiIslands123 =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoSeviiIslands123,
    .palettes = gTilesetPalettes_KantoSeviiIslands123,
    .metatiles = gMetatiles_KantoSeviiIslands123,
    .metatileAttributes = gMetatileAttributes_KantoSeviiIslands123,
    .callback = NULL,
};

const struct Tileset gTileset_KantoSeviiIslands45 =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoSeviiIslands45,
    .palettes = gTilesetPalettes_KantoSeviiIslands45,
    .metatiles = gMetatiles_KantoSeviiIslands45,
    .metatileAttributes = gMetatileAttributes_KantoSeviiIslands45,
    .callback = NULL,
};

const struct Tileset gTileset_KantoSeviiIslands67 =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoSeviiIslands67,
    .palettes = gTilesetPalettes_KantoSeviiIslands67,
    .metatiles = gMetatiles_KantoSeviiIslands67,
    .metatileAttributes = gMetatileAttributes_KantoSeviiIslands67,
    .callback = NULL,
};

const struct Tileset gTileset_KantoTrainerTower =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoTrainerTower,
    .palettes = gTilesetPalettes_KantoTrainerTower,
    .metatiles = gMetatiles_KantoTrainerTower,
    .metatileAttributes = gMetatileAttributes_KantoTrainerTower,
    .callback = NULL,
};

const struct Tileset gTileset_KantoIslandHarbor =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoIslandHarbor,
    .palettes = gTilesetPalettes_KantoIslandHarbor,
    .metatiles = gMetatiles_KantoIslandHarbor,
    .metatileAttributes = gMetatileAttributes_KantoIslandHarbor,
    .callback = NULL,
};

const struct Tileset gTileset_KantoPokemonLeague =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoPokemonLeague,
    .palettes = gTilesetPalettes_KantoPokemonLeague,
    .metatiles = gMetatiles_KantoPokemonLeague,
    .metatileAttributes = gMetatileAttributes_KantoPokemonLeague,
    .callback = NULL,
};

const struct Tileset gTileset_KantoHallOfFame =
{
    .isCompressed = TRUE,
    .isSecondary = TRUE,
    .tiles = gTilesetTiles_KantoHallOfFame,
    .palettes = gTilesetPalettes_KantoHallOfFame,
    .metatiles = gMetatiles_KantoHallOfFame,
    .metatileAttributes = gMetatileAttributes_KantoHallOfFame,
    .callback = NULL,
};

