// Generated by tools/kanto_port/port_kanto.py from pokefirered. Do not edit by hand.

const u32 gTilesetTiles_KantoPalletTown[] = INCBIN_U32("data/tilesets/secondary/kanto_pallet_town/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoPalletTown[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_pallet_town/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pallet_town/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pallet_town/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pallet_town/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pallet_town/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pallet_town/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pallet_town/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pallet_town/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pallet_town/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pallet_town/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pallet_town/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pallet_town/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pallet_town/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pallet_town/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pallet_town/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pallet_town/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoViridianCity[] = INCBIN_U32("data/tilesets/secondary/kanto_viridian_city/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoViridianCity[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_viridian_city/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_viridian_city/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_viridian_city/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_viridian_city/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_viridian_city/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_viridian_city/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_viridian_city/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_viridian_city/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_viridian_city/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_viridian_city/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_viridian_city/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_viridian_city/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_viridian_city/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_viridian_city/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_viridian_city/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_viridian_city/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoPewterCity[] = INCBIN_U32("data/tilesets/secondary/kanto_pewter_city/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoPewterCity[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_pewter_city/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pewter_city/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pewter_city/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pewter_city/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pewter_city/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pewter_city/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pewter_city/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pewter_city/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pewter_city/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pewter_city/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pewter_city/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pewter_city/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pewter_city/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pewter_city/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pewter_city/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pewter_city/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoCeruleanCity[] = INCBIN_U32("data/tilesets/secondary/kanto_cerulean_city/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoCeruleanCity[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_cerulean_city/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cerulean_city/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cerulean_city/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cerulean_city/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cerulean_city/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cerulean_city/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cerulean_city/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cerulean_city/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cerulean_city/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cerulean_city/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cerulean_city/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cerulean_city/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cerulean_city/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cerulean_city/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cerulean_city/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cerulean_city/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoLavenderTown[] = INCBIN_U32("data/tilesets/secondary/kanto_lavender_town/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoLavenderTown[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_lavender_town/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_lavender_town/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_lavender_town/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_lavender_town/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_lavender_town/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_lavender_town/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_lavender_town/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_lavender_town/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_lavender_town/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_lavender_town/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_lavender_town/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_lavender_town/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_lavender_town/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_lavender_town/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_lavender_town/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_lavender_town/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoVermilionCity[] = INCBIN_U32("data/tilesets/secondary/kanto_vermilion_city/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoVermilionCity[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_vermilion_city/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_vermilion_city/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_vermilion_city/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_vermilion_city/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_vermilion_city/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_vermilion_city/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_vermilion_city/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_vermilion_city/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_vermilion_city/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_vermilion_city/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_vermilion_city/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_vermilion_city/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_vermilion_city/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_vermilion_city/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_vermilion_city/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_vermilion_city/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoCeladonCity[] = INCBIN_U32("data/tilesets/secondary/kanto_celadon_city/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoCeladonCity[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_celadon_city/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_celadon_city/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_celadon_city/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_celadon_city/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_celadon_city/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_celadon_city/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_celadon_city/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_celadon_city/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_celadon_city/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_celadon_city/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_celadon_city/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_celadon_city/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_celadon_city/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_celadon_city/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_celadon_city/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_celadon_city/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoFuchsiaCity[] = INCBIN_U32("data/tilesets/secondary/kanto_fuchsia_city/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoFuchsiaCity[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_fuchsia_city/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_fuchsia_city/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_fuchsia_city/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_fuchsia_city/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_fuchsia_city/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_fuchsia_city/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_fuchsia_city/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_fuchsia_city/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_fuchsia_city/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_fuchsia_city/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_fuchsia_city/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_fuchsia_city/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_fuchsia_city/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_fuchsia_city/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_fuchsia_city/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_fuchsia_city/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoCinnabarIsland[] = INCBIN_U32("data/tilesets/secondary/kanto_cinnabar_island/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoCinnabarIsland[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_cinnabar_island/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cinnabar_island/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cinnabar_island/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cinnabar_island/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cinnabar_island/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cinnabar_island/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cinnabar_island/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cinnabar_island/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cinnabar_island/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cinnabar_island/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cinnabar_island/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cinnabar_island/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cinnabar_island/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cinnabar_island/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cinnabar_island/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cinnabar_island/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoIndigoPlateau[] = INCBIN_U32("data/tilesets/secondary/kanto_indigo_plateau/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoIndigoPlateau[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_indigo_plateau/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_indigo_plateau/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_indigo_plateau/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_indigo_plateau/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_indigo_plateau/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_indigo_plateau/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_indigo_plateau/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_indigo_plateau/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_indigo_plateau/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_indigo_plateau/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_indigo_plateau/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_indigo_plateau/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_indigo_plateau/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_indigo_plateau/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_indigo_plateau/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_indigo_plateau/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoSaffronCity[] = INCBIN_U32("data/tilesets/secondary/kanto_saffron_city/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoSaffronCity[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_saffron_city/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_saffron_city/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_saffron_city/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_saffron_city/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_saffron_city/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_saffron_city/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_saffron_city/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_saffron_city/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_saffron_city/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_saffron_city/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_saffron_city/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_saffron_city/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_saffron_city/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_saffron_city/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_saffron_city/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_saffron_city/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoBuilding[] = INCBIN_U32("data/tilesets/primary/kanto_building/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoBuilding[][16] =
{
	INCBIN_U16("data/tilesets/primary/kanto_building/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/primary/kanto_building/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/primary/kanto_building/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/primary/kanto_building/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/primary/kanto_building/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/primary/kanto_building/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/primary/kanto_building/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/primary/kanto_building/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/primary/kanto_building/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/primary/kanto_building/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/primary/kanto_building/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/primary/kanto_building/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/primary/kanto_building/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/primary/kanto_building/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/primary/kanto_building/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/primary/kanto_building/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoMart[] = INCBIN_U32("data/tilesets/secondary/kanto_mart/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoMart[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_mart/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_mart/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_mart/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_mart/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_mart/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_mart/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_mart/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_mart/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_mart/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_mart/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_mart/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_mart/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_mart/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_mart/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_mart/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_mart/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoPokemonCenter[] = INCBIN_U32("data/tilesets/secondary/kanto_pokemon_center/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoPokemonCenter[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_center/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_center/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_center/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_center/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_center/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_center/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_center/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_center/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_center/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_center/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_center/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_center/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_center/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_center/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_center/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_center/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoCave[] = INCBIN_U32("data/tilesets/secondary/kanto_cave/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoCave[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_cave/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cave/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cave/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cave/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cave/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cave/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cave/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cave/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cave/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cave/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cave/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cave/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cave/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cave/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cave/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cave/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoDummy1[] = INCBIN_U32("data/tilesets/secondary/kanto_dummy_1/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoDummy1[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_1/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_1/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_1/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_1/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_1/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_1/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_1/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_1/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_1/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_1/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_1/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_1/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_1/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_1/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_1/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_1/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoMuseum[] = INCBIN_U32("data/tilesets/secondary/kanto_museum/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoMuseum[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_museum/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_museum/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_museum/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_museum/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_museum/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_museum/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_museum/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_museum/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_museum/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_museum/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_museum/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_museum/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_museum/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_museum/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_museum/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_museum/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoCableClub[] = INCBIN_U32("data/tilesets/secondary/kanto_cable_club/tiles.4bpp");

const u16 gTilesetPalettes_KantoCableClub[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_cable_club/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cable_club/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cable_club/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cable_club/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cable_club/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cable_club/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cable_club/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cable_club/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cable_club/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cable_club/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cable_club/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cable_club/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cable_club/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cable_club/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cable_club/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cable_club/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoBikeShop[] = INCBIN_U32("data/tilesets/secondary/kanto_bike_shop/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoBikeShop[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_bike_shop/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_bike_shop/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_bike_shop/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_bike_shop/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_bike_shop/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_bike_shop/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_bike_shop/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_bike_shop/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_bike_shop/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_bike_shop/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_bike_shop/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_bike_shop/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_bike_shop/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_bike_shop/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_bike_shop/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_bike_shop/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoLab[] = INCBIN_U32("data/tilesets/secondary/kanto_lab/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoLab[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_lab/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_lab/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_lab/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_lab/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_lab/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_lab/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_lab/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_lab/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_lab/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_lab/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_lab/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_lab/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_lab/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_lab/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_lab/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_lab/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoHoennBuilding[] = INCBIN_U32("data/tilesets/secondary/kanto_hoenn_building/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoHoennBuilding[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_hoenn_building/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_hoenn_building/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_hoenn_building/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_hoenn_building/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_hoenn_building/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_hoenn_building/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_hoenn_building/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_hoenn_building/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_hoenn_building/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_hoenn_building/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_hoenn_building/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_hoenn_building/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_hoenn_building/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_hoenn_building/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_hoenn_building/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_hoenn_building/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoGameCorner[] = INCBIN_U32("data/tilesets/secondary/kanto_game_corner/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoGameCorner[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_game_corner/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_game_corner/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_game_corner/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_game_corner/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_game_corner/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_game_corner/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_game_corner/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_game_corner/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_game_corner/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_game_corner/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_game_corner/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_game_corner/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_game_corner/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_game_corner/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_game_corner/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_game_corner/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoPewterGym[] = INCBIN_U32("data/tilesets/secondary/kanto_pewter_gym/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoPewterGym[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_pewter_gym/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pewter_gym/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pewter_gym/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pewter_gym/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pewter_gym/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pewter_gym/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pewter_gym/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pewter_gym/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pewter_gym/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pewter_gym/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pewter_gym/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pewter_gym/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pewter_gym/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pewter_gym/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pewter_gym/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pewter_gym/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoCeruleanGym[] = INCBIN_U32("data/tilesets/secondary/kanto_cerulean_gym/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoCeruleanGym[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_cerulean_gym/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cerulean_gym/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cerulean_gym/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cerulean_gym/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cerulean_gym/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cerulean_gym/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cerulean_gym/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cerulean_gym/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cerulean_gym/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cerulean_gym/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cerulean_gym/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cerulean_gym/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cerulean_gym/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cerulean_gym/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cerulean_gym/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cerulean_gym/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoVermilionGym[] = INCBIN_U32("data/tilesets/secondary/kanto_vermilion_gym/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoVermilionGym[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_vermilion_gym/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_vermilion_gym/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_vermilion_gym/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_vermilion_gym/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_vermilion_gym/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_vermilion_gym/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_vermilion_gym/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_vermilion_gym/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_vermilion_gym/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_vermilion_gym/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_vermilion_gym/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_vermilion_gym/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_vermilion_gym/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_vermilion_gym/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_vermilion_gym/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_vermilion_gym/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoCeladonGym[] = INCBIN_U32("data/tilesets/secondary/kanto_celadon_gym/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoCeladonGym[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_celadon_gym/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_celadon_gym/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_celadon_gym/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_celadon_gym/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_celadon_gym/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_celadon_gym/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_celadon_gym/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_celadon_gym/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_celadon_gym/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_celadon_gym/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_celadon_gym/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_celadon_gym/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_celadon_gym/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_celadon_gym/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_celadon_gym/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_celadon_gym/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoFuchsiaGym[] = INCBIN_U32("data/tilesets/secondary/kanto_fuchsia_gym/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoFuchsiaGym[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_fuchsia_gym/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_fuchsia_gym/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_fuchsia_gym/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_fuchsia_gym/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_fuchsia_gym/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_fuchsia_gym/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_fuchsia_gym/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_fuchsia_gym/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_fuchsia_gym/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_fuchsia_gym/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_fuchsia_gym/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_fuchsia_gym/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_fuchsia_gym/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_fuchsia_gym/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_fuchsia_gym/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_fuchsia_gym/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoSaffronGym[] = INCBIN_U32("data/tilesets/secondary/kanto_saffron_gym/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoSaffronGym[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_saffron_gym/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_saffron_gym/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_saffron_gym/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_saffron_gym/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_saffron_gym/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_saffron_gym/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_saffron_gym/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_saffron_gym/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_saffron_gym/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_saffron_gym/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_saffron_gym/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_saffron_gym/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_saffron_gym/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_saffron_gym/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_saffron_gym/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_saffron_gym/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoCinnabarGym[] = INCBIN_U32("data/tilesets/secondary/kanto_cinnabar_gym/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoCinnabarGym[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_cinnabar_gym/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cinnabar_gym/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cinnabar_gym/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cinnabar_gym/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cinnabar_gym/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cinnabar_gym/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cinnabar_gym/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cinnabar_gym/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cinnabar_gym/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cinnabar_gym/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cinnabar_gym/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cinnabar_gym/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cinnabar_gym/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cinnabar_gym/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cinnabar_gym/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cinnabar_gym/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoViridianGym[] = INCBIN_U32("data/tilesets/secondary/kanto_viridian_gym/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoViridianGym[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_viridian_gym/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_viridian_gym/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_viridian_gym/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_viridian_gym/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_viridian_gym/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_viridian_gym/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_viridian_gym/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_viridian_gym/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_viridian_gym/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_viridian_gym/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_viridian_gym/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_viridian_gym/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_viridian_gym/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_viridian_gym/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_viridian_gym/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_viridian_gym/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoSSAnne[] = INCBIN_U32("data/tilesets/secondary/kanto_ss_anne/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoSSAnne[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_ss_anne/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_ss_anne/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_ss_anne/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_ss_anne/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_ss_anne/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_ss_anne/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_ss_anne/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_ss_anne/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_ss_anne/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_ss_anne/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_ss_anne/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_ss_anne/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_ss_anne/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_ss_anne/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_ss_anne/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_ss_anne/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoDummy2[] = INCBIN_U32("data/tilesets/secondary/kanto_dummy_2/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoDummy2[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_2/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_2/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_2/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_2/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_2/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_2/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_2/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_2/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_2/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_2/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_2/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_2/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_2/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_2/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_2/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_2/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoViridianForest[] = INCBIN_U32("data/tilesets/secondary/kanto_viridian_forest/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoViridianForest[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_viridian_forest/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_viridian_forest/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_viridian_forest/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_viridian_forest/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_viridian_forest/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_viridian_forest/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_viridian_forest/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_viridian_forest/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_viridian_forest/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_viridian_forest/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_viridian_forest/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_viridian_forest/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_viridian_forest/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_viridian_forest/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_viridian_forest/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_viridian_forest/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoUnusedGatehouse1[] = INCBIN_U32("data/tilesets/secondary/kanto_unused_gatehouse_1/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoUnusedGatehouse1[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_unused_gatehouse_1/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_unused_gatehouse_1/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_unused_gatehouse_1/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_unused_gatehouse_1/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_unused_gatehouse_1/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_unused_gatehouse_1/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_unused_gatehouse_1/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_unused_gatehouse_1/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_unused_gatehouse_1/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_unused_gatehouse_1/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_unused_gatehouse_1/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_unused_gatehouse_1/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_unused_gatehouse_1/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_unused_gatehouse_1/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_unused_gatehouse_1/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_unused_gatehouse_1/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoRockTunnel[] = INCBIN_U32("data/tilesets/secondary/kanto_rock_tunnel/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoRockTunnel[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_rock_tunnel/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_rock_tunnel/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_rock_tunnel/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_rock_tunnel/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_rock_tunnel/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_rock_tunnel/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_rock_tunnel/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_rock_tunnel/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_rock_tunnel/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_rock_tunnel/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_rock_tunnel/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_rock_tunnel/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_rock_tunnel/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_rock_tunnel/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_rock_tunnel/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_rock_tunnel/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoDiglettsCave[] = INCBIN_U32("data/tilesets/secondary/kanto_digletts_cave/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoDiglettsCave[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_digletts_cave/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_digletts_cave/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_digletts_cave/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_digletts_cave/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_digletts_cave/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_digletts_cave/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_digletts_cave/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_digletts_cave/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_digletts_cave/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_digletts_cave/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_digletts_cave/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_digletts_cave/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_digletts_cave/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_digletts_cave/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_digletts_cave/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_digletts_cave/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoSeafoamIslands[] = INCBIN_U32("data/tilesets/secondary/kanto_seafoam_islands/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoSeafoamIslands[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_seafoam_islands/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_seafoam_islands/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_seafoam_islands/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_seafoam_islands/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_seafoam_islands/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_seafoam_islands/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_seafoam_islands/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_seafoam_islands/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_seafoam_islands/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_seafoam_islands/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_seafoam_islands/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_seafoam_islands/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_seafoam_islands/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_seafoam_islands/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_seafoam_islands/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_seafoam_islands/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoUnusedGatehouse2[] = INCBIN_U32("data/tilesets/secondary/kanto_unused_gatehouse_2/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoUnusedGatehouse2[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_unused_gatehouse_2/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_unused_gatehouse_2/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_unused_gatehouse_2/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_unused_gatehouse_2/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_unused_gatehouse_2/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_unused_gatehouse_2/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_unused_gatehouse_2/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_unused_gatehouse_2/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_unused_gatehouse_2/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_unused_gatehouse_2/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_unused_gatehouse_2/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_unused_gatehouse_2/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_unused_gatehouse_2/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_unused_gatehouse_2/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_unused_gatehouse_2/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_unused_gatehouse_2/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoCeruleanCave[] = INCBIN_U32("data/tilesets/secondary/kanto_cerulean_cave/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoCeruleanCave[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_cerulean_cave/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cerulean_cave/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cerulean_cave/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cerulean_cave/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cerulean_cave/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cerulean_cave/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cerulean_cave/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cerulean_cave/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cerulean_cave/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cerulean_cave/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cerulean_cave/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cerulean_cave/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cerulean_cave/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cerulean_cave/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cerulean_cave/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_cerulean_cave/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoGenericBuilding2[] = INCBIN_U32("data/tilesets/secondary/kanto_generic_building_2/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoGenericBuilding2[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_generic_building_2/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_generic_building_2/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_generic_building_2/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_generic_building_2/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_generic_building_2/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_generic_building_2/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_generic_building_2/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_generic_building_2/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_generic_building_2/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_generic_building_2/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_generic_building_2/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_generic_building_2/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_generic_building_2/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_generic_building_2/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_generic_building_2/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_generic_building_2/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoPowerPlant[] = INCBIN_U32("data/tilesets/secondary/kanto_power_plant/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoPowerPlant[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_power_plant/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_power_plant/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_power_plant/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_power_plant/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_power_plant/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_power_plant/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_power_plant/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_power_plant/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_power_plant/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_power_plant/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_power_plant/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_power_plant/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_power_plant/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_power_plant/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_power_plant/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_power_plant/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoSeaCottage[] = INCBIN_U32("data/tilesets/secondary/kanto_sea_cottage/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoSeaCottage[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_sea_cottage/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sea_cottage/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sea_cottage/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sea_cottage/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sea_cottage/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sea_cottage/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sea_cottage/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sea_cottage/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sea_cottage/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sea_cottage/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sea_cottage/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sea_cottage/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sea_cottage/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sea_cottage/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sea_cottage/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sea_cottage/palettes/15.gbapal"),
};

// Shared by SilphCo
const u32 gTilesetTiles_KantoCondominiums[] = INCBIN_U32("data/tilesets/secondary/kanto_condominiums/tiles.4bpp.lz");

// Shared by SilphCo
const u16 gTilesetPalettes_KantoCondominiums[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_condominiums/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_condominiums/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_condominiums/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_condominiums/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_condominiums/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_condominiums/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_condominiums/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_condominiums/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_condominiums/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_condominiums/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_condominiums/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_condominiums/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_condominiums/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_condominiums/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_condominiums/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_condominiums/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoUndergroundPath[] = INCBIN_U32("data/tilesets/secondary/kanto_underground_path/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoUndergroundPath[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_underground_path/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_underground_path/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_underground_path/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_underground_path/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_underground_path/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_underground_path/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_underground_path/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_underground_path/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_underground_path/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_underground_path/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_underground_path/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_underground_path/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_underground_path/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_underground_path/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_underground_path/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_underground_path/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoPokemonTower[] = INCBIN_U32("data/tilesets/secondary/kanto_pokemon_tower/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoPokemonTower[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_tower/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_tower/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_tower/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_tower/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_tower/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_tower/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_tower/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_tower/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_tower/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_tower/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_tower/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_tower/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_tower/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_tower/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_tower/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_tower/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoSafariZoneBuilding[] = INCBIN_U32("data/tilesets/secondary/kanto_safari_zone_building/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoSafariZoneBuilding[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_safari_zone_building/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_safari_zone_building/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_safari_zone_building/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_safari_zone_building/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_safari_zone_building/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_safari_zone_building/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_safari_zone_building/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_safari_zone_building/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_safari_zone_building/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_safari_zone_building/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_safari_zone_building/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_safari_zone_building/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_safari_zone_building/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_safari_zone_building/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_safari_zone_building/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_safari_zone_building/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoPokemonMansion[] = INCBIN_U32("data/tilesets/secondary/kanto_pokemon_mansion/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoPokemonMansion[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_mansion/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_mansion/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_mansion/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_mansion/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_mansion/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_mansion/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_mansion/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_mansion/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_mansion/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_mansion/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_mansion/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_mansion/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_mansion/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_mansion/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_mansion/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_mansion/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoRestaurantHotel[] = INCBIN_U32("data/tilesets/secondary/kanto_restaurant_hotel/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoRestaurantHotel[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_restaurant_hotel/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_restaurant_hotel/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_restaurant_hotel/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_restaurant_hotel/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_restaurant_hotel/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_restaurant_hotel/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_restaurant_hotel/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_restaurant_hotel/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_restaurant_hotel/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_restaurant_hotel/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_restaurant_hotel/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_restaurant_hotel/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_restaurant_hotel/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_restaurant_hotel/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_restaurant_hotel/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_restaurant_hotel/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoSchool[] = INCBIN_U32("data/tilesets/secondary/kanto_school/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoSchool[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_school/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_school/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_school/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_school/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_school/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_school/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_school/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_school/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_school/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_school/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_school/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_school/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_school/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_school/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_school/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_school/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoFanClubDaycare[] = INCBIN_U32("data/tilesets/secondary/kanto_fan_club_daycare/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoFanClubDaycare[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_fan_club_daycare/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_fan_club_daycare/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_fan_club_daycare/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_fan_club_daycare/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_fan_club_daycare/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_fan_club_daycare/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_fan_club_daycare/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_fan_club_daycare/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_fan_club_daycare/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_fan_club_daycare/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_fan_club_daycare/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_fan_club_daycare/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_fan_club_daycare/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_fan_club_daycare/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_fan_club_daycare/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_fan_club_daycare/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoBurgledHouse[] = INCBIN_U32("data/tilesets/secondary/kanto_burgled_house/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoBurgledHouse[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_burgled_house/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_burgled_house/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_burgled_house/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_burgled_house/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_burgled_house/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_burgled_house/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_burgled_house/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_burgled_house/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_burgled_house/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_burgled_house/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_burgled_house/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_burgled_house/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_burgled_house/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_burgled_house/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_burgled_house/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_burgled_house/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoDummy3[] = INCBIN_U32("data/tilesets/secondary/kanto_dummy_3/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoDummy3[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_3/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_3/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_3/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_3/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_3/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_3/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_3/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_3/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_3/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_3/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_3/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_3/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_3/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_3/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_3/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_3/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoDummy4[] = INCBIN_U32("data/tilesets/secondary/kanto_dummy_4/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoDummy4[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_4/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_4/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_4/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_4/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_4/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_4/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_4/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_4/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_4/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_4/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_4/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_4/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_4/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_4/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_4/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_dummy_4/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoMtEmber[] = INCBIN_U32("data/tilesets/secondary/kanto_mt_ember/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoMtEmber[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_mt_ember/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_mt_ember/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_mt_ember/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_mt_ember/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_mt_ember/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_mt_ember/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_mt_ember/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_mt_ember/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_mt_ember/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_mt_ember/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_mt_ember/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_mt_ember/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_mt_ember/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_mt_ember/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_mt_ember/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_mt_ember/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoBerryForest[] = INCBIN_U32("data/tilesets/secondary/kanto_berry_forest/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoBerryForest[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_berry_forest/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_berry_forest/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_berry_forest/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_berry_forest/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_berry_forest/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_berry_forest/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_berry_forest/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_berry_forest/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_berry_forest/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_berry_forest/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_berry_forest/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_berry_forest/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_berry_forest/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_berry_forest/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_berry_forest/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_berry_forest/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoNavelRock[] = INCBIN_U32("data/tilesets/secondary/kanto_navel_rock/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoNavelRock[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_navel_rock/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_navel_rock/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_navel_rock/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_navel_rock/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_navel_rock/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_navel_rock/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_navel_rock/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_navel_rock/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_navel_rock/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_navel_rock/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_navel_rock/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_navel_rock/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_navel_rock/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_navel_rock/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_navel_rock/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_navel_rock/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoTanobyRuins[] = INCBIN_U32("data/tilesets/secondary/kanto_tanoby_ruins/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoTanobyRuins[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_tanoby_ruins/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_tanoby_ruins/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_tanoby_ruins/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_tanoby_ruins/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_tanoby_ruins/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_tanoby_ruins/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_tanoby_ruins/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_tanoby_ruins/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_tanoby_ruins/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_tanoby_ruins/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_tanoby_ruins/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_tanoby_ruins/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_tanoby_ruins/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_tanoby_ruins/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_tanoby_ruins/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_tanoby_ruins/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoSeviiIslands123[] = INCBIN_U32("data/tilesets/secondary/kanto_sevii_islands_123/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoSeviiIslands123[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_sevii_islands_123/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sevii_islands_123/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sevii_islands_123/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sevii_islands_123/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sevii_islands_123/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sevii_islands_123/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sevii_islands_123/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sevii_islands_123/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sevii_islands_123/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sevii_islands_123/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sevii_islands_123/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sevii_islands_123/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sevii_islands_123/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sevii_islands_123/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sevii_islands_123/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sevii_islands_123/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoSeviiIslands45[] = INCBIN_U32("data/tilesets/secondary/kanto_sevii_islands_45/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoSeviiIslands45[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_sevii_islands_45/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sevii_islands_45/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sevii_islands_45/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sevii_islands_45/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sevii_islands_45/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sevii_islands_45/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sevii_islands_45/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sevii_islands_45/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sevii_islands_45/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sevii_islands_45/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sevii_islands_45/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sevii_islands_45/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sevii_islands_45/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sevii_islands_45/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sevii_islands_45/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sevii_islands_45/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoSeviiIslands67[] = INCBIN_U32("data/tilesets/secondary/kanto_sevii_islands_67/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoSeviiIslands67[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_sevii_islands_67/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sevii_islands_67/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sevii_islands_67/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sevii_islands_67/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sevii_islands_67/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sevii_islands_67/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sevii_islands_67/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sevii_islands_67/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sevii_islands_67/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sevii_islands_67/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sevii_islands_67/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sevii_islands_67/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sevii_islands_67/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sevii_islands_67/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sevii_islands_67/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_sevii_islands_67/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoTrainerTower[] = INCBIN_U32("data/tilesets/secondary/kanto_trainer_tower/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoTrainerTower[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_trainer_tower/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_trainer_tower/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_trainer_tower/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_trainer_tower/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_trainer_tower/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_trainer_tower/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_trainer_tower/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_trainer_tower/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_trainer_tower/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_trainer_tower/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_trainer_tower/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_trainer_tower/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_trainer_tower/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_trainer_tower/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_trainer_tower/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_trainer_tower/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoIslandHarbor[] = INCBIN_U32("data/tilesets/secondary/kanto_island_harbor/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoIslandHarbor[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_island_harbor/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_island_harbor/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_island_harbor/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_island_harbor/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_island_harbor/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_island_harbor/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_island_harbor/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_island_harbor/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_island_harbor/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_island_harbor/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_island_harbor/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_island_harbor/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_island_harbor/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_island_harbor/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_island_harbor/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_island_harbor/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoPokemonLeague[] = INCBIN_U32("data/tilesets/secondary/kanto_pokemon_league/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoPokemonLeague[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_league/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_league/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_league/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_league/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_league/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_league/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_league/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_league/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_league/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_league/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_league/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_league/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_league/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_league/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_league/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_pokemon_league/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoHallOfFame[] = INCBIN_U32("data/tilesets/secondary/kanto_hall_of_fame/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoHallOfFame[][16] =
{
	INCBIN_U16("data/tilesets/secondary/kanto_hall_of_fame/palettes/00.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_hall_of_fame/palettes/01.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_hall_of_fame/palettes/02.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_hall_of_fame/palettes/03.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_hall_of_fame/palettes/04.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_hall_of_fame/palettes/05.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_hall_of_fame/palettes/06.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_hall_of_fame/palettes/07.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_hall_of_fame/palettes/08.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_hall_of_fame/palettes/09.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_hall_of_fame/palettes/10.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_hall_of_fame/palettes/11.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_hall_of_fame/palettes/12.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_hall_of_fame/palettes/13.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_hall_of_fame/palettes/14.gbapal"),
	INCBIN_U16("data/tilesets/secondary/kanto_hall_of_fame/palettes/15.gbapal"),
};

// From pokefirered src/graphics.c
const u16 gTilesetPalettes_KantoGeneral[][16] =
{
    INCBIN_U16("data/tilesets/primary/kanto_general/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/primary/kanto_general/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/primary/kanto_general/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/primary/kanto_general/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/primary/kanto_general/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/primary/kanto_general/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/primary/kanto_general/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/primary/kanto_general/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/primary/kanto_general/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/primary/kanto_general/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/primary/kanto_general/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/primary/kanto_general/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/primary/kanto_general/palettes/12.gbapal"),
    INCBIN_U16("data/tilesets/primary/kanto_general/palettes/13.gbapal"),
    INCBIN_U16("data/tilesets/primary/kanto_general/palettes/14.gbapal"),
    INCBIN_U16("data/tilesets/primary/kanto_general/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoGeneral[] = INCBIN_U32("data/tilesets/primary/kanto_general/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoGenericBuilding1[][16] =
{
    INCBIN_U16("data/tilesets/secondary/kanto_generic_building_1/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kanto_generic_building_1/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kanto_generic_building_1/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kanto_generic_building_1/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kanto_generic_building_1/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kanto_generic_building_1/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kanto_generic_building_1/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kanto_generic_building_1/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kanto_generic_building_1/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kanto_generic_building_1/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kanto_generic_building_1/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kanto_generic_building_1/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kanto_generic_building_1/palettes/12.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kanto_generic_building_1/palettes/13.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kanto_generic_building_1/palettes/14.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kanto_generic_building_1/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoGenericBuilding1[] = INCBIN_U32("data/tilesets/secondary/kanto_generic_building_1/tiles.4bpp.lz");

const u16 gTilesetPalettes_KantoDepartmentStore[][16] =
{
    INCBIN_U16("data/tilesets/secondary/kanto_department_store/palettes/00.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kanto_department_store/palettes/01.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kanto_department_store/palettes/02.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kanto_department_store/palettes/03.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kanto_department_store/palettes/04.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kanto_department_store/palettes/05.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kanto_department_store/palettes/06.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kanto_department_store/palettes/07.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kanto_department_store/palettes/08.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kanto_department_store/palettes/09.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kanto_department_store/palettes/10.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kanto_department_store/palettes/11.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kanto_department_store/palettes/12.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kanto_department_store/palettes/13.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kanto_department_store/palettes/14.gbapal"),
    INCBIN_U16("data/tilesets/secondary/kanto_department_store/palettes/15.gbapal"),
};

const u32 gTilesetTiles_KantoDepartmentStore[] = INCBIN_U32("data/tilesets/secondary/kanto_department_store/tiles.4bpp.lz");
