#!/usr/bin/env python3
"""Port the trainers of the Kanto maps from pret/pokefirered.

    python3 tools/kanto_port/port_npcs.py objects --frlg ../pokefirered     # ports the trainer scripts
    python3 tools/kanto_port/port_trainers.py trainers --frlg ../pokefirered

Run from the pokeemerald root. `trainers` ports every FRLG trainer the map scripts battle
(TRAINER_KANTO_*, numbered after Emerald's trainers) with its party, trainer class and front pic.
"""
import argparse, json, os, re, shutil, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from port_kanto import read, write

GENERATED = "// Generated by tools/kanto_port/port_trainers.py from pokefirered. Do not edit by hand.\n"
KANTO_TRAINERS_START = 864          # MAX_TRAINERS_COUNT: Emerald's trainer ids end here
KANTO_TRAINER_FLAGS_COUNT = 512     # see KANTO_TRAINER_FLAGS_COUNT in include/constants/flags.h
FIRST_NEW_CLASS = 0x42              # after TRAINER_CLASS_RS_PROTAG
FIRST_NEW_PIC = 93                  # TRAINER_PIC_COUNT
OPPONENTS_H = "include/constants/opponents_kanto.h"
TRAINERS_H = "include/constants/trainers_kanto.h"
PARTIES = "src/data/kanto_trainer_parties.h"
ENTRIES = "src/data/kanto_trainers.h"
PICS = "src/data/trainer_graphics/kanto_trainer_pics.h"
PIC_DIR = "graphics/trainers/kanto"

# FRLG script commands with no Emerald equivalent that can simply be left out
DROPPED_COMMANDS = {"famechecker", "set_gym_trainers", "textcolor", "goto_if_questlog", "signmsg", "normalmsg",
                    "setworldmapflag", "trainerbattle_rematch", "trainerbattle_rematch_double", "setmetatile"}
ALWAYS_DEFINED = {"TRUE", "FALSE", "YES", "NO", "NO_MUSIC"}


def kanto_trainer(const):
    return "TRAINER_KANTO_" + const[len("TRAINER_"):]


class ScriptPorter:
    """Translates FRLG scripts (and the texts, movements and scripts they use) into Emerald's.

    Commands Emerald lacks are left out, as are lines whose constants Emerald doesn't define.
    FLAG_* names Emerald lacks are collected in .flags so they can be allocated."""

    def __init__(self, labels, emerald_labels, rename_label, map_of, current_map):
        self.labels = labels
        self.em_labels = emerald_labels
        self.rename_label = rename_label
        self.map_of = map_of
        self.current_map = current_map  # () -> new name of the map being ported
        self.local, self.common, self.flags, self.trainers = {}, {}, set(), set()
        self.localids = {}
        self.done = {}
        macros = re.findall(r"\.macro (\w+)", read("asm/macros/event.inc"))
        self.movements = set(re.findall(r"create_movement_action (\w+)", read("asm/macros/movement.inc")))
        self.commands = set(macros) | self.movements
        self.specials = set(re.findall(r"def_special (\w+)", read("data/specials.inc")))
        consts = set(ALWAYS_DEFINED)
        for root, _, names in os.walk("include/constants"):
            for n in names:
                # #defines and enum members alike
                consts |= set(re.findall(r"\b[A-Z][A-Z0-9_]{2,}\b", read(os.path.join(root, n))))
        for root, _, names in os.walk("data/maps"):
            for n in names:
                if n == "scripts.inc":
                    text = read(os.path.join(root, n)).split("@ BEGIN KANTO NPCS")[0]  # not our own output
                    consts |= set(re.findall(r"\b[A-Z][A-Z0-9_]{2,}\b", text))
        self.consts = consts
        self.defined_flags = set(re.findall(r"#define (FLAG_\w+)", read("include/constants/flags.h")))

    def begin_map(self, local, localids):
        self.local, self.localids = local, localids

    def _place(self, label):
        """New name for a FRLG label, and the dict its definition goes into."""
        owner = self.map_of(label)
        new = self.rename_label(label)
        if owner is not None and new.startswith(self.current_map() + "_"):
            return new, self.local
        return "Kanto_" + label, self.common

    def _kind(self, label):
        body = self.labels[label]
        lines = [l.strip() for l in body.splitlines() if l.strip() and not l.strip().startswith("@")]
        if ".string" in body:
            return "text"
        if lines and all(l.split()[0] in self.movements for l in lines):
            return "movement"
        if any(l.startswith((".2byte", ".byte", ".align")) for l in lines):
            return "data"
        return "script"

    def port(self, label):
        """Port a label; returns its new name, or None if it can't be ported."""
        if label not in self.labels:
            return None
        key = (label, self.current_map())
        if key in self.done:
            return self.done[key]
        kind = self._kind(label)
        if kind == "script" and label in self.em_labels and self.map_of(label) is None:
            self.done[key] = label  # Emerald has a common script of the same name
            return label
        new, where = self._place(label)
        self.done[key] = new
        body = self.labels[label]
        if kind == "text":
            from port_npcs import fix_text
            where[new] = f"{new}:\n" + fix_text(body).rstrip() + "\n"
        elif kind == "movement":
            where[new] = f"{new}:\n" + body.rstrip() + "\n"
        elif kind == "data":
            where[new] = f"\t.align 2\n{new}:\n" + body.rstrip() + "\n"
        else:
            lines = self.translate(body)
            if lines is None:
                self.done[key] = None
                return None
            where[new] = f"{new}::\n" + "\n".join(lines) + "\n"
        return new

    def translate(self, body, trainer=False):
        out, skip_result = [], False
        for raw in body.splitlines():
            line = raw.strip()
            if not line or line.startswith("@"):
                continue
            cmd, _, rest = line.partition(" ")
            args = [a.strip() for a in rest.split(",")] if rest else []
            if skip_result and "VAR_RESULT" in args:
                continue  # tests the result of a command that was left out
            skip_result = False
            if cmd == "giveitem_msg":  # FRLG: giveitem_msg msg, item[, amount[, fanfare]]
                cmd, args = "giveitem", args[1:3]
            if cmd in DROPPED_COMMANDS or cmd not in self.commands:
                skip_result = True
                continue
            if cmd in ("special", "specialvar") and args[-1] not in self.specials:
                skip_result = True
                continue
            new_args = []
            for a in args:
                if a in self.labels:
                    n = self.port(a)
                    if n is None:
                        break
                    new_args.append(n)
                    continue
                for tok in re.findall(r"\b[A-Z][A-Z0-9_]{2,}\b", a):
                    if tok.startswith("TRAINER_") and not tok.startswith("TRAINER_TYPE_") and not tok.startswith("TRAINER_BATTLE_"):
                        self.trainers.add(tok)
                        a = re.sub(rf"\b{tok}\b", kanto_trainer(tok), a)
                    elif tok.startswith("LOCALID_") and tok in self.localids:
                        a = re.sub(rf"\b{tok}\b", self.localids[tok], a)
                    elif tok.startswith("FLAG_"):
                        if tok not in self.defined_flags:
                            self.flags.add(tok)
                    elif tok not in self.consts:
                        break
                else:
                    new_args.append(a)
                    continue
                break
            else:
                out.append("\t" + cmd + (" " + ", ".join(new_args) if new_args else ""))
                continue
            skip_result = True  # the line was left out
        if trainer:
            # Trainers that spot the player need the script to start with trainerbattle
            first = next((i for i, l in enumerate(out) if l.strip().startswith("trainerbattle")), None)
            if first is None:
                return None
            out = out[first:]
        if not out or out[-1].strip() not in ("end", "return", "releaseall", "release") and not out[-1].strip().startswith("goto "):
            out.append("\tend")
        return out


# ---------------------------------------------------------------------------------------------
# Trainer data

def c_entries(text, array):
    """[KEY] = {...} entries of a designated initializer."""
    return {m.group(1): m.group(2) for m in re.finditer(r"\[(\w+)\]\s*=\s*(\{.*?\n    \}),", text, re.S)}


def cmd_trainers(args):
    frlg = args.frlg
    used = set()
    for root, _, names in os.walk("data/maps"):
        for n in names:
            if n == "scripts.inc":
                used |= set(re.findall(r"\bTRAINER_KANTO_\w+", read(os.path.join(root, n))))
    used = sorted(used)
    ftrainers = c_entries(read(f"{frlg}/src/data/trainers.h"), "gTrainers")
    fparties = read(f"{frlg}/src/data/trainer_parties.h")
    fconst = read(f"{frlg}/include/constants/trainers.h")
    em_const = read("include/constants/trainers.h")
    em_classes = set(re.findall(r"#define (TRAINER_CLASS_\w+)", em_const))
    fclass_names = dict(re.findall(r"\[(TRAINER_CLASS_\w+)\]\s*=\s*(_\(\".*?\"\))", read(f"{frlg}/src/data/text/trainer_class_names.h")))
    fmoney = dict(re.findall(r"\{(TRAINER_CLASS_\w+),\s*(\d+)\}", read(f"{frlg}/src/battle_main.c")))
    fpic_ids = {int(v): k for k, v in re.findall(r"#define (TRAINER_PIC_\w+)\s+(\d+)", fconst)}
    ftables = read(f"{frlg}/src/data/trainer_graphics/front_pic_tables.h")
    fcoords = re.findall(r"\{\.size = (\d+), \.y_offset = (\d+)\}", ftables.split("gTrainerFrontPicTable")[0])
    fsprites = dict(re.findall(r"TRAINER_SPRITE\((\w+), (\w+), \w+\)", ftables))
    fpals = dict(re.findall(r"TRAINER_PAL\((\w+), (\w+)\)", ftables))
    fgfx = dict(re.findall(r"const u32 (\w+)\[\] = INCBIN_U32\(\"(.*?)\.(?:4bpp|gbapal)\.lz\"\)", read(f"{frlg}/src/data/graphics/trainers.h")))

    consts, entries, parties, classes, pics = [], [], [], {}, {}
    party_names = set()
    for i, t in enumerate(used):
        frlg_name = "TRAINER_" + t[len("TRAINER_KANTO_"):]
        consts.append(f"#define {t:<48} {KANTO_TRAINERS_START + i}")
        body = ftrainers[frlg_name]
        cls = re.search(r"\.trainerClass = (\w+)", body).group(1)
        if cls not in em_classes and cls not in classes:
            classes[cls] = FIRST_NEW_CLASS + len(classes)
        pic = re.search(r"\.trainerPic = (\w+)", body).group(1)
        if pic not in pics:
            pics[pic] = FIRST_NEW_PIC + len(pics)
        body = body.replace(f".trainerPic = {pic}", f".trainerPic = TRAINER_PIC_KANTO_{pic[len('TRAINER_PIC_'):]}")
        for party in re.findall(r"\((sParty_\w+)\)", body):
            body = body.replace(party, party.replace("sParty_", "sParty_Kanto"))
            if party not in party_names:
                party_names.add(party)
                m = re.search(rf"static const struct (\w+) {party}\[\] = \{{.*?\n\}};", fparties, re.S)
                parties.append(m.group(0).replace(party, party.replace("sParty_", "sParty_Kanto")))
        entries.append(f"    [{t}] = {body},\n")

    # Front pics
    os.makedirs(f"{PIC_DIR}/front_pics", exist_ok=True)
    os.makedirs(f"{PIC_DIR}/palettes", exist_ok=True)
    pic_lines, coord_lines, sheet_lines, pal_lines, anim_lines = [], [], [], [], []
    for pic in sorted(pics, key=pics.get):
        short = pic[len("TRAINER_PIC_"):]
        kconst = f"TRAINER_PIC_KANTO_{short}"
        fid = [k for k, v in fpic_ids.items() if v == pic][0]
        size, yoff = fcoords[fid]
        sprite, pal = fsprites[short], fpals[short]
        png, palpath = fgfx[sprite], fgfx[pal]
        dst_png = f"{PIC_DIR}/front_pics/{os.path.basename(png)}.png"
        dst_pal = f"{PIC_DIR}/palettes/{os.path.basename(palpath)}.pal"
        shutil.copyfile(f"{frlg}/{png}.png", dst_png)
        shutil.copyfile(f"{frlg}/{palpath}.pal", dst_pal)
        ksprite, kpal = sprite.replace("gTrainerFrontPic_", "gTrainerFrontPic_Kanto"), pal.replace("gTrainerPalette_", "gTrainerPalette_Kanto")
        pic_lines.append(f'static const u32 {ksprite}[] = INCGFX_U32("{dst_png}", ".4bpp.lz");')
        pic_lines.append(f'static const u32 {kpal}[] = INCGFX_U32("{dst_pal}", ".gbapal.lz");')
        coord_lines.append(f"    [{kconst}] = {{.size = {size}, .y_offset = {yoff}}}, \\")
        sheet_lines.append(f"    [{kconst}] = {{{ksprite}, TRAINER_PIC_SIZE, {kconst}}}, \\")
        pal_lines.append(f"    [{kconst}] = {{{kpal}, {kconst}}}, \\")
        anim_lines.append(f"    [{kconst}] = sAnims_Hiker, \\")  # FRLG trainer pics have a single frame

    write(OPPONENTS_H, GENERATED + "#ifndef GUARD_CONSTANTS_OPPONENTS_KANTO_H\n#define GUARD_CONSTANTS_OPPONENTS_KANTO_H\n\n"
          "// FRLG trainers fought on the Kanto maps. They come after Emerald's trainers; their trainer flags\n"
          "// start at KANTO_TRAINER_FLAGS_START (see GetTrainerFlagId).\n"
          f"#define KANTO_TRAINERS_START {KANTO_TRAINERS_START}\n\n" + "\n".join(consts) +
          f"\n\n#define NUM_KANTO_TRAINERS {len(used)}\n#define ALL_TRAINERS_COUNT (KANTO_TRAINERS_START + NUM_KANTO_TRAINERS)\n\n"
          "#endif // GUARD_CONSTANTS_OPPONENTS_KANTO_H\n")
    if len(used) > KANTO_TRAINER_FLAGS_COUNT:
        sys.exit("too many Kanto trainers for KANTO_TRAINER_FLAGS_COUNT")
    class_defs = "\n".join(f"#define {c:<34} 0x{v:x}" for c, v in classes.items())
    write(TRAINERS_H, GENERATED + "#ifndef GUARD_CONSTANTS_TRAINERS_KANTO_H\n#define GUARD_CONSTANTS_TRAINERS_KANTO_H\n\n"
          "// FRLG trainer classes Emerald doesn't have\n" + class_defs + "\n\n"
          "// FRLG trainer front pics\n" + "\n".join(f"#define TRAINER_PIC_KANTO_{p[len('TRAINER_PIC_'):]:<26} {v}" for p, v in sorted(pics.items(), key=lambda x: x[1])) + "\n"
          f"#define TRAINER_PIC_KANTO_END {FIRST_NEW_PIC + len(pics)}\n\n"
          "// Entries for gTrainerClassNames and gTrainerMoneyTable\n"
          "#define KANTO_TRAINER_CLASS_NAMES \\\n" + " \\\n".join(f"    [{c}] = {fclass_names[c]}," for c in classes) + "\n\n"
          "#define KANTO_TRAINER_MONEY \\\n" + " \\\n".join(f"    {{{c}, {fmoney.get(c, 5)}}}," for c in classes) + "\n\n"
          "#endif // GUARD_CONSTANTS_TRAINERS_KANTO_H\n")
    write(PARTIES, GENERATED + "// Included by data.c after trainer_parties.h\n\n" + "\n\n".join(parties) + "\n")
    write(ENTRIES, GENERATED + "// Included in gTrainers (src/data/trainers.h)\n\n" + "\n".join(entries))
    for lst in (coord_lines, sheet_lines, pal_lines, anim_lines):
        lst[-1] = lst[-1].rstrip(" \\")
    write(PICS, GENERATED + "// Included by data.c before the trainer front pic tables\n\n" + "\n".join(pic_lines) + "\n\n"
          "#define KANTO_TRAINER_FRONT_PIC_COORDS \\\n" + "\n".join(coord_lines) + "\n\n"
          "#define KANTO_TRAINER_FRONT_PICS \\\n" + "\n".join(sheet_lines) + "\n\n"
          "#define KANTO_TRAINER_FRONT_PALETTES \\\n" + "\n".join(pal_lines) + "\n\n"
          "#define KANTO_TRAINER_FRONT_ANIMS \\\n" + "\n".join(anim_lines) + "\n")
    print(f"ported {len(used)} trainers, {len(classes)} new trainer classes, {len(pics)} trainer pics")


def main():
    if not os.path.exists("include/constants/opponents.h"):
        sys.exit("run from the pokeemerald root")
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    t = sub.add_parser("trainers"); t.add_argument("--frlg", default="../pokefirered"); t.set_defaults(fn=cmd_trainers)
    args = ap.parse_args(); args.fn(args)


if __name__ == "__main__":
    main()
