#!/usr/bin/env python3
"""Port the NPCs of the Kanto maps from pret/pokefirered.

    python3 tools/kanto_port/port_npcs.py sprites --frlg ../pokefirered
    python3 tools/kanto_port/port_npcs.py objects --frlg ../pokefirered

Run from the pokeemerald root, after port_kanto.py maps. Both commands are idempotent.

sprites: ports every FRLG object event graphic used by the ported maps as OBJ_EVENT_GFX_KANTO_*
         (graphics ids from 256, see include/constants/event_objects_kanto.h), with FRLG's palettes.
         Generated code goes to src/data/object_events/kanto_object_events.h.
objects: puts the FRLG objects (NPCs, item balls, Cut trees...) on the ported maps and gives them
         scripts, see port_objects() for what is and is not ported.
"""
import argparse, json, os, re, shutil, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from port_kanto import read, write, load_manifest

GFX_START = 256
KANTO_CONSTANTS = "include/constants/event_objects_kanto.h"
KANTO_HEADER = "src/data/object_events/kanto_object_events.h"
PIC_DIR = "graphics/object_events/pics/kanto"
PAL_DIR = "graphics/object_events/palettes/kanto"
GENERATED = "// Generated by tools/kanto_port/port_npcs.py from pokefirered. Do not edit by hand.\n"

# FRLG animation tables -> Emerald's (same animations, different names)
ANIMS = {"sAnimTable_Standard": "sAnimTable_Standard", "sAnimTable_Inanimate": "sAnimTable_Inanimate",
         "sAnimTable_Nurse": "sAnimTable_Nurse", "sAnimTable_CutTree": "sAnimTable_CuttableTree",
         "sAnimTable_RockSmashRock": "sAnimTable_BreakableRock", "sAnimTable_HoOh": "sAnimTable_HoOh"}
# FRLG's four NPC palettes go in the same slots as Emerald's NPC_1..4 on Kanto maps
NPC_PALETTES = ["NPC_BLUE", "NPC_PINK", "NPC_GREEN", "NPC_WHITE"]


def camel(name):
    return "".join(p.capitalize() for p in name.lower().split("_"))


def used_frlg_gfx(frlg):
    """FRLG graphics ids used by the objects of the ported maps."""
    used = set()
    for fname in load_manifest()["maps"]:
        j = json.loads(read(f"{frlg}/data/maps/{fname}/map.json"))
        for o in j["object_events"]:
            g = o.get("graphics_id", "0")
            if g.startswith("OBJ_EVENT_GFX_") and not g.startswith("OBJ_EVENT_GFX_VAR_"):
                used.add(g)
        # Objects whose graphics are picked by a var get them from the map's scripts.
        src = read(f"{frlg}/data/maps/{fname}/scripts.inc")
        used |= set(re.findall(r"setvar VAR_OBJ_GFX_ID_\w+, (OBJ_EVENT_GFX_\w+)", src))
    return sorted(used)


def c_blocks(text, kind):
    """name -> body of every `<kind> name... = { ... };` definition in text."""
    out = {}
    for m in re.finditer(kind + r"\s+(\w+)(\[\])?\s*=\s*\{(.*?)\n\};", text, re.S):
        out[m.group(1)] = m.group(3)
    return out


def cmd_sprites(args):
    frlg = args.frlg
    fsrc = f"{frlg}/src/data/object_events"
    infos = c_blocks(read(f"{fsrc}/object_event_graphics_info.h"), r"const struct ObjectEventGraphicsInfo")
    pointers = dict(re.findall(r"\[(OBJ_EVENT_GFX_\w+)\]\s*=\s*&(\w+)", read(f"{fsrc}/object_event_graphics_info_pointers.h")))
    pic_tables = c_blocks(read(f"{fsrc}/object_event_pic_tables.h"), r"static const struct SpriteFrameImage")
    graphics = read(f"{fsrc}/object_event_graphics.h")
    pics = dict(re.findall(r"const u(?:16|32) (gObjectEventPic_\w+)\[\] = INCBIN_U(?:16|32)\(\"(.*?)\.4bpp\"\)", graphics))
    pals = dict(re.findall(r"const u16 (gObjectEventPal_\w+)\[\] = INCBIN_U16\(\"(.*?)\.gbapal\"\)", graphics))
    fevent = read(f"{frlg}/src/event_object_movement.c")
    pal_of_tag = {t: p for p, t in re.findall(r"\{(gObjectEventPal_\w+),\s*(OBJ_EVENT_PAL_TAG_\w+)\}", fevent)}
    sheet_args = dict(re.findall(r"\$\(OBJEVENTGFXDIR\)/(\S+)\.4bpp: %\.4bpp: %\.png\n\t\$\(GFX\) \$< \$@ (.*)",
                                 read(f"{frlg}/spritesheet_rules.mk")))
    subsprites = read(f"{fsrc}/object_event_subsprites.h")
    em_subsprites = set(re.findall(r"SubspriteTable (sOamTables_\w+)\[\]", read("src/data/object_events/object_event_subsprites.h")))
    em_oams = set(re.findall(r"OamData (gObjectEventBaseOam_\w+)", read("src/data/object_events/base_oam.h")))
    foams = c_blocks(read(f"{fsrc}/base_oam.h"), r"const struct OamData")

    used = used_frlg_gfx(frlg)
    consts, pic_lines, table_lines, info_lines, ptr_lines = [], [], [], [], []
    extra_lines, done_pics, done_tables, pal_tags = [], set(), set(), {}
    for t in NPC_PALETTES:  # always ported: Kanto maps load these into the NPC palette slots
        pal_tags[f"OBJ_EVENT_PAL_TAG_{t}"] = None
        pal_tags[f"OBJ_EVENT_PAL_TAG_{t}_REFLECTION"] = None

    def kanto_tag(tag):
        return "OBJ_EVENT_PAL_TAG_KANTO_" + tag[len("OBJ_EVENT_PAL_TAG_"):]

    for i, gfx in enumerate(used):
        kname = "OBJ_EVENT_GFX_KANTO_" + gfx[len("OBJ_EVENT_GFX_"):]
        consts.append(f"#define {kname:<48} {GFX_START + i}")
        info_name = pointers[gfx]
        body = infos[info_name]
        new_info = info_name.replace("gObjectEventGraphicsInfo_", "gObjectEventGraphicsInfo_Kanto")
        table = re.search(r"\.images = (\w+)", body).group(1)
        new_table = table.replace("sPicTable_", "sPicTable_Kanto")
        if table not in done_tables:
            done_tables.add(table)
            frames = pic_tables[table]
            for pic in sorted(set(re.findall(r"gObjectEventPic_\w+", frames))):
                if pic in done_pics:
                    continue
                done_pics.add(pic)
                path = pics[pic]  # e.g. graphics/object_events/pics/people/boy
                rel = path[len("graphics/object_events/pics/"):]
                dst = f"{PIC_DIR}/{rel}.png"
                os.makedirs(os.path.dirname(dst), exist_ok=True)
                shutil.copyfile(f"{frlg}/{path}.png", dst)
                extra = sheet_args.get(rel, "")
                argstr = f', "{extra}"' if extra else ""
                pic_lines.append(f'const u32 {pic.replace("Pic_", "Pic_Kanto")}[] = INCGFX_U32("{dst}", ".4bpp"{argstr});')
            frames = re.sub(r"gObjectEventPic_(\w+)", r"gObjectEventPic_Kanto\1", frames)
            table_lines.append(f"static const struct SpriteFrameImage {new_table}[] = {{{frames}\n}};\n")
        body = body.replace(f".images = {table}", f".images = {new_table}")
        for tagfield in ("paletteTag", "reflectionPaletteTag"):
            tag = re.search(rf"\.{tagfield} = (\w+)", body).group(1)
            if tag != "OBJ_EVENT_PAL_TAG_NONE":
                pal_tags[tag] = None
                body = body.replace(f".{tagfield} = {tag}", f".{tagfield} = {kanto_tag(tag)}")
        anim = re.search(r"\.anims = (\w+)", body).group(1)
        body = body.replace(f".anims = {anim}", f".anims = {ANIMS.get(anim, 'sAnimTable_Standard')}")
        oam = re.search(r"\.oam = &(\w+)", body).group(1)
        if oam not in em_oams:
            body = body.replace(f"&{oam}", f"&{oam.replace('gObjectEventBaseOam_', 'sKantoObjectEventBaseOam_')}")
            if oam not in done_pics:
                done_pics.add(oam)
                extra_lines.append(f"static const struct OamData {oam.replace('gObjectEventBaseOam_', 'sKantoObjectEventBaseOam_')} = {{{foams[oam]}\n}};\n")
        sub = re.search(r"\.subspriteTables = (\w+)", body).group(1)
        size = sub[len("gObjectEventSpriteOamTables_"):]
        if f"sOamTables_{size}" in em_subsprites:
            body = body.replace(sub, f"sOamTables_{size}")
        elif sub not in done_pics:
            # Copy FRLG's subsprite table and the subsprite lists it uses
            done_pics.add(sub)
            parts = re.findall(rf"(const struct Subsprite (gObjectEventSpriteOamTable_{size}_\d+)\[\] = \{{.*?\n\}};)", subsprites, re.S)
            for text, name in parts:
                extra_lines.append("static " + text.replace(name, name.replace("gObjectEvent", "sKanto")) + "\n")
            tbl = re.search(rf"const struct SubspriteTable {sub}\[\] = \{{.*?\n\}};", subsprites, re.S).group(0)
            tbl = re.sub(r"gObjectEventSpriteOamTable_", "sKantoSpriteOamTable_", tbl).replace(sub, f"sKantoOamTables_{size}")
            extra_lines.append("static " + tbl + "\n")
            body = body.replace(sub, f"sKantoOamTables_{size}")
        else:
            body = body.replace(sub, f"sKantoOamTables_{size}")
        info_lines.append(f"const struct ObjectEventGraphicsInfo {new_info} = {{{body}\n}};\n")
        ptr_lines.append(f"    [{kname} - OBJ_EVENT_GFX_KANTO_START] = &{new_info},")

    pal_lines, pal_defs, pal_table = [], [], []
    for i, tag in enumerate(sorted(pal_tags)):
        pal = pal_of_tag[tag]
        path = pals[pal]
        dst = f"{PAL_DIR}/{os.path.basename(path)}.pal"
        os.makedirs(PAL_DIR, exist_ok=True)
        shutil.copyfile(f"{frlg}/{path}.pal", dst)
        new_pal = pal.replace("gObjectEventPal_", "gObjectEventPal_Kanto")
        if new_pal not in "\n".join(pal_lines):
            pal_lines.append(f'const u16 {new_pal}[] = INCGFX_U16("{dst}", ".gbapal");')
        pal_defs.append(f"#define {kanto_tag(tag):<52} 0x{0x1140 + i:04X}")
        pal_table.append(f"    {{{new_pal}, {kanto_tag(tag)}}}, \\")

    write(KANTO_CONSTANTS, GENERATED + "#ifndef GUARD_CONSTANTS_EVENT_OBJECTS_KANTO_H\n#define GUARD_CONSTANTS_EVENT_OBJECTS_KANTO_H\n\n"
          f"// FRLG object event graphics, used by the Kanto maps. They come after OBJ_EVENT_GFX_VAR_F.\n"
          f"#define OBJ_EVENT_GFX_KANTO_START {GFX_START}\n\n" + "\n".join(consts) +
          f"\n\n#define NUM_KANTO_OBJ_EVENT_GFX {len(used)}\n\n#endif // GUARD_CONSTANTS_EVENT_OBJECTS_KANTO_H\n")
    npc_tags = "\n".join(f"    [PALSLOT_NPC_{n + 1}{r}] = OBJ_EVENT_PAL_TAG_KANTO_{t}{r.replace('_REFLECTION', '_REFLECTION')}," for r in ("", "_REFLECTION") for n, t in enumerate(NPC_PALETTES))
    write(KANTO_HEADER, GENERATED + "// Included by event_object_movement.c.\n\n"
          + "\n".join(pal_defs) + "\n\n"
          + "// Entries for sObjectEventSpritePalettes\n#define KANTO_OBJECT_EVENT_SPRITE_PALETTES \\\n" + "\n".join(pal_table) + "\n\n"
          + "// The NPC palettes loaded on Kanto maps, see InitObjectEventPalettes\n"
          + "#define KANTO_NPC_PALETTE_TAGS \\\n" + " \\\n".join(l.rstrip(",") + "," for l in npc_tags.split("\n")) + "\n\n"
          + "\n".join(pal_lines) + "\n\n" + "\n".join(pic_lines) + "\n\n" + "\n".join(table_lines) + "\n"
          + "\n".join(extra_lines) + "\n" + "\n".join(info_lines) + "\n"
          + "static const struct ObjectEventGraphicsInfo *const sKantoObjectEventGraphicsInfoPointers[NUM_KANTO_OBJ_EVENT_GFX] = {\n"
          + "\n".join(ptr_lines) + "\n};\n")
    print(f"ported {len(used)} object event graphics with {len(pal_tags)} palettes")


# ---------------------------------------------------------------------------------------------
# Objects

KANTO_SCRIPTS = "data/scripts/kanto_npcs.inc"
NPC_BEGIN = "@ BEGIN KANTO NPCS: generated by tools/kanto_port/port_npcs.py from pokefirered. Do not edit by hand."
NPC_END = "@ END KANTO NPCS"
FLAGS_H = "include/constants/flags.h"
# FRLG scripts Emerald has under the same name and that work the same way
SHARED_SCRIPTS = {"EventScript_RockSmash", "EventScript_StrengthBoulder", "EventScript_CutTree",
                  "Common_EventScript_UnionRoomAttendant", "Common_EventScript_WirelessClubAttendant",
                  "Common_EventScript_DirectCornerAttendant", "CableClub_EventScript_MysteryGiftMan"}
MOVEMENT_TYPES = {"MOVEMENT_TYPE_WANDER_AROUND_SLOWER": "MOVEMENT_TYPE_WANDER_AROUND"}
TEXT_FIXES = [(r"\{FONT_(MALE|FEMALE|NORMAL)\}", ""), (r"\{LEFT_PAREN\}", "("), (r"\{RIGHT_PAREN\}", ")")]


def frlg_labels(frlg):
    """label -> body for every label in FRLG's script and text files."""
    files = [f"{frlg}/data/event_scripts.s"]
    for d in ("data/scripts", "data/text", "data/maps"):
        for root, _, names in os.walk(f"{frlg}/{d}"):
            files += [os.path.join(root, n) for n in names if n.endswith(".inc")]
    labels = {}
    for f in files:
        text = read(f)
        for m in re.finditer(r"^(\w+)::?[ \t]*\n(.*?)(?=^\w+::?[ \t]*$|^\s*\.include|\Z)", text, re.S | re.M):
            labels.setdefault(m.group(1), m.group(2))
    return labels


def emerald_labels():
    out = set()
    for root, _, names in os.walk("data"):
        for n in names:
            if n.endswith((".inc", ".s")):
                out |= set(re.findall(r"^(\w+)::", read(os.path.join(root, n)), re.M))
    return out


def allocate_flags(names):
    """Define the FRLG flags Emerald lacks in place of unused (non-daily) Emerald flags."""
    text = read(FLAGS_H)
    defined = set(re.findall(r"#define (FLAG_\w+)", text))
    missing = [n for n in sorted(names) if n not in defined]
    free = [m for m in re.finditer(r"^#define (FLAG_UNUSED_0x([0-9A-F]+))(\s+)(.*?)[ \t]*// Unused Flag[ \t]*$", text, re.M)
            if int(m.group(2), 16) < 0x91F]
    if len(missing) > len(free):
        sys.exit(f"{len(missing)} flags needed but only {len(free)} unused flags are left")
    for name, m in zip(missing, free):
        width = len(m.group(1)) + len(m.group(3))
        text = text.replace(m.group(0), f"#define {name:<{max(width - 1, len(name))}} {m.group(4)} // Kanto (FRLG)", 1)
    write(FLAGS_H, text)
    return missing


def fix_text(body):
    for a, b in TEXT_FIXES:
        body = re.sub(a, b, body)
    # {PLAY_BGM}{MUS_X}: use Emerald's RG version of the song, or drop the music change
    songs = set(re.findall(r"^(MUS_\w+)\s*=", read("charmap.txt"), re.M))
    def bgm(m):
        rg = m.group(1).replace("MUS_", "MUS_RG_", 1)
        return "{PLAY_BGM}{" + rg + "}" if rg in songs else ("{PLAY_BGM}{" + m.group(1) + "}" if m.group(1) in songs else "")
    return re.sub(r"\{PLAY_BGM(?:\}\{| )(MUS_\w+)\}", bgm, body)


def cmd_objects(args):
    frlg = args.frlg
    man = load_manifest()["maps"]
    labels = frlg_labels(frlg)
    em_labels = emerald_labels()
    kanto_gfx = set(re.findall(r"#define (OBJ_EVENT_GFX_KANTO_\w+)", read(KANTO_CONSTANTS)))
    em_localids = set(re.findall(r"#define (LOCALID_\w+)", read("include/constants/map_event_ids.h"))) if os.path.exists("include/constants/map_event_ids.h") else set()
    ported_localids = set()
    for new in man.values():
        ported_localids |= {o.get("local_id") for o in json.loads(read(f"data/maps/{new}/map.json"))["object_events"] if o.get("local_id")}
    em_localids -= ported_localids  # local ids from an earlier run of this tool are ours
    renamed_maps = {f: n for f, n in man.items() if f != n}

    common_texts, common_blocks, flags = {}, [], set()
    stats = {"talk": 0, "item": 0, "trainer": 0, "nurse": 0, "mart": 0, "shared": 0, "fallback": 0, "silent": 0}

    def rename_label(label):
        for f, n in renamed_maps.items():
            if label.startswith(f + "_"):
                return n + label[len(f):]
        return label

    def map_of(label):
        for f in sorted(man, key=len, reverse=True):
            if label.startswith(f + "_"):
                return f
        return None

    def text_label(label, local_texts, mapname):
        """Copy a FRLG text label (and nothing else) and return the name to use for it."""
        if label not in labels:
            return None
        owner = map_of(label)
        if owner is not None:
            new = rename_label(label)
            if man[owner] == mapname:
                local_texts[new] = labels[label]
            else:
                common_texts["Kanto_" + label] = labels[label]
                new = "Kanto_" + label
            return new
        new = "Kanto_" + label
        common_texts[new] = labels[label]
        return new

    def first_text(label, seen=None):
        """First text a script shows, following gotos and calls."""
        seen = seen or set()
        if label in seen or label not in labels or len(seen) > 8:
            return None
        seen.add(label)
        body = labels[label]
        m = re.search(r"^\s*(?:msgbox|message)\s+(\w+)", body, re.M)
        if m and m.group(1) in labels:
            return m.group(1)
        for target in re.findall(r"^\s*(?:goto|call|goto_if_\w+|call_if_\w+)\s+(?:[\w ,]*,\s*)?(\w+)\s*$", body, re.M):
            t = first_text(target, seen)
            if t:
                return t
        return None

    for fname, new in sorted(man.items()):
        fj = json.loads(read(f"{frlg}/data/maps/{fname}/map.json"))
        ej = json.loads(read(f"data/maps/{new}/map.json"))
        fsrc = read(f"{frlg}/data/maps/{fname}/scripts.inc")
        var_gfx = {}
        for var, gfx in re.findall(r"setvar VAR_OBJ_GFX_ID_(\w+), (OBJ_EVENT_GFX_\w+)", fsrc):
            var_gfx.setdefault(f"OBJ_EVENT_GFX_VAR_{var}", gfx)
        objects, scripts, local_texts, marts = [], [], {}, {}
        for idx, o in enumerate(fj["object_events"]):
            if o.get("type") == "clone":
                continue
            gfx = var_gfx.get(o["graphics_id"], o["graphics_id"])
            kgfx = "OBJ_EVENT_GFX_KANTO_" + gfx[len("OBJ_EVENT_GFX_"):] if gfx.startswith("OBJ_EVENT_GFX_") else None
            movement = MOVEMENT_TYPES.get(o["movement_type"], o["movement_type"])
            if kgfx not in kanto_gfx:
                # Pokémon Journals lying on tables have no graphics in FRLG either
                kgfx, movement = "OBJ_EVENT_GFX_KANTO_ITEM_BALL", "MOVEMENT_TYPE_INVISIBLE"
            obj = {}
            local_id = o.get("local_id")
            if local_id:
                if local_id in em_localids:
                    local_id = "LOCALID_KANTO_" + local_id[len("LOCALID_"):]
                obj["local_id"] = local_id
            flag = o.get("flag", "0")
            if flag not in ("0", ""):
                flags.add(flag)
            obj.update({"graphics_id": kgfx, "x": o["x"], "y": o["y"], "elevation": o["elevation"],
                        "movement_type": movement, "movement_range_x": o["movement_range_x"],
                        "movement_range_y": o["movement_range_y"], "trainer_type": "TRAINER_TYPE_NONE",
                        "trainer_sight_or_berry_tree_id": "0", "script": "0x0", "flag": flag})
            script = o.get("script", "0x0")
            body = labels.get(script, "")
            label = rename_label(script) if map_of(script) else f"{new}_EventScript_Object{idx + 1}"
            lines = None
            if script in SHARED_SCRIPTS:
                obj["script"] = script
                stats["shared"] += 1
            elif re.search(r"^\s*finditem\s", body, re.M):
                lines = ["\t" + l.strip() for l in body.strip().splitlines() if l.strip().startswith("finditem")] + ["\tend"]
                stats["item"] += 1
            elif re.search(r"^\s*call (Common_)?EventScript_PkmnCenterNurse\b", body, re.M):
                lid = local_id or str(len(objects) + 1)
                lines = [f"\tsetvar VAR_0x800B, {lid}", "\tcall Common_EventScript_PkmnCenterNurse",
                         "\twaitmessage", "\twaitbuttonpress", "\trelease", "\tend"]
                stats["nurse"] += 1
            elif re.search(r"^\s*pokemart\s+(\w+)", body, re.M):
                items = re.search(r"^\s*pokemart\s+(\w+)", body, re.M).group(1)
                new_items = rename_label(items) if map_of(items) else f"{new}_Items_{items}"
                marts[new_items] = labels[items]
                lines = ["\tlock", "\tfaceplayer", "\tmessage gText_HowMayIServeYou", "\twaitmessage",
                         f"\tpokemart {new_items}", "\tmsgbox gText_PleaseComeAgain, MSGBOX_DEFAULT", "\trelease", "\tend"]
                stats["mart"] += 1
            elif re.search(r"^\s*trainerbattle", body, re.M):
                m = re.search(r"^\s*trainerbattle\w*\s+\w+,\s*(\w+)", body, re.M)
                t = text_label(m.group(1), local_texts, new) if m else None
                if t:
                    lines = [f"\tmsgbox {t}, MSGBOX_NPC", "\tend"]
                stats["trainer"] += 1
            else:
                body_lines = [l.strip() for l in body.strip().splitlines() if l.strip() and not l.strip().startswith("@")]
                simple = body_lines and all(re.match(r"(lock|lockall|faceplayer|release|releaseall|end|waitmessage|waitbuttonpress|closemessage|msgbox \w+(, MSGBOX_\w+)?)$", l) for l in body_lines)
                if simple:
                    lines = []
                    for l in body_lines:
                        m = re.match(r"msgbox (\w+)(.*)", l)
                        if m:
                            t = text_label(m.group(1), local_texts, new)
                            l = f"msgbox {t}{m.group(2)}" if t else ""
                        if l:
                            lines.append("\t" + l)
                    stats["talk"] += 1
                else:
                    t = first_text(script)
                    t = text_label(t, local_texts, new) if t else None
                    if t:
                        lines = [f"\tmsgbox {t}, MSGBOX_NPC", "\tend"]
                        stats["fallback"] += 1
                    else:
                        stats["silent"] += 1
            if lines:
                obj["script"] = label
                script_text = f"{label}::\n" + "\n".join(lines) + "\n"
                if script_text not in scripts:  # several objects can share a script
                    scripts.append(script_text)
            objects.append(obj)

        ej["object_events"] = objects
        write(f"data/maps/{new}/map.json", json.dumps(ej, indent=2) + "\n")

        block = [NPC_BEGIN, ""] + scripts
        for name, items in marts.items():
            block.append(f"\t.align 2\n{name}:\n" + items.rstrip() + "\n")
        for name, text in sorted(local_texts.items()):
            block.append(f"{name}:\n" + fix_text(text).rstrip() + "\n")
        block.append(NPC_END)
        path = f"data/maps/{new}/scripts.inc"
        cur = read(path)
        if NPC_BEGIN in cur:
            cur = cur[:cur.index(NPC_BEGIN)].rstrip("\n") + cur[cur.index(NPC_END) + len(NPC_END):].rstrip("\n")
        write(path, cur.rstrip("\n") + "\n\n" + "\n".join(block) + "\n")

    # Flags, and the ones a new game starts with (FRLG's EventScript_ResetAllMapFlags)
    allocate_flags(flags)
    reset = labels["EventScript_ResetAllMapFlags"]
    start_flags = [f for f in re.findall(r"setflag (FLAG_\w+)", reset) if f in flags]
    out = [GENERATED.replace("//", "@"), "@ Included by data/event_scripts.s.", "",
           "EventScript_ResetKantoMapFlags::"] + [f"\tsetflag {f}" for f in start_flags] + ["\treturn", ""]
    for name, text in sorted(common_texts.items()):
        out.append(f"{name}:\n" + fix_text(text).rstrip() + "\n")
    write(KANTO_SCRIPTS, "\n".join(out) + "\n")
    es = read("data/event_scripts.s")
    inc = f'\t.include "{KANTO_SCRIPTS}"'
    if inc not in es:
        write("data/event_scripts.s", es.replace('\t.include "data/scripts/test_signpost.inc"', '\t.include "data/scripts/test_signpost.inc"\n' + inc, 1))
    ng = read("data/scripts/new_game.inc")
    if "call EventScript_ResetKantoMapFlags" not in ng:
        write("data/scripts/new_game.inc", ng.replace("EventScript_ResetAllMapFlags::\n", "EventScript_ResetAllMapFlags::\n\tcall EventScript_ResetKantoMapFlags\n", 1))
    print("ported objects: " + ", ".join(f"{v} {k}" for k, v in stats.items()) + f"; {len(flags)} flags")


def main():
    if not os.path.exists("include/constants/event_objects.h"):
        sys.exit("run from the pokeemerald root")
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    s = sub.add_parser("sprites"); s.add_argument("--frlg", default="../pokefirered"); s.set_defaults(fn=cmd_sprites)
    o = sub.add_parser("objects"); o.add_argument("--frlg", default="../pokefirered"); o.set_defaults(fn=cmd_objects)
    args = ap.parse_args(); args.fn(args)


if __name__ == "__main__":
    main()
