#!/usr/bin/env python3
"""Port Kanto data from pret/pokefirered into this pokeemerald tree.

    python3 tools/kanto_port/port_kanto.py tilesets --frlg ../pokefirered
    python3 tools/kanto_port/port_kanto.py maps --frlg ../pokefirered            # every map
    python3 tools/kanto_port/port_kanto.py maps PalletTown Route1 --frlg ../pokefirered
    python3 tools/kanto_port/port_kanto.py encounters --frlg ../pokefirered
    python3 tools/kanto_port/port_kanto.py regionmap --frlg ../pokefirered
    python3 tools/kanto_port/port_kanto.py heal --frlg ../pokefirered

Run from the pokeemerald root. Both commands are idempotent.

tilesets: copies every FRLG tileset to data/tilesets/<kind>/kanto_<name>, converts the
          32-bit FRLG metatile attributes to Emerald's 16-bit format (remapping behaviours),
          and adds them to src/data/tilesets/{graphics,metatiles,headers}.h plus tileset_rules_kanto.mk.
          All ported symbols get a "Kanto" prefix (gTileset_KantoPalletTown) so they
          cannot collide with the Hoenn tilesets.
maps:     ports layouts and maps with their warps and connections into gMapGroup_Kanto* groups.
          Maps and layouts that already exist are left alone unless --force is given, so
          edits made afterwards (by hand or in Porymap) survive a re-run.
          NPCs, triggers and signs are stripped (port_npcs.py objects adds the NPCs). Maps and layouts
          whose name already exists in Emerald get a Kanto prefix (see map_report.txt).
encounters: replaces the wild encounter tables of every ported map with FireRed's (LeafGreen's are skipped).
regionmap: converts the Kanto and Sevii Islands region maps to Emerald's 8bpp affine format
          (graphics/pokenav/region_map/<region>/), writes their layouts and the region of each map
          section to src/data/region_map/region_map_layout_kanto.h, and sets the map section positions
          in region_map_sections.json (FRLG grid x + 3, so Kanto sits in the middle of Emerald's wider grid).
heal:     adds FRLG's heal locations and gives the ported towns and Pokémon Centers map scripts that set
          the respawn point and the FLAG_VISITED_* flag that unlocks them as fly destinations. Maps whose
          scripts were edited since they were ported are listed instead of overwritten.
Needs Pillow for regionmap.
"""
import argparse, json, os, re, shutil, struct, sys
from collections import Counter, defaultdict

ROOT = os.getcwd()
PREFIX_SYM = "Kanto"
PREFIX_DIR = "kanto_"
BLOCK_BEGIN = "// BEGIN KANTO PORT: generated by tools/kanto_port/port_kanto.py from pokefirered. Do not edit by hand."
BLOCK_END = "// END KANTO PORT"

# FRLG behaviour name -> Emerald behaviour name. None = no Emerald equivalent (becomes MB_NORMAL,
# listed in the report so the behaviour can be re-implemented later).
BEHAVIOR_MAP = {
    "MB_NORMAL": "MB_NORMAL", "MB_UNUSED_01": "MB_NORMAL", "MB_TALL_GRASS": "MB_TALL_GRASS",
    "MB_CAVE": "MB_CAVE", "MB_RUNNING_DISALLOWED": "MB_NO_RUNNING",
    "MB_INDOOR_ENCOUNTER": "MB_INDOOR_ENCOUNTER", "MB_MOUNTAIN_TOP": "MB_MOUNTAIN_TOP",
    "MB_POND_WATER": "MB_POND_WATER", "MB_FAST_WATER": "MB_INTERIOR_DEEP_WATER",
    "MB_DEEP_WATER": "MB_DEEP_WATER", "MB_WATERFALL": "MB_WATERFALL",
    "MB_OCEAN_WATER": "MB_OCEAN_WATER", "MB_PUDDLE": "MB_PUDDLE",
    "MB_SHALLOW_WATER": "MB_SHALLOW_WATER", "MB_UNDERWATER_BLOCKED_ABOVE": "MB_NO_SURFACING",
    "MB_UNUSED_WATER": "MB_OCEAN_WATER", "MB_CYCLING_ROAD_WATER": "MB_OCEAN_WATER",
    "MB_STRENGTH_BUTTON": None, "MB_SAND": "MB_SAND", "MB_SEAWEED": "MB_SEAWEED",
    "MB_ICE": "MB_ICE", "MB_THIN_ICE": "MB_THIN_ICE", "MB_CRACKED_ICE": "MB_CRACKED_ICE",
    "MB_HOT_SPRINGS": "MB_HOT_SPRINGS", "MB_ROCK_STAIRS": None, "MB_SAND_CAVE": "MB_SAND",
    "MB_SPIN_RIGHT": None, "MB_SPIN_LEFT": None, "MB_SPIN_UP": None, "MB_SPIN_DOWN": None,
    "MB_STOP_SPINNING": None,
    "MB_CAVE_DOOR": "MB_NON_ANIMATED_DOOR", "MB_LADDER": "MB_LADDER",
    "MB_FALL_WARP": "MB_CRACKED_FLOOR_HOLE", "MB_REGULAR_WARP": "MB_AQUA_HIDEOUT_WARP",
    "MB_LAVARIDGE_1F_WARP": "MB_LAVARIDGE_GYM_1F_WARP", "MB_WARP_DOOR": "MB_ANIMATED_DOOR",
    "MB_UP_ESCALATOR": "MB_UP_ESCALATOR", "MB_DOWN_ESCALATOR": "MB_DOWN_ESCALATOR",
    # Diagonal stair warps do not exist in Emerald; nearest is a sideways arrow warp.
    "MB_UP_RIGHT_STAIR_WARP": "MB_EAST_ARROW_WARP", "MB_DOWN_RIGHT_STAIR_WARP": "MB_EAST_ARROW_WARP",
    "MB_UP_LEFT_STAIR_WARP": "MB_WEST_ARROW_WARP", "MB_DOWN_LEFT_STAIR_WARP": "MB_WEST_ARROW_WARP",
    "MB_UNION_ROOM_WARP": None,
    "MB_COUNTER": "MB_COUNTER", "MB_BOOKSHELF": "MB_BOOKSHELF", "MB_POKEMART_SHELF": "MB_SHOP_SHELF",
    "MB_PC": "MB_PC", "MB_REGION_MAP": "MB_REGION_MAP", "MB_TELEVISION": "MB_TELEVISION",
    "MB_CABLE_CLUB_WIRELESS_MONITOR": "MB_WIRELESS_BOX_RESULTS",
    "MB_BATTLE_RECORDS": "MB_CABLE_BOX_RESULTS_1", "MB_QUESTIONNAIRE": "MB_QUESTIONNAIRE",
    "MB_BLUEPRINTS": "MB_BLUEPRINT", "MB_TRASH_BIN": "MB_TRASH_CAN",
    "MB_CYCLING_ROAD_PULL_DOWN": None, "MB_CYCLING_ROAD_PULL_DOWN_GRASS": "MB_TALL_GRASS",
}
SAME_NAME = ["MB_IMPASSABLE_EAST", "MB_IMPASSABLE_WEST", "MB_IMPASSABLE_NORTH", "MB_IMPASSABLE_SOUTH",
    "MB_IMPASSABLE_NORTHEAST", "MB_IMPASSABLE_NORTHWEST", "MB_IMPASSABLE_SOUTHEAST", "MB_IMPASSABLE_SOUTHWEST",
    "MB_JUMP_EAST", "MB_JUMP_WEST", "MB_JUMP_NORTH", "MB_JUMP_SOUTH",
    "MB_WALK_EAST", "MB_WALK_WEST", "MB_WALK_NORTH", "MB_WALK_SOUTH",
    "MB_SLIDE_EAST", "MB_SLIDE_WEST", "MB_SLIDE_NORTH", "MB_SLIDE_SOUTH", "MB_TRICK_HOUSE_PUZZLE_8_FLOOR",
    "MB_EASTWARD_CURRENT", "MB_WESTWARD_CURRENT", "MB_NORTHWARD_CURRENT", "MB_SOUTHWARD_CURRENT",
    "MB_EAST_ARROW_WARP", "MB_WEST_ARROW_WARP", "MB_NORTH_ARROW_WARP", "MB_SOUTH_ARROW_WARP"]
BEHAVIOR_MAP.update({n: n for n in SAME_NAME})
# Emerald behaviours that can trigger wild encounters (TILE_FLAG_HAS_ENCOUNTERS).
EM_ENCOUNTER = {"MB_TALL_GRASS", "MB_LONG_GRASS", "MB_DEEP_SAND", "MB_CAVE", "MB_INDOOR_ENCOUNTER",
    "MB_POND_WATER", "MB_INTERIOR_DEEP_WATER", "MB_DEEP_WATER", "MB_OCEAN_WATER", "MB_SEAWEED",
    "MB_ASHGRASS", "MB_FOOTPRINTS", "MB_SEAWEED_NO_SURFACING"}


def read(p):
    with open(p, encoding="utf-8") as f:
        return f.read()

def write(p, s):
    if os.path.dirname(p):
        os.makedirs(os.path.dirname(p), exist_ok=True)
    with open(p, "w", encoding="utf-8", newline="\n") as f:
        f.write(s)

def emerald_behaviors():
    body = re.search(r"enum\s*\{(.*?)\}", read("include/constants/metatile_behaviors.h"), re.S).group(1)
    body = re.sub(r"//.*", "", body)
    names = [n.strip() for n in body.split(",") if n.strip()]
    return {n: i for i, n in enumerate(names)}

def frlg_behaviors(frlg):
    out = {}
    for m in re.finditer(r"#define\s+(MB_\w+)\s+(0x[0-9A-Fa-f]+)", read(f"{frlg}/include/constants/metatile_behaviors.h")):
        out[int(m.group(2), 16)] = m.group(1)
    return out

def convert_attributes(data, em, fr, tileset, report):
    out = bytearray()
    for i, (v,) in enumerate(struct.iter_unpack("<I", data)):
        beh, enc, layer = v & 0x1FF, (v >> 24) & 7, (v >> 29) & 3
        name = fr.get(beh)
        target = BEHAVIOR_MAP.get(name) if name else None
        if target is None:
            target = "MB_NORMAL"
        final = target
        # FRLG stores "has land encounters" as a separate attribute; Emerald derives it from the behaviour.
        lost = ""
        if enc == 1 and target not in EM_ENCOUNTER:
            if target in ("MB_NORMAL", "MB_SAND"):
                final = "MB_CAVE" if target == "MB_NORMAL" else "MB_DEEP_SAND"
            else:
                lost = " (land encounters LOST)"
        src = name or ("MB_NORMAL" if beh == 0 else f"unknown 0x{beh:02X}")
        if BEHAVIOR_MAP.get(name) is None and beh != 0 and final == "MB_NORMAL":
            lost += " (no Emerald equivalent)"
        if final != src or lost:
            report[(src + (" + land encounters" if enc == 1 else ""), final + lost)].append(f"{tileset}:{i}")
        target = final
        out += struct.pack("<H", em[target] | (layer << 12))
    return bytes(out)

def rename_symbols(text):
    text = re.sub(r"\b(gTileset|gTilesetTiles|gTilesetPalettes|gMetatiles|gMetatileAttributes)_(\w+)",
                  lambda m: f"{m.group(1)}_{PREFIX_SYM}{m.group(2)}", text)
    return re.sub(r"data/tilesets/(primary|secondary)/", lambda m: f"data/tilesets/{m.group(1)}/{PREFIX_DIR}", text)

def insert_once(path, anchor, line, after=True):
    s = read(path)
    if line in s:
        return
    if anchor not in s:
        sys.exit(f"anchor {anchor!r} not found in {path}")
    s = s.replace(anchor, anchor + "\n" + line if after else line + "\n" + anchor, 1)
    write(path, s)

def cmd_tilesets(args):
    frlg = args.frlg
    em, fr = emerald_behaviors(), frlg_behaviors(frlg)
    report = defaultdict(list)
    count = 0
    for kind in ("primary", "secondary"):
        src_root = f"{frlg}/data/tilesets/{kind}"
        for name in sorted(os.listdir(src_root)):
            src, dst = f"{src_root}/{name}", f"data/tilesets/{kind}/{PREFIX_DIR}{name}"
            if not os.path.isdir(src):
                continue
            os.makedirs(dst, exist_ok=True)
            for dirpath, _, files in os.walk(src):
                rel = os.path.relpath(dirpath, src)
                for f in files:
                    if not f.endswith((".png", ".pal", ".bin")):
                        continue  # skip build products
                    os.makedirs(os.path.join(dst, rel), exist_ok=True)
                    s, d = os.path.join(dirpath, f), os.path.join(dst, rel, f)
                    if f == "metatile_attributes.bin" and rel == ".":
                        with open(s, "rb") as fh:
                            conv = convert_attributes(fh.read(), em, fr, f"{kind}/{name}", report)
                        with open(d, "wb") as fh:
                            fh.write(conv)
                    else:
                        shutil.copyfile(s, d)
            count += 1

    # Porymap only reads the standard graphics.h / metatiles.h / headers.h, so the Kanto
    # definitions go into those files, inside a marked block that is replaced on every run.
    gfx = read(f"{frlg}/src/data/tilesets/graphics.h")
    # A few tilesets are also used outside the overworld in FRLG, so their graphics live in src/graphics.c.
    shared = re.findall(r"^const u16 gTilesetPalettes_\w+\[\]\[16\] =\n\{.*?\n\};\n|^const u32 gTilesetTiles_\w+\[\] = INCBIN_U32\(.*?\);\n",
                        read(f"{frlg}/src/graphics.c"), re.S | re.M)
    gfx += "\n" + "\n".join(shared)
    met = rename_symbols(read(f"{frlg}/src/data/tilesets/metatiles.h"))
    met = re.sub(r"const u32 (gMetatileAttributes_\w+\[\]) = INCBIN_U32", r"const u16 \1 = INCBIN_U16", met)
    heads = rename_symbols(read(f"{frlg}/src/data/tilesets/headers.h"))
    # The tile animations are ported in src/tileset_anims.c with a Kanto prefix.
    heads = re.sub(r"\.callback = InitTilesetAnim_(\w+),", r".callback = InitTilesetAnim_Kanto\1,", heads)
    for fname, body in (("graphics.h", rename_symbols(gfx)), ("metatiles.h", met), ("headers.h", heads)):
        path = f"src/data/tilesets/{fname}"
        block = f"{BLOCK_BEGIN}\n\n{body.strip()}\n\n{BLOCK_END}\n"
        cur = read(path)
        if BLOCK_BEGIN in cur:
            cur = cur[:cur.index(BLOCK_BEGIN)] + block + cur[cur.index(BLOCK_END) + len(BLOCK_END):].lstrip("\n")
        else:
            cur = cur.rstrip("\n") + "\n\n" + block
        write(path, cur)
        # Earlier versions of this tool used separate kanto_*.h files.
        old = f"src/data/tilesets/kanto_{fname}"
        if os.path.exists(old):
            os.remove(old)
    ts = read("src/tilesets.c")
    write("src/tilesets.c", re.sub(r'#include "data/tilesets/kanto_\w+\.h"\n', "", ts))

    rules = rename_symbols(read(f"{frlg}/tileset_rules.mk")).replace(
        "$(TILESETGFXDIR)/primary/", f"$(TILESETGFXDIR)/primary/{PREFIX_DIR}").replace(
        "$(TILESETGFXDIR)/secondary/", f"$(TILESETGFXDIR)/secondary/{PREFIX_DIR}")
    rules = "\n".join(l for l in rules.splitlines() if not l.startswith("TILESETGFXDIR"))
    write("tileset_rules_kanto.mk", "# Generated by tools/kanto_port/port_kanto.py from pokefirered.\n" + rules + "\n")

    insert_once("Makefile", "include graphics_file_rules.mk", "include tileset_rules_kanto.mk")
    lines = ["Metatile behaviour conversions (FRLG -> Emerald). Entries are tileset:metatile index.", ""]
    for (a, b), where in sorted(report.items(), key=lambda kv: -len(kv[1])):
        by_ts = Counter(w.split(":")[0] for w in where)
        lines.append(f"{a} -> {b}: {len(where)} metatiles")
        lines.append("    " + ", ".join(f"{t} ({n})" for t, n in sorted(by_ts.items())))
    write("tools/kanto_port/behavior_report.txt", "\n".join(lines) + "\n")
    print(f"ported {count} tilesets; see tools/kanto_port/behavior_report.txt")

MANIFEST = "tools/kanto_port/manifest.json"
BATTLE_SCENES = {"MAP_BATTLE_SCENE_NORMAL", "MAP_BATTLE_SCENE_GYM"}  # FRLG scenes that also exist in Emerald

# FRLG map sections whose name Emerald uses for its own (Hoenn) location.
MAPSEC_MAP = {"MAPSEC_NAVEL_ROCK": "MAPSEC_NAVEL_ROCK_FRLG", "MAPSEC_ALTERING_CAVE": "MAPSEC_ALTERING_CAVE_FRLG",
              "MAPSEC_BIRTH_ISLAND": "MAPSEC_BIRTH_ISLAND_FRLG"}

def load_manifest():
    if os.path.exists(MANIFEST):
        return json.loads(read(MANIFEST))
    return {"maps": {}, "layouts": {}}

def const_to_kanto(const, prefix):
    return f"{prefix}KANTO_{const[len(prefix):]}"

def cmd_maps(args):
    """Port FRLG maps (all of them unless names are given) with their layouts, warps and connections."""
    frlg = args.frlg
    fgroups = json.loads(read(f"{frlg}/data/maps/map_groups.json"))
    flayouts = {l["id"]: l for l in json.loads(read(f"{frlg}/data/layouts/layouts.json"))["layouts"] if l}
    groups = json.loads(read("data/maps/map_groups.json"))
    lj = json.loads(read("data/layouts/layouts.json"))
    manifest = load_manifest()
    songs = set(re.findall(r"#define (MUS_\w+)", read("include/constants/songs.h")))

    # Anything not created by this tool is "Hoenn" and must not be overwritten.
    kanto_groups = [g for g in groups["group_order"] if g.startswith("gMapGroup_Kanto")]
    hoenn_maps = {m for g in groups["group_order"] if g not in kanto_groups for m in groups[g]}
    ported_layout_ids = set(manifest["layouts"].values())
    hoenn_layouts = [l for l in lj["layouts"] if l and l["id"] not in ported_layout_ids]
    hoenn_layout_ids = {l["id"] for l in hoenn_layouts}
    hoenn_layout_names = {l["name"] for l in hoenn_layouts}
    hoenn_layout_dirs = {os.path.dirname(l["blockdata_filepath"]) for l in hoenn_layouts}

    # The link maps (Union Room, Trade Center...) already exist in Emerald and its link code uses them.
    skipped = set(fgroups.get("gMapGroup_Link", []))
    fmaps = {}
    for g in fgroups["group_order"]:
        for name in fgroups[g]:
            if name not in skipped:
                fmaps[name] = (g, json.loads(read(f"{frlg}/data/maps/{name}/map.json")))
    wanted = args.names or list(fmaps)
    for n in wanted:
        if n not in fmaps:
            sys.exit(f"{n}: not a portable FRLG map")

    # Names that exist in both games get a Kanto prefix. Decide this for every FRLG map so that
    # warps and connections to maps ported later still resolve to the right constant.
    map_name, map_id = {}, {}
    for name, (_, j) in fmaps.items():
        clash = name in hoenn_maps
        map_name[name] = PREFIX_SYM + name if clash else name
        map_id[j["id"]] = const_to_kanto(j["id"], "MAP_") if clash else j["id"]

    notes = []
    def port_layout(lid):
        fl = flayouts[lid]
        ldir = os.path.dirname(fl["blockdata_filepath"])
        clash = lid in hoenn_layout_ids or fl["name"] in hoenn_layout_names or ldir in hoenn_layout_dirs
        new_id = const_to_kanto(lid, "LAYOUT_") if clash else lid
        new_dir = f"data/layouts/{PREFIX_SYM}{os.path.basename(ldir)}" if clash else ldir
        entry = {
            "id": new_id, "name": (PREFIX_SYM if clash else "") + fl["name"],
            "width": fl["width"], "height": fl["height"],
            "primary_tileset": rename_symbols(fl["primary_tileset"]),
            "secondary_tileset": rename_symbols(fl["secondary_tileset"]),
            "border_filepath": f"{new_dir}/border.bin", "blockdata_filepath": f"{new_dir}/map.bin",
        }
        if os.path.exists(entry["blockdata_filepath"]) and not args.force:
            manifest["layouts"][lid] = new_id
            return new_id  # already ported; may have been edited since (e.g. in Porymap)
        os.makedirs(new_dir, exist_ok=True)
        shutil.copyfile(f"{frlg}/{fl['blockdata_filepath']}", entry["blockdata_filepath"])
        with open(f"{frlg}/{fl['border_filepath']}", "rb") as fh:
            border = fh.read()
        bw, bh = fl.get("border_width", 2), fl.get("border_height", 2)
        if (bw, bh) != (2, 2):
            # Emerald borders are always 2x2: keep the top-left 2x2 of the FRLG border.
            border = b"".join(border[(r * bw + c) * 2:(r * bw + c) * 2 + 2] for r in range(2) for c in range(2))
            notes.append(f"{new_id}: {bw}x{bh} border cropped to 2x2")
        with open(entry["border_filepath"], "wb") as fh:
            fh.write(border)
        existing = next((i for i, l in enumerate(lj["layouts"]) if l and l["id"] == new_id), None)
        if existing is None:
            lj["layouts"].append(entry)
        else:
            lj["layouts"][existing] = entry
        manifest["layouts"][lid] = new_id
        return new_id

    done_layouts = {}
    skipped_existing = []
    es = read("data/event_scripts.s")
    for name in wanted:
        fgroup, fj = fmaps[name]
        new_name = map_name[name]
        if fj["layout"] not in done_layouts:
            done_layouts[fj["layout"]] = port_layout(fj["layout"])
        if os.path.exists(f"data/maps/{new_name}/map.json") and not args.force:
            skipped_existing.append(new_name)
            continue  # already ported; may have been edited since (e.g. in Porymap)
        m = dict(fj)
        m["id"], m["name"], m["layout"] = map_id[fj["id"]], new_name, done_layouts[fj["layout"]]
        m.pop("floor_number", None)
        m.pop("connections_no_include", None)
        rg = fj["music"].replace("MUS_", "MUS_RG_", 1)
        m["music"] = rg if rg in songs else fj["music"]
        m["region_map_section"] = MAPSEC_MAP.get(fj["region_map_section"], fj["region_map_section"])
        if m["music"] not in songs:
            notes.append(f"{new_name}: music {fj['music']} not in Emerald")
        if fj["battle_scene"] not in BATTLE_SCENES:
            m["battle_scene"] = "MAP_BATTLE_SCENE_NORMAL"
        m["connections"] = None if args.no_connections or not fj["connections"] else [
            dict(c, map=map_id.get(c["map"], c["map"])) for c in fj["connections"]]
        m["warp_events"] = [] if args.no_warps else [
            dict(w, dest_map=map_id.get(w["dest_map"], w["dest_map"])) for w in fj["warp_events"]]
        # NPCs are added by port_npcs.py; triggers and signs need their scripts ported first.
        m["object_events"], m["coord_events"], m["bg_events"] = [], [], []
        write(f"data/maps/{new_name}/map.json", json.dumps(m, indent=2) + "\n")
        scripts = f"data/maps/{new_name}/scripts.inc"
        if not os.path.exists(scripts):
            write(scripts, f"{new_name}_MapScripts::\n\t.byte 0\n")

        group = "gMapGroup_" + PREFIX_SYM + fgroup[len("gMapGroup_"):]
        for g in list(groups["group_order"]):  # move out of any other Kanto group (e.g. the old gMapGroup_Kanto)
            if g.startswith("gMapGroup_Kanto") and g != group and new_name in groups[g]:
                groups[g].remove(new_name)
                if not groups[g]:
                    groups["group_order"].remove(g)
                    del groups[g]
        if group not in groups:
            groups["group_order"].append(group)
            groups[group] = []
        if new_name not in groups[group]:
            groups[group].append(new_name)
        manifest["maps"][name] = new_name

        inc = f'\t.include "data/maps/{new_name}/scripts.inc"'
        if inc not in es:
            last = [l for l in es.splitlines() if re.match(r'\t\.include "data/maps/.*/scripts\.inc"', l)][-1]
            es = es.replace(last, last + "\n" + inc, 1)

    # Keep each Kanto group in FRLG's order so map numbers are stable however the tool was run.
    for fg in fgroups["group_order"]:
        g = "gMapGroup_" + PREFIX_SYM + fg[len("gMapGroup_"):]
        if g in groups:
            order = [map_name[n] for n in fgroups[fg] if n in map_name]
            groups[g].sort(key=order.index)
    write("data/event_scripts.s", es)
    write("data/layouts/layouts.json", json.dumps(lj, indent=2) + "\n")
    write("data/maps/map_groups.json", json.dumps(groups, indent=2) + "\n")
    write(MANIFEST, json.dumps(manifest, indent=2, sort_keys=True) + "\n")
    if len(skipped_existing) < len(wanted):  # keep the last report when nothing was ported
        renamed = sorted(f"{a} -> {b}" for a, b in manifest["maps"].items() if a != b)
        write("tools/kanto_port/map_report.txt", "\n".join(
            ["Maps renamed because the name already exists in Emerald:"] + ["    " + r for r in renamed]
            + ["", "FRLG link maps not ported (Emerald's own are used):"] + ["    " + n for n in sorted(skipped)]
            + ["", "Notes:"] + ["    " + n for n in sorted(set(notes))]) + "\n")
    print(f"ported {len(wanted) - len(skipped_existing)} maps, left {len(skipped_existing)} existing maps untouched "
          f"(use --force to overwrite them); see tools/kanto_port/map_report.txt")

def ported_map_ids(frlg):
    """FRLG map constant -> constant of the ported map, for every map in the manifest."""
    out = {}
    for fname, new in load_manifest()["maps"].items():
        fid = json.loads(read(f"{frlg}/data/maps/{fname}/map.json"))["id"]
        out[fid] = json.loads(read(f"data/maps/{new}/map.json"))["id"]
    return out

WILD_JSON = "src/data/wild_encounters.json"

def cmd_encounters(args):
    """Port FireRed's wild encounter tables for every ported map (LeafGreen's are skipped)."""
    frlg = args.frlg
    ids = ported_map_ids(frlg)
    fgroup = json.loads(read(f"{frlg}/src/data/wild_encounters.json"))["wild_encounter_groups"][0]
    wj = json.loads(read(WILD_JSON))
    group = next(g for g in wj["wild_encounter_groups"] if g["label"] == "gWildMonHeaders")
    for a, b in zip(fgroup["fields"], group["fields"]):
        if a != b:
            sys.exit(f"FRLG encounter field {a['type']} differs from Emerald's")
    kanto = set(ids.values())
    group["encounters"] = [e for e in group["encounters"] if e["map"] not in kanto]
    missing, count, seen = [], 0, Counter()
    for e in fgroup["encounters"]:
        if not e["base_label"].endswith("_FireRed"):
            continue
        if e["map"] not in ids:
            missing.append(e["map"])
            continue
        new = dict(e, map=ids[e["map"]])
        # Labels follow Emerald's style (gRoute101); a map with several tables (Altering Cave) gets _2, _3...
        base = "g" + e["base_label"][1:-len("_FireRed")]
        base = re.sub(r"_\d+$", "", base)
        seen[base] += 1
        new["base_label"] = base if seen[base] == 1 else f"{base}_{seen[base]}"
        if new["base_label"] in {x.get("base_label") for x in group["encounters"]}:
            new["base_label"] = "gKanto" + new["base_label"][1:]
        group["encounters"].append(new)
        count += 1
    write(WILD_JSON, json.dumps(wj, indent=2) + "\n")
    print(f"ported {count} FireRed encounter tables" + (f"; maps not ported: {', '.join(missing)}" if missing else ""))

# ---------------------------------------------------------------------------------------------
# Region map

REGIONS = ["kanto", "sevii_123", "sevii_45", "sevii_67"]  # FRLG region maps, in FRLG's order
REGION_ENUM = {"kanto": "REGION_KANTO", "sevii_123": "REGION_SEVII_123", "sevii_45": "REGION_SEVII_45", "sevii_67": "REGION_SEVII_67"}
RM_GFX = "graphics/pokenav/region_map"
FR_MAP_W, FR_MAP_H = 22, 15       # FRLG region map grid
EM_MAP_W, EM_MAP_H = 28, 15       # Emerald region map grid
RM_X_OFFSET = 3                   # FRLG grid x -> Emerald grid x (both are drawn at the same screen tile)
FR_GRID_ROW = 4                   # FRLG draws its grid from screen tile row 4, Emerald from row 2
EM_GRID_ROW = 2
# Where FRLG puts the player for map sections that are not on the map itself
# (GetPlayerPositionOnRegionMap_HandleOverrides), in FRLG grid coordinates.
RM_POSITION_OVERRIDES = {
    "MAPSEC_KANTO_SAFARI_ZONE": (12, 12), "MAPSEC_SILPH_CO": (14, 6), "MAPSEC_POKEMON_MANSION": (4, 14),
    "MAPSEC_POKEMON_TOWER": (18, 6), "MAPSEC_POWER_PLANT": (18, 4), "MAPSEC_S_S_ANNE": (14, 9),
    "MAPSEC_POKEMON_LEAGUE": (2, 3), "MAPSEC_ROCKET_HIDEOUT": (11, 6), "MAPSEC_UNDERGROUND_PATH": (14, 7),
    "MAPSEC_UNDERGROUND_PATH_2": (12, 6), "MAPSEC_BIRTH_ISLAND": (18, 13), "MAPSEC_NAVEL_ROCK": (10, 8),
    "MAPSEC_TRAINER_TOWER_2": (5, 6), "MAPSEC_MT_EMBER": (2, 3), "MAPSEC_BERRY_FOREST": (14, 12),
    "MAPSEC_PATTERN_BUSH": (17, 3), "MAPSEC_ROCKET_WAREHOUSE": (17, 11), "MAPSEC_DILFORD_CHAMBER": (9, 12),
    "MAPSEC_LIPTOO_CHAMBER": (9, 12), "MAPSEC_MONEAN_CHAMBER": (9, 12), "MAPSEC_RIXY_CHAMBER": (9, 12),
    "MAPSEC_SCUFIB_CHAMBER": (9, 12), "MAPSEC_TANOBY_CHAMBERS": (9, 12), "MAPSEC_VIAPOIS_CHAMBER": (9, 12),
    "MAPSEC_WEEPTH_CHAMBER": (9, 12), "MAPSEC_DOTTED_HOLE": (16, 8), "MAPSEC_VIRIDIAN_FOREST": (4, 6),
    "MAPSEC_SPECIAL_AREA": (11, 6),  # Celadon Dept. Store
    # Not placed by FRLG at all; put them where their entrances are.
    "MAPSEC_THREE_ISLE_PATH": (18, 13), "MAPSEC_EMBER_SPA": (2, 4), "MAPSEC_TANOBY_KEY": (6, 11),
}

def read_jasc(path):
    lines = read(path).split("\n")
    return [tuple(int(v) for v in l.split()) for l in lines[3:] if l.strip()]

def render_frlg_region_map(frlg, name):
    """Render an FRLG region map (4bpp tiles + text tilemap) to rows of RGB pixels (None = transparent)."""
    from PIL import Image
    tiles = Image.open(f"{frlg}/graphics/region_map/region_map.png")
    pal = read_jasc(f"{frlg}/graphics/region_map/region_map.pal")
    tw = tiles.size[0] // 8
    px = tiles.load()
    with open(f"{frlg}/graphics/region_map/{name}.bin", "rb") as fh:
        tmap = struct.unpack("<600H", fh.read())
    out = [[None] * 240 for _ in range(160)]
    for i, e in enumerate(tmap):
        ti, hf, vf, pl = e & 0x3FF, e & 0x400, e & 0x800, e >> 12
        tx, ty = (ti % tw) * 8, (ti // tw) * 8
        for y in range(8):
            for x in range(8):
                sx, sy = (7 - x if hf else x), (7 - y if vf else y)
                c = px[tx + sx, ty + sy] & 15 if ty + sy < tiles.size[1] else 0
                out[(i // 30) * 8 + y][(i % 30) * 8 + x] = pal[pl * 16 + c][:3] if c else None
    return out

def parse_frlg_layout(frlg, name):
    """FRLG region map layout -> (map layer, dungeon layer), each [y][x] of MAPSEC names."""
    src = read(f"{frlg}/src/data/region_map/region_map_layout_{name}.h")
    secs = [MAPSEC_MAP.get(m, m) for m in re.findall(r"\bMAPSEC_\w+", src)]
    n = FR_MAP_W * FR_MAP_H
    if len(secs) != 2 * n:
        sys.exit(f"unexpected layout size in region_map_layout_{name}.h")
    grid = lambda l: [l[y * FR_MAP_W:(y + 1) * FR_MAP_W] for y in range(FR_MAP_H)]
    return grid(secs[:n]), grid(secs[n:])

def convert_region_map_gfx(frlg, name):
    """Write the FRLG region map as an Emerald 8bpp affine background (tiles, 64x64 tilemap, palette)."""
    from PIL import Image
    img = render_frlg_region_map(frlg, name)
    # FRLG covers the transparent edge columns with a separate map edge layer; Emerald has no such layer,
    # so draw them in the white of FRLG's map border instead.
    img = [[(255, 255, 255) if c is None else c for c in row] for row in img]
    shift = FR_GRID_ROW - EM_GRID_ROW
    colors = []
    for row in img:
        for c in row:
            if c is not None and c not in colors:
                colors.append(c)
    # Emerald loads the region map palette into BG palettes 7-9 (indices 112-159).
    # Colour 0 of each of those palettes is left unused, like Emerald's own map.
    slots = [i for i in range(113, 160) if i % 16]
    if len(colors) > len(slots):
        sys.exit(f"{name}: {len(colors)} colours do not fit in the region map palette")
    index = {c: slots[i] for i, c in enumerate(colors)}
    tiles, tile_ids = [bytes(64)], {bytes(64): 0}
    tilemap = bytearray(64 * 64)
    for r in range(20):
        for c in range(30):
            sr = r + shift
            if sr >= 20:
                continue
            t = bytes(0 if img[sr * 8 + y][c * 8 + x] is None else index[img[sr * 8 + y][c * 8 + x]]
                      for y in range(8) for x in range(8))
            if t not in tile_ids:
                tile_ids[t] = len(tiles)
                tiles.append(t)
            tilemap[r * 64 + c] = tile_ids[t]
    if len(tiles) > 256:
        sys.exit(f"{name}: {len(tiles)} tiles do not fit in an affine background")
    rows = (len(tiles) + 15) // 16
    sheet = Image.new("P", (128, rows * 8))
    flat = [0] * (256 * 3)
    for c, i in index.items():
        flat[i * 3:i * 3 + 3] = c
    sheet.putpalette(flat)
    spx = sheet.load()
    for i, t in enumerate(tiles):
        for y in range(8):
            for x in range(8):
                spx[(i % 16) * 8 + x, (i // 16) * 8 + y] = t[y * 8 + x]
    out = f"{RM_GFX}/{name}"
    os.makedirs(out, exist_ok=True)
    sheet.save(f"{out}/map.png", bits=8)
    with open(f"{out}/map.bin", "wb") as fh:
        fh.write(bytes(tilemap))
    # The Pokédex area screen shows the same map on a regular (32x32, 16-bit entries) 8bpp background.
    with open(f"{out}/dex.bin", "wb") as fh:
        fh.write(b"".join(struct.pack("<H", tilemap[r * 64 + c]) for r in range(32) for c in range(32)))
    pal = [(0, 0, 0)] * 48
    for c, i in index.items():
        pal[i - 112] = c
    write(f"{out}/map.pal", "JASC-PAL\n0100\n48\n" + "".join(f"{r} {g} {b}\n" for r, g, b in pal))
    return len(tiles)

def cmd_regionmap(args):
    """Port the FRLG region maps: graphics, layouts, map section positions and regions."""
    frlg = args.frlg
    ftable = [m for m in json.loads(read(f"{frlg}/src/data/region_map/region_map_sections.json"))["map_sections"]]
    path = "src/data/region_map/region_map_sections.json"
    ej = json.loads(read(path))
    eids = [m["id"] for m in ej["map_sections"]]
    start = eids.index("MAPSEC_PALLET_TOWN")
    fstart = [m["id"] for m in ftable].index("MAPSEC_PALLET_TOWN")
    kanto = ftable[fstart:]
    for i, fm in enumerate(kanto):  # Emerald mirrors FRLG's Kanto map sections in the same order
        if eids[start + i] != MAPSEC_MAP.get(fm["id"], fm["id"]):
            sys.exit(f"map section mismatch: {eids[start + i]} vs {fm['id']}")

    layouts = {n: parse_frlg_layout(frlg, n) for n in REGIONS}
    region_of, first_pos = {}, {}
    for n in REGIONS:
        for layer in layouts[n]:
            for y, row in enumerate(layer):
                for x, sec in enumerate(row):
                    if sec != "MAPSEC_NONE":
                        region_of.setdefault(sec, n)
                        first_pos.setdefault(sec, (x, y))
    rm = read(f"{frlg}/src/region_map.c")
    sevii = re.search(r"sSeviiMapsecs\[3\]\[30\] = \{(.*?)\n\};", rm, re.S).group(1)
    for n, block in zip(REGIONS[1:], re.findall(r"\{(.*?)\}", sevii, re.S)):
        for sec in re.findall(r"MAPSEC_\w+", block):
            if sec != "MAPSEC_NONE":
                region_of.setdefault(MAPSEC_MAP.get(sec, sec), n)

    # Map section positions, in Emerald grid coordinates.
    for i, fm in enumerate(kanto):
        sec = eids[start + i]
        em = ej["map_sections"][start + i]
        if fm.get("width", 0) and (fm.get("x", 0) or fm.get("y", 0)):
            x, y, w, h = fm["x"], fm["y"], fm["width"], fm["height"]
        elif fm["id"] in RM_POSITION_OVERRIDES or sec in first_pos:
            (x, y), w, h = RM_POSITION_OVERRIDES.get(fm["id"]) or first_pos[sec], 1, 1
        else:
            continue
        for k in ("x", "y", "width", "height"):
            em.pop(k, None)
        em.update(x=x + RM_X_OFFSET, y=y, width=w, height=h)
    write(path, json.dumps(ej, indent=2, ensure_ascii=False) + "\n")

    lines = ["// Generated by tools/kanto_port/port_kanto.py regionmap from pokefirered. Do not edit by hand.", ""]
    for n in REGIONS:
        lines.append(f"static const mapsec_u8_t sRegionMap_MapSectionLayout_{''.join(p.capitalize() for p in n.split('_'))}[MAP_HEIGHT][MAP_WIDTH] = {{")
        for row in layouts[n][0]:
            cells = ["MAPSEC_NONE"] * RM_X_OFFSET + row
            cells += ["MAPSEC_NONE"] * (EM_MAP_W - len(cells))
            lines.append("    {" + ", ".join(cells) + "},")
        lines.append("};")
        lines.append("")
    lines.append("// Which region map each Kanto map section is drawn on.")
    lines.append("static const u8 sKantoMapSecRegions[KANTO_MAPSEC_COUNT] = {")
    for i, fm in enumerate(kanto):
        sec = eids[start + i]
        lines.append(f"    [{sec} - KANTO_MAPSEC_START] = {REGION_ENUM[region_of.get(sec, 'kanto')]},")
    lines.append("};")
    write("src/data/region_map/region_map_layout_kanto.h", "\n".join(lines) + "\n")

    counts = {n: convert_region_map_gfx(frlg, n) for n in REGIONS}
    print("ported region maps: " + ", ".join(f"{n} ({c} tiles)" for n, c in counts.items()))

# ---------------------------------------------------------------------------------------------
# Heal locations and fly destinations

# FRLG world map flags that unlock a fly destination -> the Emerald flag used for it.
FLY_FLAGS = {
    "FLAG_WORLD_MAP_PALLET_TOWN": "FLAG_VISITED_PALLET_TOWN",
    "FLAG_WORLD_MAP_VIRIDIAN_CITY": "FLAG_VISITED_VIRIDIAN_CITY",
    "FLAG_WORLD_MAP_PEWTER_CITY": "FLAG_VISITED_PEWTER_CITY",
    "FLAG_WORLD_MAP_CERULEAN_CITY": "FLAG_VISITED_CERULEAN_CITY",
    "FLAG_WORLD_MAP_LAVENDER_TOWN": "FLAG_VISITED_LAVENDER_TOWN",
    "FLAG_WORLD_MAP_VERMILION_CITY": "FLAG_VISITED_VERMILION_CITY",
    "FLAG_WORLD_MAP_CELADON_CITY": "FLAG_VISITED_CELADON_CITY",
    "FLAG_WORLD_MAP_FUCHSIA_CITY": "FLAG_VISITED_FUCHSIA_CITY",
    "FLAG_WORLD_MAP_CINNABAR_ISLAND": "FLAG_VISITED_CINNABAR_ISLAND",
    "FLAG_WORLD_MAP_INDIGO_PLATEAU_EXTERIOR": "FLAG_VISITED_INDIGO_PLATEAU",
    "FLAG_WORLD_MAP_SAFFRON_CITY": "FLAG_VISITED_SAFFRON_CITY",
    "FLAG_WORLD_MAP_ROUTE4_POKEMON_CENTER_1F": "FLAG_VISITED_ROUTE4_POKEMON_CENTER",
    "FLAG_WORLD_MAP_ROUTE10_POKEMON_CENTER_1F": "FLAG_VISITED_ROUTE10_POKEMON_CENTER",
    "FLAG_WORLD_MAP_ONE_ISLAND": "FLAG_VISITED_ONE_ISLAND",
    "FLAG_WORLD_MAP_TWO_ISLAND": "FLAG_VISITED_TWO_ISLAND",
    "FLAG_WORLD_MAP_THREE_ISLAND": "FLAG_VISITED_THREE_ISLAND",
    "FLAG_WORLD_MAP_FOUR_ISLAND": "FLAG_VISITED_FOUR_ISLAND",
    "FLAG_WORLD_MAP_FIVE_ISLAND": "FLAG_VISITED_FIVE_ISLAND",
    "FLAG_WORLD_MAP_SIX_ISLAND": "FLAG_VISITED_SIX_ISLAND",
    "FLAG_WORLD_MAP_SEVEN_ISLAND": "FLAG_VISITED_SEVEN_ISLAND",
}
HEAL_JSON = "src/data/heal_locations.json"
NPC_BLOCK_BEGIN = "@ BEGIN KANTO NPCS"

def cmd_heal(args):
    """Port FRLG's heal locations, and the map scripts that set the respawn point and unlock fly destinations."""
    frlg = args.frlg
    ids = ported_map_ids(frlg)
    man = load_manifest()["maps"]
    fheal = json.loads(read(f"{frlg}/src/data/heal_locations.json"))["heal_locations"]
    hj = json.loads(read(HEAL_JSON))
    new_ids = {h["id"] for h in fheal}
    hj["heal_locations"] = [h for h in hj["heal_locations"] if h["id"] not in new_ids]
    for h in fheal:
        # Emerald respawns the player outside the Pokémon Center, so the respawn map and nurse are not needed.
        hj["heal_locations"].append({"id": h["id"], "map": ids[h["map"]], "x": h["x"], "y": h["y"]})
    write(HEAL_JSON, json.dumps(hj, indent=2, ensure_ascii=False) + "\n")

    done, skipped = [], []
    for fname, new in sorted(man.items()):
        src = read(f"{frlg}/data/maps/{fname}/scripts.inc")
        cmds = [f"\tsetflag {FLY_FLAGS[f]}" for f in re.findall(r"setworldmapflag (\w+)", src) if f in FLY_FLAGS]
        if fname.endswith("_PokemonCenter_1F") or fname == "PalletTown_PlayersHouse_2F":
            cmds += [f"\tsetrespawn {h}" for h in re.findall(r"setrespawn (HEAL_LOCATION_\w+)", src)]
        if not cmds:
            continue
        path = f"data/maps/{new}/scripts.inc"
        cur = read(path)
        npcs = ""  # the NPC scripts port_npcs.py appends to the file are kept as they are
        if NPC_BLOCK_BEGIN in cur:
            npcs = "\n" + cur[cur.index(NPC_BLOCK_BEGIN):]
            cur = cur[:cur.index(NPC_BLOCK_BEGIN)].rstrip("\n") + "\n"
        label = f"{new}_OnTransition"
        body = (f"{new}_MapScripts::\n\tmap_script MAP_SCRIPT_ON_TRANSITION, {label}\n\t.byte 0\n\n"
                f"{label}:\n" + "\n".join(cmds) + "\n\tend\n")
        if cur == body:
            continue
        if cur != f"{new}_MapScripts::\n\t.byte 0\n":
            skipped.append(new)  # scripts were edited since the map was ported; add the commands by hand
            continue
        write(path, body + npcs)
        done.append(new)
    print(f"ported {len(fheal)} heal locations; added map scripts to {len(done)} maps"
          + (f"; scripts already edited, add by hand: {', '.join(skipped)}" if skipped else ""))

def main():
    if not os.path.exists("include/constants/metatile_behaviors.h"):
        sys.exit("run from the pokeemerald root")
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    t = sub.add_parser("tilesets"); t.add_argument("--frlg", default="../pokefirered"); t.set_defaults(fn=cmd_tilesets)
    m = sub.add_parser("maps"); m.add_argument("names", nargs="*"); m.add_argument("--frlg", default="../pokefirered")
    m.add_argument("--no-warps", action="store_true"); m.add_argument("--no-connections", action="store_true")
    m.add_argument("--force", action="store_true", help="overwrite maps and layouts that were already ported")
    m.set_defaults(fn=cmd_maps)
    e = sub.add_parser("encounters"); e.add_argument("--frlg", default="../pokefirered"); e.set_defaults(fn=cmd_encounters)
    r = sub.add_parser("regionmap"); r.add_argument("--frlg", default="../pokefirered"); r.set_defaults(fn=cmd_regionmap)
    h = sub.add_parser("heal"); h.add_argument("--frlg", default="../pokefirered"); h.set_defaults(fn=cmd_heal)
    args = ap.parse_args(); args.fn(args)

if __name__ == "__main__":
    main()
