#!/usr/bin/env python3
"""Port Kanto data from pret/pokefirered into this pokeemerald tree.

    python3 tools/kanto_port/port_kanto.py tilesets --frlg ../pokefirered
    python3 tools/kanto_port/port_kanto.py maps --frlg ../pokefirered            # every map
    python3 tools/kanto_port/port_kanto.py maps PalletTown Route1 --frlg ../pokefirered

Run from the pokeemerald root. Both commands are idempotent.

tilesets: copies every FRLG tileset to data/tilesets/<kind>/kanto_<name>, converts the
          32-bit FRLG metatile attributes to Emerald's 16-bit format (remapping behaviours),
          and adds them to src/data/tilesets/{graphics,metatiles,headers}.h plus tileset_rules_kanto.mk.
          All ported symbols get a "Kanto" prefix (gTileset_KantoPalletTown) so they
          cannot collide with the Hoenn tilesets.
maps:     ports layouts and maps with their warps and connections into gMapGroup_Kanto* groups.
          Maps and layouts that already exist are left alone unless --force is given, so
          edits made afterwards (by hand or in Porymap) survive a re-run.
          NPCs, triggers and signs are stripped until their scripts are ported. Maps and layouts
          whose name already exists in Emerald get a Kanto prefix (see map_report.txt).
"""
import argparse, json, os, re, shutil, struct, sys
from collections import Counter, defaultdict

ROOT = os.getcwd()
PREFIX_SYM = "Kanto"
PREFIX_DIR = "kanto_"
BLOCK_BEGIN = "// BEGIN KANTO PORT: generated by tools/kanto_port/port_kanto.py from pokefirered. Do not edit by hand."
BLOCK_END = "// END KANTO PORT"

# FRLG behaviour name -> Emerald behaviour name. None = no Emerald equivalent (becomes MB_NORMAL,
# listed in the report so the behaviour can be re-implemented later).
BEHAVIOR_MAP = {
    "MB_NORMAL": "MB_NORMAL", "MB_UNUSED_01": "MB_NORMAL", "MB_TALL_GRASS": "MB_TALL_GRASS",
    "MB_CAVE": "MB_CAVE", "MB_RUNNING_DISALLOWED": "MB_NO_RUNNING",
    "MB_INDOOR_ENCOUNTER": "MB_INDOOR_ENCOUNTER", "MB_MOUNTAIN_TOP": "MB_MOUNTAIN_TOP",
    "MB_POND_WATER": "MB_POND_WATER", "MB_FAST_WATER": "MB_INTERIOR_DEEP_WATER",
    "MB_DEEP_WATER": "MB_DEEP_WATER", "MB_WATERFALL": "MB_WATERFALL",
    "MB_OCEAN_WATER": "MB_OCEAN_WATER", "MB_PUDDLE": "MB_PUDDLE",
    "MB_SHALLOW_WATER": "MB_SHALLOW_WATER", "MB_UNDERWATER_BLOCKED_ABOVE": "MB_NO_SURFACING",
    "MB_UNUSED_WATER": "MB_OCEAN_WATER", "MB_CYCLING_ROAD_WATER": "MB_OCEAN_WATER",
    "MB_STRENGTH_BUTTON": None, "MB_SAND": "MB_SAND", "MB_SEAWEED": "MB_SEAWEED",
    "MB_ICE": "MB_ICE", "MB_THIN_ICE": "MB_THIN_ICE", "MB_CRACKED_ICE": "MB_CRACKED_ICE",
    "MB_HOT_SPRINGS": "MB_HOT_SPRINGS", "MB_ROCK_STAIRS": None, "MB_SAND_CAVE": "MB_SAND",
    "MB_SPIN_RIGHT": None, "MB_SPIN_LEFT": None, "MB_SPIN_UP": None, "MB_SPIN_DOWN": None,
    "MB_STOP_SPINNING": None,
    "MB_CAVE_DOOR": "MB_NON_ANIMATED_DOOR", "MB_LADDER": "MB_LADDER",
    "MB_FALL_WARP": "MB_CRACKED_FLOOR_HOLE", "MB_REGULAR_WARP": "MB_AQUA_HIDEOUT_WARP",
    "MB_LAVARIDGE_1F_WARP": "MB_LAVARIDGE_GYM_1F_WARP", "MB_WARP_DOOR": "MB_ANIMATED_DOOR",
    "MB_UP_ESCALATOR": "MB_UP_ESCALATOR", "MB_DOWN_ESCALATOR": "MB_DOWN_ESCALATOR",
    # Diagonal stair warps do not exist in Emerald; nearest is a sideways arrow warp.
    "MB_UP_RIGHT_STAIR_WARP": "MB_EAST_ARROW_WARP", "MB_DOWN_RIGHT_STAIR_WARP": "MB_EAST_ARROW_WARP",
    "MB_UP_LEFT_STAIR_WARP": "MB_WEST_ARROW_WARP", "MB_DOWN_LEFT_STAIR_WARP": "MB_WEST_ARROW_WARP",
    "MB_UNION_ROOM_WARP": None,
    "MB_COUNTER": "MB_COUNTER", "MB_BOOKSHELF": "MB_BOOKSHELF", "MB_POKEMART_SHELF": "MB_SHOP_SHELF",
    "MB_PC": "MB_PC", "MB_REGION_MAP": "MB_REGION_MAP", "MB_TELEVISION": "MB_TELEVISION",
    "MB_CABLE_CLUB_WIRELESS_MONITOR": "MB_WIRELESS_BOX_RESULTS",
    "MB_BATTLE_RECORDS": "MB_CABLE_BOX_RESULTS_1", "MB_QUESTIONNAIRE": "MB_QUESTIONNAIRE",
    "MB_BLUEPRINTS": "MB_BLUEPRINT", "MB_TRASH_BIN": "MB_TRASH_CAN",
    "MB_CYCLING_ROAD_PULL_DOWN": None, "MB_CYCLING_ROAD_PULL_DOWN_GRASS": "MB_TALL_GRASS",
}
SAME_NAME = ["MB_IMPASSABLE_EAST", "MB_IMPASSABLE_WEST", "MB_IMPASSABLE_NORTH", "MB_IMPASSABLE_SOUTH",
    "MB_IMPASSABLE_NORTHEAST", "MB_IMPASSABLE_NORTHWEST", "MB_IMPASSABLE_SOUTHEAST", "MB_IMPASSABLE_SOUTHWEST",
    "MB_JUMP_EAST", "MB_JUMP_WEST", "MB_JUMP_NORTH", "MB_JUMP_SOUTH",
    "MB_WALK_EAST", "MB_WALK_WEST", "MB_WALK_NORTH", "MB_WALK_SOUTH",
    "MB_SLIDE_EAST", "MB_SLIDE_WEST", "MB_SLIDE_NORTH", "MB_SLIDE_SOUTH", "MB_TRICK_HOUSE_PUZZLE_8_FLOOR",
    "MB_EASTWARD_CURRENT", "MB_WESTWARD_CURRENT", "MB_NORTHWARD_CURRENT", "MB_SOUTHWARD_CURRENT",
    "MB_EAST_ARROW_WARP", "MB_WEST_ARROW_WARP", "MB_NORTH_ARROW_WARP", "MB_SOUTH_ARROW_WARP"]
BEHAVIOR_MAP.update({n: n for n in SAME_NAME})
# Emerald behaviours that can trigger wild encounters (TILE_FLAG_HAS_ENCOUNTERS).
EM_ENCOUNTER = {"MB_TALL_GRASS", "MB_LONG_GRASS", "MB_DEEP_SAND", "MB_CAVE", "MB_INDOOR_ENCOUNTER",
    "MB_POND_WATER", "MB_INTERIOR_DEEP_WATER", "MB_DEEP_WATER", "MB_OCEAN_WATER", "MB_SEAWEED",
    "MB_ASHGRASS", "MB_FOOTPRINTS", "MB_SEAWEED_NO_SURFACING"}


def read(p):
    with open(p, encoding="utf-8") as f:
        return f.read()

def write(p, s):
    if os.path.dirname(p):
        os.makedirs(os.path.dirname(p), exist_ok=True)
    with open(p, "w", encoding="utf-8", newline="\n") as f:
        f.write(s)

def emerald_behaviors():
    body = re.search(r"enum\s*\{(.*?)\}", read("include/constants/metatile_behaviors.h"), re.S).group(1)
    body = re.sub(r"//.*", "", body)
    names = [n.strip() for n in body.split(",") if n.strip()]
    return {n: i for i, n in enumerate(names)}

def frlg_behaviors(frlg):
    out = {}
    for m in re.finditer(r"#define\s+(MB_\w+)\s+(0x[0-9A-Fa-f]+)", read(f"{frlg}/include/constants/metatile_behaviors.h")):
        out[int(m.group(2), 16)] = m.group(1)
    return out

def convert_attributes(data, em, fr, tileset, report):
    out = bytearray()
    for i, (v,) in enumerate(struct.iter_unpack("<I", data)):
        beh, enc, layer = v & 0x1FF, (v >> 24) & 7, (v >> 29) & 3
        name = fr.get(beh)
        target = BEHAVIOR_MAP.get(name) if name else None
        if target is None:
            target = "MB_NORMAL"
        final = target
        # FRLG stores "has land encounters" as a separate attribute; Emerald derives it from the behaviour.
        lost = ""
        if enc == 1 and target not in EM_ENCOUNTER:
            if target in ("MB_NORMAL", "MB_SAND"):
                final = "MB_CAVE" if target == "MB_NORMAL" else "MB_DEEP_SAND"
            else:
                lost = " (land encounters LOST)"
        src = name or ("MB_NORMAL" if beh == 0 else f"unknown 0x{beh:02X}")
        if BEHAVIOR_MAP.get(name) is None and beh != 0 and final == "MB_NORMAL":
            lost += " (no Emerald equivalent)"
        if final != src or lost:
            report[(src + (" + land encounters" if enc == 1 else ""), final + lost)].append(f"{tileset}:{i}")
        target = final
        out += struct.pack("<H", em[target] | (layer << 12))
    return bytes(out)

def rename_symbols(text):
    text = re.sub(r"\b(gTileset|gTilesetTiles|gTilesetPalettes|gMetatiles|gMetatileAttributes)_(\w+)",
                  lambda m: f"{m.group(1)}_{PREFIX_SYM}{m.group(2)}", text)
    return re.sub(r"data/tilesets/(primary|secondary)/", lambda m: f"data/tilesets/{m.group(1)}/{PREFIX_DIR}", text)

def insert_once(path, anchor, line, after=True):
    s = read(path)
    if line in s:
        return
    if anchor not in s:
        sys.exit(f"anchor {anchor!r} not found in {path}")
    s = s.replace(anchor, anchor + "\n" + line if after else line + "\n" + anchor, 1)
    write(path, s)

def cmd_tilesets(args):
    frlg = args.frlg
    em, fr = emerald_behaviors(), frlg_behaviors(frlg)
    report = defaultdict(list)
    count = 0
    for kind in ("primary", "secondary"):
        src_root = f"{frlg}/data/tilesets/{kind}"
        for name in sorted(os.listdir(src_root)):
            src, dst = f"{src_root}/{name}", f"data/tilesets/{kind}/{PREFIX_DIR}{name}"
            if not os.path.isdir(src):
                continue
            os.makedirs(dst, exist_ok=True)
            for dirpath, _, files in os.walk(src):
                rel = os.path.relpath(dirpath, src)
                for f in files:
                    if not f.endswith((".png", ".pal", ".bin")):
                        continue  # skip build products
                    os.makedirs(os.path.join(dst, rel), exist_ok=True)
                    s, d = os.path.join(dirpath, f), os.path.join(dst, rel, f)
                    if f == "metatile_attributes.bin" and rel == ".":
                        with open(s, "rb") as fh:
                            conv = convert_attributes(fh.read(), em, fr, f"{kind}/{name}", report)
                        with open(d, "wb") as fh:
                            fh.write(conv)
                    else:
                        shutil.copyfile(s, d)
            count += 1

    # Porymap only reads the standard graphics.h / metatiles.h / headers.h, so the Kanto
    # definitions go into those files, inside a marked block that is replaced on every run.
    gfx = read(f"{frlg}/src/data/tilesets/graphics.h")
    # A few tilesets are also used outside the overworld in FRLG, so their graphics live in src/graphics.c.
    shared = re.findall(r"^const u16 gTilesetPalettes_\w+\[\]\[16\] =\n\{.*?\n\};\n|^const u32 gTilesetTiles_\w+\[\] = INCBIN_U32\(.*?\);\n",
                        read(f"{frlg}/src/graphics.c"), re.S | re.M)
    gfx += "\n" + "\n".join(shared)
    met = rename_symbols(read(f"{frlg}/src/data/tilesets/metatiles.h"))
    met = re.sub(r"const u32 (gMetatileAttributes_\w+\[\]) = INCBIN_U32", r"const u16 \1 = INCBIN_U16", met)
    heads = rename_symbols(read(f"{frlg}/src/data/tilesets/headers.h"))
    # Tile animations are not ported yet.
    heads = re.sub(r"\.callback = (InitTilesetAnim_\w+),", r".callback = NULL, // TODO: port \1 from pokefirered", heads)
    for fname, body in (("graphics.h", rename_symbols(gfx)), ("metatiles.h", met), ("headers.h", heads)):
        path = f"src/data/tilesets/{fname}"
        block = f"{BLOCK_BEGIN}\n\n{body.strip()}\n\n{BLOCK_END}\n"
        cur = read(path)
        if BLOCK_BEGIN in cur:
            cur = cur[:cur.index(BLOCK_BEGIN)] + block + cur[cur.index(BLOCK_END) + len(BLOCK_END):].lstrip("\n")
        else:
            cur = cur.rstrip("\n") + "\n\n" + block
        write(path, cur)
        # Earlier versions of this tool used separate kanto_*.h files.
        old = f"src/data/tilesets/kanto_{fname}"
        if os.path.exists(old):
            os.remove(old)
    ts = read("src/tilesets.c")
    write("src/tilesets.c", re.sub(r'#include "data/tilesets/kanto_\w+\.h"\n', "", ts))

    rules = rename_symbols(read(f"{frlg}/tileset_rules.mk")).replace(
        "$(TILESETGFXDIR)/primary/", f"$(TILESETGFXDIR)/primary/{PREFIX_DIR}").replace(
        "$(TILESETGFXDIR)/secondary/", f"$(TILESETGFXDIR)/secondary/{PREFIX_DIR}")
    rules = "\n".join(l for l in rules.splitlines() if not l.startswith("TILESETGFXDIR"))
    write("tileset_rules_kanto.mk", "# Generated by tools/kanto_port/port_kanto.py from pokefirered.\n" + rules + "\n")

    insert_once("Makefile", "include graphics_file_rules.mk", "include tileset_rules_kanto.mk")
    lines = ["Metatile behaviour conversions (FRLG -> Emerald). Entries are tileset:metatile index.", ""]
    for (a, b), where in sorted(report.items(), key=lambda kv: -len(kv[1])):
        by_ts = Counter(w.split(":")[0] for w in where)
        lines.append(f"{a} -> {b}: {len(where)} metatiles")
        lines.append("    " + ", ".join(f"{t} ({n})" for t, n in sorted(by_ts.items())))
    write("tools/kanto_port/behavior_report.txt", "\n".join(lines) + "\n")
    print(f"ported {count} tilesets; see tools/kanto_port/behavior_report.txt")

MANIFEST = "tools/kanto_port/manifest.json"
BATTLE_SCENES = {"MAP_BATTLE_SCENE_NORMAL", "MAP_BATTLE_SCENE_GYM"}  # FRLG scenes that also exist in Emerald

def load_manifest():
    if os.path.exists(MANIFEST):
        return json.loads(read(MANIFEST))
    return {"maps": {}, "layouts": {}}

def const_to_kanto(const, prefix):
    return f"{prefix}KANTO_{const[len(prefix):]}"

def cmd_maps(args):
    """Port FRLG maps (all of them unless names are given) with their layouts, warps and connections."""
    frlg = args.frlg
    fgroups = json.loads(read(f"{frlg}/data/maps/map_groups.json"))
    flayouts = {l["id"]: l for l in json.loads(read(f"{frlg}/data/layouts/layouts.json"))["layouts"] if l}
    groups = json.loads(read("data/maps/map_groups.json"))
    lj = json.loads(read("data/layouts/layouts.json"))
    manifest = load_manifest()
    songs = set(re.findall(r"#define (MUS_\w+)", read("include/constants/songs.h")))

    # Anything not created by this tool is "Hoenn" and must not be overwritten.
    kanto_groups = [g for g in groups["group_order"] if g.startswith("gMapGroup_Kanto")]
    hoenn_maps = {m for g in groups["group_order"] if g not in kanto_groups for m in groups[g]}
    ported_layout_ids = set(manifest["layouts"].values())
    hoenn_layouts = [l for l in lj["layouts"] if l and l["id"] not in ported_layout_ids]
    hoenn_layout_ids = {l["id"] for l in hoenn_layouts}
    hoenn_layout_names = {l["name"] for l in hoenn_layouts}
    hoenn_layout_dirs = {os.path.dirname(l["blockdata_filepath"]) for l in hoenn_layouts}

    # The link maps (Union Room, Trade Center...) already exist in Emerald and its link code uses them.
    skipped = set(fgroups.get("gMapGroup_Link", []))
    fmaps = {}
    for g in fgroups["group_order"]:
        for name in fgroups[g]:
            if name not in skipped:
                fmaps[name] = (g, json.loads(read(f"{frlg}/data/maps/{name}/map.json")))
    wanted = args.names or list(fmaps)
    for n in wanted:
        if n not in fmaps:
            sys.exit(f"{n}: not a portable FRLG map")

    # Names that exist in both games get a Kanto prefix. Decide this for every FRLG map so that
    # warps and connections to maps ported later still resolve to the right constant.
    map_name, map_id = {}, {}
    for name, (_, j) in fmaps.items():
        clash = name in hoenn_maps
        map_name[name] = PREFIX_SYM + name if clash else name
        map_id[j["id"]] = const_to_kanto(j["id"], "MAP_") if clash else j["id"]

    notes = []
    def port_layout(lid):
        fl = flayouts[lid]
        ldir = os.path.dirname(fl["blockdata_filepath"])
        clash = lid in hoenn_layout_ids or fl["name"] in hoenn_layout_names or ldir in hoenn_layout_dirs
        new_id = const_to_kanto(lid, "LAYOUT_") if clash else lid
        new_dir = f"data/layouts/{PREFIX_SYM}{os.path.basename(ldir)}" if clash else ldir
        entry = {
            "id": new_id, "name": (PREFIX_SYM if clash else "") + fl["name"],
            "width": fl["width"], "height": fl["height"],
            "primary_tileset": rename_symbols(fl["primary_tileset"]),
            "secondary_tileset": rename_symbols(fl["secondary_tileset"]),
            "border_filepath": f"{new_dir}/border.bin", "blockdata_filepath": f"{new_dir}/map.bin",
        }
        if os.path.exists(entry["blockdata_filepath"]) and not args.force:
            manifest["layouts"][lid] = new_id
            return new_id  # already ported; may have been edited since (e.g. in Porymap)
        os.makedirs(new_dir, exist_ok=True)
        shutil.copyfile(f"{frlg}/{fl['blockdata_filepath']}", entry["blockdata_filepath"])
        with open(f"{frlg}/{fl['border_filepath']}", "rb") as fh:
            border = fh.read()
        bw, bh = fl.get("border_width", 2), fl.get("border_height", 2)
        if (bw, bh) != (2, 2):
            # Emerald borders are always 2x2: keep the top-left 2x2 of the FRLG border.
            border = b"".join(border[(r * bw + c) * 2:(r * bw + c) * 2 + 2] for r in range(2) for c in range(2))
            notes.append(f"{new_id}: {bw}x{bh} border cropped to 2x2")
        with open(entry["border_filepath"], "wb") as fh:
            fh.write(border)
        existing = next((i for i, l in enumerate(lj["layouts"]) if l and l["id"] == new_id), None)
        if existing is None:
            lj["layouts"].append(entry)
        else:
            lj["layouts"][existing] = entry
        manifest["layouts"][lid] = new_id
        return new_id

    done_layouts = {}
    skipped_existing = []
    es = read("data/event_scripts.s")
    for name in wanted:
        fgroup, fj = fmaps[name]
        new_name = map_name[name]
        if fj["layout"] not in done_layouts:
            done_layouts[fj["layout"]] = port_layout(fj["layout"])
        if os.path.exists(f"data/maps/{new_name}/map.json") and not args.force:
            skipped_existing.append(new_name)
            continue  # already ported; may have been edited since (e.g. in Porymap)
        m = dict(fj)
        m["id"], m["name"], m["layout"] = map_id[fj["id"]], new_name, done_layouts[fj["layout"]]
        m.pop("floor_number", None)
        m.pop("connections_no_include", None)
        rg = fj["music"].replace("MUS_", "MUS_RG_", 1)
        m["music"] = rg if rg in songs else fj["music"]
        if m["music"] not in songs:
            notes.append(f"{new_name}: music {fj['music']} not in Emerald")
        if fj["battle_scene"] not in BATTLE_SCENES:
            m["battle_scene"] = "MAP_BATTLE_SCENE_NORMAL"
        m["connections"] = None if args.no_connections or not fj["connections"] else [
            dict(c, map=map_id.get(c["map"], c["map"])) for c in fj["connections"]]
        m["warp_events"] = [] if args.no_warps else [
            dict(w, dest_map=map_id.get(w["dest_map"], w["dest_map"])) for w in fj["warp_events"]]
        # NPCs, triggers and signs need their scripts ported first.
        m["object_events"], m["coord_events"], m["bg_events"] = [], [], []
        write(f"data/maps/{new_name}/map.json", json.dumps(m, indent=2) + "\n")
        scripts = f"data/maps/{new_name}/scripts.inc"
        if not os.path.exists(scripts):
            write(scripts, f"{new_name}_MapScripts::\n\t.byte 0\n")

        group = "gMapGroup_" + PREFIX_SYM + fgroup[len("gMapGroup_"):]
        for g in list(groups["group_order"]):  # move out of any other Kanto group (e.g. the old gMapGroup_Kanto)
            if g.startswith("gMapGroup_Kanto") and g != group and new_name in groups[g]:
                groups[g].remove(new_name)
                if not groups[g]:
                    groups["group_order"].remove(g)
                    del groups[g]
        if group not in groups:
            groups["group_order"].append(group)
            groups[group] = []
        if new_name not in groups[group]:
            groups[group].append(new_name)
        manifest["maps"][name] = new_name

        inc = f'\t.include "data/maps/{new_name}/scripts.inc"'
        if inc not in es:
            last = [l for l in es.splitlines() if re.match(r'\t\.include "data/maps/.*/scripts\.inc"', l)][-1]
            es = es.replace(last, last + "\n" + inc, 1)

    # Keep each Kanto group in FRLG's order so map numbers are stable however the tool was run.
    for fg in fgroups["group_order"]:
        g = "gMapGroup_" + PREFIX_SYM + fg[len("gMapGroup_"):]
        if g in groups:
            order = [map_name[n] for n in fgroups[fg] if n in map_name]
            groups[g].sort(key=order.index)
    write("data/event_scripts.s", es)
    write("data/layouts/layouts.json", json.dumps(lj, indent=2) + "\n")
    write("data/maps/map_groups.json", json.dumps(groups, indent=2) + "\n")
    write(MANIFEST, json.dumps(manifest, indent=2, sort_keys=True) + "\n")
    if len(skipped_existing) < len(wanted):  # keep the last report when nothing was ported
        renamed = sorted(f"{a} -> {b}" for a, b in manifest["maps"].items() if a != b)
        write("tools/kanto_port/map_report.txt", "\n".join(
            ["Maps renamed because the name already exists in Emerald:"] + ["    " + r for r in renamed]
            + ["", "FRLG link maps not ported (Emerald's own are used):"] + ["    " + n for n in sorted(skipped)]
            + ["", "Notes:"] + ["    " + n for n in sorted(set(notes))]) + "\n")
    print(f"ported {len(wanted) - len(skipped_existing)} maps, left {len(skipped_existing)} existing maps untouched "
          f"(use --force to overwrite them); see tools/kanto_port/map_report.txt")

def main():
    if not os.path.exists("include/constants/metatile_behaviors.h"):
        sys.exit("run from the pokeemerald root")
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    t = sub.add_parser("tilesets"); t.add_argument("--frlg", default="../pokefirered"); t.set_defaults(fn=cmd_tilesets)
    m = sub.add_parser("maps"); m.add_argument("names", nargs="*"); m.add_argument("--frlg", default="../pokefirered")
    m.add_argument("--no-warps", action="store_true"); m.add_argument("--no-connections", action="store_true")
    m.add_argument("--force", action="store_true", help="overwrite maps and layouts that were already ported")
    m.set_defaults(fn=cmd_maps)
    args = ap.parse_args(); args.fn(args)

if __name__ == "__main__":
    main()
