MegaIsland_Castle_Room3_MapScripts::
	.byte 0

MegaIsland_Castle_Room3_EventScript_Steven::
	msgbox MegaIsland_Castle_Room3_Text_Steven, MSGBOX_NPC
	end

MegaIsland_Castle_Room3_Text_Steven:
	.string "STEVEN: Oh, hello! I'm STEVEN.\n"
	.string "I came all the way from HOENN.\p"
	.string "I collect rare stones, but I'd never\n"
	.string "seen one like the stone MR. M. sent.\p"
	.string "It resonates with my METAGROSS…\p"
	.string "I'd love to know where he found it.$"
